### DISCUSSION TITLE
Docs Primary Colour

### DISCUSSION THREAD

**Discussion by Shivansh-007** [mkdocs/mkdocs#2466] [Q&A] [answered]
Is it possible to keep the primary colour code as hex colour codes, for example: `#2bb34b`.

**Comment by Shivansh-007** [comment, marked as answer]
Ah, nevermind, I found it, didn't look through the docs nicely earlier.

I can use css variables, for example:
```css
:root {
  --md-primary-fg-color:        #EE0F0F;
  --md-primary-fg-color--light: #ECB7B7;
  --md-primary-fg-color--dark:  #90030C;
}
```
