### DISCUSSION TITLE
Question about building

### DISCUSSION THREAD

**Discussion by ELEVENStudio-Main** [mkdocs/mkdocs#2560] [Q&A]
Can this run on GitHub Pages?

**Comment by mondeja** [comment]
Yes. See, for example, the next [workflow](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions) configuration:

<details>
<summary>Serve Mkdocs docs on Github Pages</summary>

```yaml
name: Github Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Github Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python v3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install .[doc]
      - name: Build documentation
        run: python -m mkdocs build
      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
```

</details>
