### DISCUSSION TITLE
`edit_uri` customization

### DISCUSSION THREAD

**Discussion by HonkingGoose** [mkdocs/mkdocs#2757] [Q&A] [answered]
Follow up from comment https://github.com/mkdocs/mkdocs/issues/2745#issuecomment-1016606060.

Pinging @viceice to help with any questions.
Pinging @oprypin as they graciously offered to help us get our configuration sorted properly. ❤️ 

## Intro

I help maintain the Renovate documentation site.

On our documentation site we have a pencil button that allows our readers to suggest changes to the source of the page. This pencil button _only_ works for files that live in the `docs/usage` directory on our main repository, which does not cover all source files on the published docs.

I need help to get our pencil button working for all files. 😉 

## Repositories we use

The vast bulk of our documentation lives in the [`renovatebot/renovate`](https://github.com/renovatebot/renovate) repository.

We write some docs, and some we auto-generate from TypeScript code.

The hand-written docs live in the [`docs/usage` folder](https://github.com/renovatebot/renovate/tree/main/docs/usage). We have a `docs/development` folder as well, but we don't publish any of those files.

We have TypeScript code that autogenerates some Markdown files, these can be found in the [`tools/docs/`](https://github.com/renovatebot/renovate/tree/main/tools/docs) directory: 

We use Git submodules to pull in the main Renovate repository and do the final build/publish step in the [`renovatebot/renovatebot.github.io` repository](https://github.com/renovatebot/renovatebot.github.io)

## `mkdocs.yml` config file

Our [`mkdocs.yml` file on the publishing repo](https://github.com/renovatebot/renovatebot.github.io/blob/main/mkdocs.yml).

Copy/paste of the `edit_uri` part of our `mkdocs.yml` config file:

```yaml
# Upstream Git repository information
# https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/
repo_name: renovatebot/renovate
repo_url: https://github.com/renovatebot/renovate
edit_uri: edit/main/docs/usage/
```

## Makefile

Here's the [Makefile](https://github.com/renovatebot/renovatebot.github.io/blob/main/Makefile) that we use to put all the pieces together and create the final build that we publish on our documentation site.
