### DISCUSSION TITLE
Trying to use codehilite with the mkdocs scheme

### DISCUSSION THREAD

**Discussion by bandokihiro** [mkdocs/mkdocs#2803] [Q&A] [answered]
Hi,

First of all, thank you very much for your work. This is an amazing tool. Also, I just started using it so I apologize in advance if my question is stupid.

I am trying to use pygments instead of highlight.js for code block syntax highlighting. The reason is that I think the superfences extension might interfer with highlight.js. Since I need this extension, I would like to switch to pygments and the codehilite extension.

I followed the [recipe](https://github.com/mkdocs/mkdocs/issues/1019) but can't get it to work. Attached is a minimal reproducer. The python code block is not highlighted for me (see attached picture).

Thank you very much for your help.
[reproducer.zip](https://github.com/mkdocs/mkdocs/files/8191341/reproducer.zip)
![Screenshot from 2022-02-26 17-30-45](https://user-images.githubusercontent.com/39278362/155864586-86dff37e-cb3a-469f-8a22-3fc76bfca803.png)

**Comment by bandokihiro** [comment, marked as answer]
Thanks to @facelessuser for helping me getting what I want.

The initial goals were
- to be able to have code blocks without highlighting with
~~~
```plaintext
a plain text
```
~~~
- to be able to use the superfences extension for nested code blocks

By default, mkdocs uses highlight.js. I wasn't able to make the first goal work with that (see below for the fix) so I tried codehilite instead. The first issue I had is the one presented in this post. This was fixed by generating a .css file which targets the `codehilite` class instead of `highlight` with something like this
```
pygmentize -S monokai -f html -a .codehilite > docs/monokai.css
```

Then, the problem presented in my previous post was solved but I bumped into another issue (which I am not able to characterize precisely anymore, sorry) which made me want to go back to trying highlight.js.

The superfences extension uses the highlight extension for syntax highlighting. By default, the highlight extension uses pygments (which highlights `plaintext` blocks). A configuration that fulfills the requirements, regardless whether or not you have pygments installed in your system, is the following:
```yaml
site_name: My Docs

theme:
  name: mkdocs
  highlightjs: true
  hljs_style: night-owl # or any other theme provided by highlight.js

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.highlight: # provide options that apply also to the superfences extension
      use_pygments: false
```
