### DISCUSSION TITLE
Error while copying build files to gh-pages branch and pushing to GitHub

### DISCUSSION THREAD

**Discussion by DiabolusGX** [mkdocs/mkdocs#2840] [Q&A] [answered]
Hi, I'm trying to setup GitHub action when there is an push in master branch, it builds and deploys docs.
The build was successful but getting 403 during fetching the repo that I'm trying to setup action on (same repo)
```yml
- run: mkdocs gh-deploy --force
```
I have 2FA enabled, it might be related but I'm not sure where to put access token (if it's required on public repo)

`CI.yml` file:
```yml
name: CI
on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install --upgrade pip && pip install mkdocs mkdocs-gen-files
      - run: pip install mkdocs-material
      - name: Publish docs
        run: mkdocs gh-deploy --force
```

---

### Error:

![brave_3MgScXXuhE](https://user-images.githubusercontent.com/48189581/167503569-c8afa72b-7fec-48a4-b606-def4e2615430.png)
