### DISCUSSION TITLE
git-revision-date-localized-plugin for MkDocs fallback to date on Github Action

### DISCUSSION THREAD

**Discussion by NicolasMassart** [mkdocs/mkdocs#2843] [Q&A] [answered]
Hi,

I have Github Actions running Mkdocs in a Docker `python:3.9-alpine` image for almost one year now.
2 weeks ago, the `mkdocs build -s` started to fail because of `git-revision-date-localized-plugin` raising warnings:
```
WARNING  -  [git-revision-date-localized-plugin] Unable to read git logs of '/workspace/tests/docs'. Is git log readable? Option 'fallback_to_build_date' set to 'true': Falling back to build date
```
This is new. It was working fine before and I detected this error when building a new image with a config change on a file that has nothing to do with Mkdocs (adding an exclusion in the link checker config for another action workflow).

The workflow uses action checkout@v2 with the depth to 0 of course:

```
      - name: Checkout code from repos
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Required for mkdocs to be able to display pages last update info
```

So of course, the build fails now as I don't want to allow any warnings for production use. This is a requirement to have this with `-s`

I tried building the same image in a local Ubuntu VM, it works, changing base image to Alpine and install python manually, it works, use older versions of git-revision-date-localized-plugin it works, tried other versions of python, everything works locally, but then once in Github action, it fails. Not sure what to test now...

Anyone had issue with `git-revision-date-localized-plugin` on Github Action recently ?
Thanks for your help.
