### DISCUSSION TITLE
Why is the Metadata extension non-functional in MkDocs?

### DISCUSSION THREAD

**Discussion by wilhelmer** [mkdocs/mkdocs#2939] [Q&A]
As described in this [MkDocs Material issue](https://github.com/squidfunk/mkdocs-material/issues/4179), I recently noticed that the [Python-Markdown Metadata extension](https://python-markdown.github.io/extensions/meta_data/) is essentially non-functional in MkDocs.

The reason for this is that the metadata functionality is built-in natively in MkDocs, precisely in [mkdocs/utils/meta.py](https://github.com/mkdocs/mkdocs/blob/master/mkdocs/utils/meta.py).

This built-in functionality takes precedence over the Metadata extension. So when the Metadata extension parses the Markdown content, **all metadata has already been stripped, and the extension does effectively nothing**.

mkdocs.yml
 
```yml
site_name: Test Project
markdown_extensions:
  - meta  # <<< this does effectively nothing! 
nav:
  - Welcome: index.md
```

So I'd like to know: 

Is that intended? Why is the metadata extension built-in? Why is it the only one that's built-in? Should it really take precedence over the original extension?
