### DISCUSSION TITLE
Why is the file always in front of the folder in the auto-generated navigation

### DISCUSSION THREAD

**Discussion by shu307** [mkdocs/mkdocs#2955] [Q&A]
I'm trying to organize auto-generated navigation with numbers.
![QQ截图20220826010138](https://user-images.githubusercontent.com/26036149/187030947-449f6543-9b1c-4fde-93d6-ab5580e85a98.png)
I am using `material` theme, and have tested without theme, get the same situation.
Or is there any other convenient way for organization?
For example, markdown meta-data like this:
``` yaml
---
title: foo
..
weight: 2
..
---
```
here is my mkdocs.yml
--Forgive my poor english, please let me know if there is anything unclear

``` yaml
site_name: My Docs
theme:
    name: material
    palette:
        primary: white
    font: false
    language: zh
    features:
        - navigation.instant
        - navigation.tracking
        - navigation.tabs
        - navigation.expand

markdown_extensions:
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
```
