### DISCUSSION TITLE
Make tables from the ReadTheDocs theme wrap text instead of adding horizontal scroll bar

### DISCUSSION THREAD

**Discussion by eggohito** [mkdocs/mkdocs#3035] [Q&A] [answered]
Hello! I've been wondering if there's a way to do this. Ever since the docs I'm working on *([apace100/origins-docs](https://github.com/apace100/origins-docs))* used Mkdocs >= 1.3.1, tables have this horizontal scroll bar instead of wrapping the text, like it used to.

I've tried using the `extra_css` configuration option to tweak `table` like so:
```css
table {
    table-layout: fixed;
    width: 100%;
}
```
but that doesn't seem to have worked. :thinking: Sorry for the dumb question, I'm quite new to CSS

**Comment by monodera** [comment, marked as answer]
I have the same wish and found that it has been discussed in the upstream readthedocs repo.

I added the following entries in the custom css file and it worked.

```css
.wy-table-responsive table td, .wy-table-responsive table th {
    white-space: normal !important;
}

.wy-table-responsive {
    overflow : visible !important;
}
```

See, for example:
https://github.com/readthedocs/sphinx_rtd_theme/issues/295
https://github.com/readthedocs/sphinx_rtd_theme/issues/117
