### DISCUSSION TITLE
Reuse of sections in different parts of the navigation

### DISCUSSION THREAD

**Discussion by msoutopico** [mkdocs/mkdocs#3064] [Q&A]
Hi there, 

I'm trying to create several guides that have some parts unique to each guide and other parts that are shared among several guides.

My nav looks like this: 

```
nav:
    - Guide1: 
        - Foo: foo.md
        - Bar: bar.md
        - Qux: qux.md
    - Guide2: 
        - Foo: foo.md
        - Bar: bar.md
        - Baz: baz.md
```

There you can see that `Foo` and `Bar` are shared and common to both guides, but that `Qux` is specific to guide 1 whereas `Baz` is specific to guide 2. 

So far so good. The problem is the following: 

### Precondition 

+ User is on Guide1/Foo. 

### Steps 

1. The user clicks on the next arrow at the bottom to go to Guide1/Bar.
2. The user clicks on the next arrow at the bottom to go to Guide1/Qux.

### Expected results

1. The user lands on Guide1/Bar
2. The user lands on Guide1/Qux

### Actual results

1. The user lands on Guide2/Bar
2. The user lands on Guide2/Baz

Maybe there's a better of handling this structure? Any tips? 
Thanks.
