### DISCUSSION TITLE
Permanent links to files, unchainging when file is moved

### DISCUSSION THREAD

**Discussion by Emmanuel-Messulam** [mkdocs/mkdocs#3091] [Q&A]
Is there a way to link to a file, not as file with a name in a directory, but specifically to a file?

Example implementation:

```yaml
...
nav:
    - Home: index.md
        link: aaanbbbcdsc
    - Some Info:
        - A thing: info/thing.md
            link: thing
```

Then you'd be able to use both `localhost:8000/aaanbbbcdsc` and `localhost:8000/index.md` to access index.md. Similarly with thing.md.

This helps us with reordering the files, as the links wouldn't change; this is similar to how google drive works.
