### DISCUSSION TITLE
MkDocs - Azure Static WebApp Configuration

### DISCUSSION THREAD

**Discussion by danorama-dh** [mkdocs/mkdocs#3104] [Q&A]
I would like to host my MkDocs repo on GitHub on Azure as a Static Web App. However, I am failing with the configuration. Can anyone help me with the GitHub WorkFlow or configuration?

My ./github/workflows/azure-static-[...].yml

```
name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main


jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_MANGO_FLOWER_01EAF0703 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "site" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_[...] }}
          action: "close"
```

Especially with this part:

```
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "site" # Built app content directory - optional
```

I get the following error:

```
App Directory Location: '/' was found.
Looking for event info
Starting to build app with Oryx
Azure Static Web Apps utilizes Oryx to build both static applications and Azure Functions. You can find more details on Oryx here: https://github.com/microsoft/Oryx
Oryx will build app with the following custom override command: mkdocs build
---Oryx build logs---


Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues

Oryx Version: 0.2.20221103.1, Commit: [...]

Build Operation ID: [...]
Repository Commit : [...]

Detecting platforms...
Could not detect any platform in the source directory.
Error: Could not detect the language from repo.


---End of Oryx build logs---
Oryx was unable to determine the build steps. Continuing assuming the assets in this folder are already built. If this is an unexpected behavior please contact support.
Finished building app with Oryx
No Api directory specified. Azure Functions will not be created.
Failed to find a default file in the app artifacts folder (/). Valid default files: index.html,Index.html.
If your application contains purely static content, please verify that the variable 'app_location' in your workflow file points to the root of your application.
If your application requires build steps, please validate that a default file exists in the build output directory.


For further information, please visit the Azure Static Web Apps documentation at https://docs.microsoft.com/en-us/azure/static-web-apps/
If you believe this behavior is unexpected, please raise a GitHub issue at https://github.com/azure/static-web-apps/issues/
Exiting
```

THANK YOU!!!

**Comment by Gijsreyn** [comment]
I'm using it in Azure DevOps like the following:

```yaml
- task: AzurePowerShell@5
        displayName: "Retrieve deployment token"
        inputs:
          azureSubscription: ${{ parameters.serviceConnection }}
          ScriptType: "InlineScript"
          azurePowerShellVersion: LatestVersion
          Inline: |
            $AppSecret = Get-AzStaticWebAppSecret -ResourceGroupName '${{ parameters.resourceGroupName }}' -Name '${{ parameters.siteName }}'

            $deploymentToken = ($AppSecret.property | ConvertFrom-Json).apiKey

            Write-Host "##vso[task.setvariable variable=swaToken;issecret=true]$deploymentToken"

      - task: AzureStaticWebApp@0
        displayName: "Deploy SWA"
        inputs:
          app_location: "/site/"
          api_location: ""
          output_location: "./"
          azure_static_web_apps_api_token: "$(swaToken)"
          workingDirectory: $(Pipeline.Workspace)
```
