### DISCUSSION TITLE
watermark insertion

### DISCUSSION THREAD

**Discussion by ZirconfleX** [mkdocs/mkdocs#3112] [Q&A] [answered]
Hi,
Is there a way to let MkDocs automatically insert a watermark text or figure on the pages it creates (behind or in front of the text and figures)?

Thanks,

**Comment by rachel-rigdon-sp** [comment]
I am also trying to figure out how to do this.

**Reply by kamilkrzyskow** [reply, marked as answer]
And you asked on mkdocs-material:
- https://github.com/squidfunk/mkdocs-material/discussions/7365

Worth mentioning here

**Reply by pawamoy** [reply]
Marked as answer since the CSS solution suggested by Alex would work with any theme. For reference:

```css
.md-content__inner.md-typeset:before {
  content: "DRAFT";
  -webkit-transform: rotate(331deg);
  -moz-transform: rotate(331deg);
  -o-transform: rotate(331deg);
  transform: rotate(331deg);
  font-size: 20em;
  color: rgba(255, 5, 5, 0.17);
  position: absolute;
}
```

Just update the element selector depending on the generated HTML.

Thanks again @kamilkrzyskow for bridging discussions :heart:
