### DISCUSSION TITLE
What does the key `theme: include_sidebar: false` mean?

### DISCUSSION THREAD

**Discussion by reregaga** [mkdocs/mkdocs#3114] [Q&A]
Here https://www.mkdocs.org/user-guide/configuration/#theme I see an example of code with a key `include_sidebar: false` :
```yml
theme:
    name: mkdocs
    locale: en
    custom_dir: my_theme_customizations/
    static_templates:
        - sitemap.html
    include_sidebar: false
```
But I don't understand what it does?
The other keys are described in the documentation, but this one is not mentioned.
