### DISCUSSION TITLE
How to link (correctly) to a heading? (in nav)

### DISCUSSION THREAD

**Discussion by botkero** [mkdocs/mkdocs#3151] [Q&A]
Hello,
I always get a warning in Mkdocs that I seem to be specifying a relative path. It does work, but the warning is certainly for a reason and prevents my page from being built when I use `--strict`.

Here I have reduced the project structure to the minimum:  
```txt
mkdocs-project
├── docs
│    ├── folder1
│    │    └── index.md
│    └── index.md
└── mkdocs.yml
```

In addition my `nav`:  
```yaml
nav:
  - Home: index.md
  - Test:
      - folder1/index.md
      - Test_Heading1: folder1/#heading1  # How would I link properly here?
```

I have tried a few things, but I have the impression as soon as I try to link something from my Index.md, it is considered relative.
Maybe someone can help me here?

Edit:

```
WARNING  -  A relative path to 'folder1/#heading1' is included in the 'nav' configuration, which is not
            found in the documentation files
```
