### DISCUSSION TITLE
[question] How to have a click to copy feature for code blocks ?

### DISCUSSION THREAD

**Discussion by aahnik** [mkdocs/mkdocs#3177] [Q&A] [answered]
I am curious to know how can I have click to copy button on the top right corner, using the `read the docs` theme

![click_to_copy_in_docs](https://user-images.githubusercontent.com/66209958/99977390-91effd00-2dca-11eb-9816-f8ed66230641.gif)

You can see an example here https://docs.pyrogram.org/

**Comment by waylan** [comment]
I'm assuming that is using a newer version of the theme. Out clone of the theme is based on an older version. We would need to update the theme to the newer version.

Although, that may not matter. Click to copy is generally a feature of a syntax highlighter and if we are using a different one, things may not work the same. However, that would require some investigation to determine how it is implemented there.

**Comment by squidfunk** [comment]
[Material for MkDocs](https://github.com/squidfunk/mkdocs-material) - a popular theme - integrates with Clipboard.js and supports this functionality out-of-the-box 😊

You can check the implementation - it’s easy to add with some extra JS!

**Comment by aahnik** [comment]
Material for mkdocs is a cool theme, and many modern projects use it. But I am still attracted to the old readthedocs theme.

How can I add the copy to clipboard feature there ?

> Out clone of the theme is based on an older version. We would need to update the theme to the newer version.

How can I do this ? Can you please give link to relevant docs, so that I can learn about changing the theme ?

It would be great if mkdocs provides "copy to clipboard" for readthedocs theme, out of the box.

thank you.

**Comment by kgibm** [comment, marked as answer]
> It would be great if mkdocs provides "copy to clipboard" for readthedocs theme, out of the box.

I accomplished this as follows:

1. Import [ClipboardJS](https://clipboardjs.com/) and [Tippy](https://github.com/atomiks/tippyjs) (`tippy-bundle.umd.js` and `popper.min.js`) into a `js` subfolder.
2. Create `css/extra.css` which styles the copy-to-clipboard button:
   ```css
   .clipboard {
       position: relative;
       display: block;
       float: right;
   }
   
   .btn-clipboard {
       position: relative;
       top: .5rem;
       right: .5rem;
       z-index: 10;
       display: block;
       padding: .25rem .5rem;
       cursor: pointer;
   }
   ```
3. Create `js/extra.js` which uses jQuery (built into the theme) to wait for the page to load and then find all `code` blocks, insert a Copy button, and add handlers:
   ```javascript
   $(document).ready(function() {
     // https://clipboardjs.com/
     var selectors = document.querySelectorAll('pre code');
     var copyButton = '<div class="clipboard"><span class="btn btn-neutral btn-clipboard" title="Copy to clipboard">Copy</span></div>';
     Array.prototype.forEach.call(selectors, function(selector){
       selector.insertAdjacentHTML('beforebegin', copyButton);
     });
     var clipboard = new ClipboardJS('.btn-clipboard', {
       target: function (trigger) {
         return trigger.parentNode.nextElementSibling;
       }
     });
   
     clipboard.on('success', function (e) {
       e.clearSelection();
   
       // https://atomiks.github.io/tippyjs/v6/all-props/
       var tippyInstance = tippy(
         e.trigger,
         {
           content: 'Copied',
           showOnCreate: true,
           trigger: 'manual',
         },
       );
       setTimeout(function() { tippyInstance.hide(); }, 1000);
     });
   });
   ```
4. Update `mkdocs.yaml`:
   ```
   extra_css:
     - css/extra.css
   extra_javascript:
     - js/popper.min.js
     - js/tippy-bundle.umd.js
     - js/clipboard.js
     - js/extra.js
   ```

**Reply by niccokunzmann** [reply]
Thank you! I modified the CSS so the copy button inside:

```
.clipboard {
    position: relative;
    display: block;
    float: right;
    right: 18px;
    line-height: 0px;
    width: 0px;
}

.clipboard:hover {
  color: var(--md-accent-fg-color);
  transition: color 125ms;
}
```

And, I use this instead of "Copy" `⧉` .

![grafik](https://github.com/mkdocs/mkdocs/assets/564768/52cead89-c149-4d8b-91e6-6b9993394f0f)

**Reply by Sieboldianus** [reply]
Great, thanks to you two! In my mkdocs reathedocs theme, I had to do a bit more css twiggling to get it working:
```css
pre {
  position: relative;
}

/* Container for the clipboard icon */
.clipboard {
  position: absolute;
  top: 0.5rem;
  right: 0.5rem;
  line-height: 1;
  width: auto;
  height: auto;
  z-index: 10;
}

/* Target the button with enough specificity */
.clipboard > .btn-clipboard {
  all: unset;
  font-family: "Font Awesome 6 Free";
  font-weight: 900;
  font-size: 1rem;
  color: silver;
  cursor: pointer;
  display: inline-block;
  vertical-align: middle;
  transition: color 150ms ease-in-out;

  text-indent: -9999px;
  overflow: hidden;
  width: 1.2em;
  height: 1.2em;
  position: relative;

  /* Remove backgrounds, borders, shadows */
  background: transparent;
  border: none;
  box-shadow: none;
  user-select: none;
}

/* Also remove background etc on hover */
.clipboard > .btn-clipboard:hover {
  background: transparent;
  border: none;
  box-shadow: none;
  color: black;
}

/* Icon content */
.clipboard > .btn-clipboard::before {
  content: "\f0c5";
  position: absolute;
  left: 0;
  top: 0;
  text-indent: 0;
  color: silver;
}

/* Make icon black on hover */
.clipboard > .btn-clipboard:hover::before {
  color: black;
}

/* Remove scaling/transform on click */
.clipboard > .btn-clipboard:active {
  transform: none;
  transition: none;
  outline: none;
}

span.btn.btn-neutral.btn-clipboard:hover {
  background-color: transparent !important;
  color: black !important;
  box-shadow: none !important;
  border: none !important;
}
```

I also had to download the FA woff files and store them to webfonts/ folder.
