### DISCUSSION TITLE
'Copy' button for code blocks is missing after upgrading from 1.3.0 to 1.4.3

### DISCUSSION THREAD

**Discussion by syntezzz1** [mkdocs/mkdocs#3212] [Q&A] [answered]
I don't know why, but the button is missing. 
![image](https://user-images.githubusercontent.com/84198235/236430892-fc43f343-ad7b-4469-b621-86ae9a002e6a.png)
![image](https://user-images.githubusercontent.com/84198235/236431095-bf54087f-8137-4e8a-88c6-207eb4cf7c4f.png)

I've tried to use the following `markdown_extensions`

```
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
 ```
    
I've also used `js/clipboard.js` and `features: - content.code.copy`, but it's not working. I'm using the Material theme. Does anyone have any ideas why this is happening?"
