### DISCUSSION TITLE
How to type a config option that is a dict[str, str]?

### DISCUSSION THREAD

**Discussion by pawamoy** [mkdocs/mkdocs#3240] [Q&A] [answered]
I want to add a config option to a plugin. The option takes a dict[str, str]:

```
plugins:
- myplugin:
    option:
      a: b
      c: d
```

I can't use `Type(Dict[str, str])`, and `SubConfig` wouldn't make sense since I don't know the keys in advance. I don't see a `Map` type or equivalent, only lists of items. Should I just use `Type(dict)` and lose type checks on the keys and values?

Maybe I can create such a `Dict` config type myself?
