### DISCUSSION TITLE
Global variable to keep track of a value in a recursive function

### DISCUSSION THREAD

**Discussion by redtide** [mkdocs/mkdocs#3250] [Q&A] [answered]
I have some data to parse recursively like:
```yml
opcodes:
  - name: "a"
    type_id: 1
    children:
    - name: "b"
      children:
      - name: "c"
```
where children inherit some variables, in this case `type_id`.
It seems that I get the variable empty, no matter where I set it, when I reach "c", so I'm wondering if this is supported and I'm doing something wrong, or not and so how I can solve it.
The recursive function is an imported macro called from a macro include, so I'm not sure if I should ask in the related plugin project or here.

**Comment by pawamoy** [comment]
I personally do not understand what your issue is based on the information you provided, or how to help you. You should provide additional info like the macro/recursive function you're mentioning, and how you use it in your Markdown page or template (how you load it, how you call it, where the data comes from, what you expect to see, etc.) :)

**Reply by redtide** [reply]
basically I want, via recursive function, that the `type_id` in the "granparent opcode" to be saved in a (global) variable to use it when the function reaches "c".
In the example below is the parameter `version`, set to "ARIA", to be saved when I reach `amplitude_ccN` during recursion, so that I can add it to the `Version` column of the table.

**Comment by redtide** [comment]
This currently works, but still with Jekyll at <https://sfz.tools/sfizz/development/status/opcodes/?q=amplitude_ccN>

`mkdocs.yml`:
```yml
# ...
plugins:
  macros:
    include_yaml:
  # - other data...
    - sfz_syntax: "data/sfz/syntax.yml"
    include_dir: "includes"
```
`data/sfz/syntax.yml`:
```yml
categories:
- name: "Performance Parameters"
  types:
  - name: "Amplifier"
    opcodes:
    - name: "amplitude"
      version: "ARIA" # value to inherit
      modulation:
        midi_cc:
        - name: "amplitude_onccN" # this inherits the value
          alias:
          - name: "amplitude_ccN" # this doesn't inherits the value
```

a page, `docs/opcodes/index.md`, contains a HTML table:
```markdown
---
title: Opcodes Support Table
---
{% include "opcodes_table_generator.j2" %}
```
generated by `includes/opcodes_table_generator.j2`:
```jinja
{# Keep track of the last specified opcode version in the hierarchy
    to be inherited when not specified by a child. #}
{%- set opcode_version = "" %}

{%- macro add_opcode_to_table(category, opcode, parent_opcode = none, is_alias = false) %}
  <tr>
    {# some other stuff... #}
    {%- if opcode.version %} 
      {%- set opcode_version = opcode.version %}
    {%- elif parent_opcode.version %}
      {%- set opcode_version = parent_opcode.version %}
    {%- endif %}
    <td>{{ opcode_version }}</td> {# THIS ONE... #}
    {# some other stuff... #}
  </tr>

{# Rescan recursively #}
  {%- for alias in opcode.alias %}
    {{- add_opcode_to_table(category, alias, opcode, true) }}
  {%- endfor %}

  {%- if opcode.modulation and opcode.modulation.midi_cc %}
    {%-for midi_cc in opcode.modulation.midi_cc %}
      {{- add_opcode_to_table(category, midi_cc, opcode) }}
    {%- endfor %}
  {%- endif %}
{%- endmacro %}

<table>
  <thead>
    <tr>
      <th>Opcode</th>
      <th>Version</th> {# ...GOES IN THIS COLUMN #}
      <th>Supported</th>
      <th>Comment</th>
    </tr>
  </thead>
  <tbody>
  {%- for category in sfz_syntax.categories %}
    {%- for toplevel_opcode in category.opcodes %}
      {{- add_opcode_to_table(category, toplevel_opcode) }}
    {%- endfor %}
    {%- for category_type in category.types %}
      {%- for toplevel_opcode in category_type.opcodes %}
        {{- add_opcode_to_table(category_type, toplevel_opcode) }}
      {%- endfor %}
    {%- endfor %}
  {%- endfor %}
  </tbody>
</table>
```
