### DISCUSSION TITLE
Using ordered list with content tabs breaks list order

### DISCUSSION THREAD

**Discussion by markosopcic** [mkdocs/mkdocs#3270] [Q&A] [answered]
Hi! I'm using content tabs inside an ordered list and it seems to break either the list order or the content tabs.
E.g.:

```
1. Some text
2. Some content tabs:
=== "Tab1"
       ```
       some code block here
       ```
=== "Tab2"
       ```
       more code here
       ```
3. continue with ordered list
```

In this case, the number 3 gets rendered as 1
<img width="782" alt="image" src="https://github.com/mkdocs/mkdocs/assets/32719316/b99f6ac5-4a05-4ebc-98d0-8a06dbcb79bd">

Is there any way to avoid this happening?

**Comment by pawamoy** [comment]
Try to indent your tabs to put them under the list's second item:

```md
1. Some text
2. Some content tabs:
    === "Tab1"
        ```
        some code block here
        ```
    === "Tab2"
        ```
        more code here
        ```
3. continue with ordered list
```

**Reply by markosopcic** [reply]
@pawamoy  I did try that, but unfortunately it doesn't render correctly. 

![image](https://github.com/mkdocs/mkdocs/assets/32719316/2346c5b5-8278-4f91-9c76-497c897adcc2)

**Reply by pawamoy** [reply]
Try to add blank lines then:

```md
1. Some text
2. Some content tabs:

    === "Tab1"
        ```
        some code block here
        ```

    === "Tab2"
        ```
        more code here
        ```

3. continue with ordered list
```

**Reply by markosopcic** [reply]
@pawamoy tried that as well, also doesn't work 😕 
![image](https://github.com/mkdocs/mkdocs/assets/32719316/be3dcf20-216d-4501-9a62-db88c316cb86)

**Reply by pawamoy** [reply]
It's working well on my end, you must be missing some configuration in mkdocs.yml. Here's mine:

```yaml
# mkdocs.yml
markdown_extensions:
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
    slugify: !!python/object/apply:pymdownx.slugs.slugify
      kwds:
        case: lower
```
