### DISCUSSION TITLE
Cannot use string interpolation in mkdocs.yml

### DISCUSSION THREAD

**Discussion by msrouchou** [mkdocs/mkdocs#3279] [Q&A]
It seems one cannot use string interpolation in order to reuse yml keys. 

```yml
extra:
  version: !ENV [SITE_VERSION, 'dev']
 
extra_css: 
  - "assets/css/theme-override.css?v=#{extra.version}"
```

would yield in the html: 
```html
<link rel="stylesheet" href="assets/css/theme-override.css?v=#{extra.version}">
```

I also tried the anchors and it was not better: 
```yml
extra:
  version: &resolvedVersion !ENV [SITE_VERSION, 'dev']
 
extra_css: 
  - "assets/css/theme-override.css?v=#{*resolvedVersion}"
```

Is there a way to achieve this ?
Thank you!
