### DISCUSSION TITLE
Deploy option for other repository hostings?

### DISCUSSION THREAD

**Discussion by Andre601** [mkdocs/mkdocs#3298] [Q&A] [answered]
We all know that `gh_deploy` is a thing to directly build and push a page to a repository's `gh-pages` branch.

What I'm wondering is, if the command allows a different, non-github host to be given.
I host a page using MkDocs on Codeberg which offers a feature similar to GitHub pages, but obviously, just using `gh-deploy` may not work as expected...

Do I just change the target bracnh? Or would additional changes be needed? From what I know is this just a `mkdocs build -> git add ... -> git commit -m "Message" -> git push` flow (Very simplified).

---

Either way, I'm also wonder how GitHub dependand MkDocs is. Like are there parts of it that are focused on GitHub itself?
And would it be an option to allow other Remote repo hosts in the future?

**Comment by oprypin** [comment, marked as answer]
`gh-deploy` is a command that performs `mkdocs build`, then replaces the contents of a particular Git branch with the result, then pushes it. The only thing that can be called specific to GitHub is that the **default branch name** is "gh-pages"; but it's overridable, of course.

The functionality *is* specific to Git. But the host can be anything at all, as long as you can push to it.

And in any case you can **always** run `mkdocs build` and copy the files over however you want instead. It is **100%** equivalent.

---

 I will also point out that even for GitHub in my opinion `gh-deploy` is not the best option, and I never use it for any sites that I make. Why limit yourself to a particular opinionated way of copying files over, when you can copy them in any way you like, and for GitHub Actions the variety of available actions for that is really compelling.

In particular for CI I really like this idiom:
https://github.com/oprypin/mkdocs-gen-files/blob/b02016c315e25017f5678e190d98f53c64c99446/.github/workflows/deploy-docs.yml#L20-L24
```yaml
      - name: Build site
        run: mkdocs build
      - name: Deploy to gh-pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: oprypin/push-to-gh-pages@v3
        with:
          publish_dir: site
```
-Always build the site for any pull request or push (for the purposes of validation), but then copy the files only if it's an actual push to master. Why would I need gh-deploy to build the site anew for me?

As such, my opinion is that `gh-deploy` shouldn't receive any further configurability, as the flexibility of external tooling will always beat it. It'll just be preserved as is.

**Reply by Andre601** [reply]
My questions were mostly for curiosity sake, as I use MkDocs on Codeberg pages using their Woodpecker CI instance (See file [here](https://codeberg.org/Andre601/blog-source/src/branch/master/.woodpecker.yml)).

I was mostly curious on if the command was rigit or more open, which given your answer seems to be the second.

**Comment by Andre601** [comment]
This just came to mind recently (a few minutes ago to be completely honest), but wouldn't it be good to deprecate `gh-deploy` and instead have a general `deploy` command?

Because looking at the command, a new user may get the impression that the command is only meant for GitHub, instead of being a command that only does some specific, generic steps with only the branch being GitHub specific.

So having that command deprecated in favour of a more neutral sounding `deploy` command would be useful here.

Tho, a change that would imo be required is to have the command require a branch to be specified. So that the full syntax is `mkdocs deploy <branch>`
It would behave the same as `gh-deploy`. The only change is more visual, ignoring the branch requirement obviously.

Truth be told, I wouldn't use the command most likely as - at least for non-GitHub repositories - I use a `mkdocs build -> git commit -> git push` aproach.

My idea is mostly for new users of MkDocs. Because when they see `gh-deploy`, their first thought would most likely be that it is only meant for GitHub, even tho that isn't the case.
A more neutral sounding `deploy` command would allow them to understand that it is a general-purpose command that only performs a few convenience steps.

Just a random thought tho.

**Reply by Andre601** [reply]
Just noticed that the gh-deploy command also adds a line about the URL it will be available for.

If a change like the above would be made, then either this line would need to be removed or somehow be changed (i.e. by pulling the URL from the one defined in mkdocs.yml if present)...

**Comment by redtide** [comment]
If can be useful for someone as alternative, I just experimented to deploy manually and got it working this way:
```yml
      - name: Build site
        run: poetry run mkdocs build
      - name: Upload to GitHub pages
        if: github.ref_name == 'master' && github.event_name != 'pull_request'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: www
          publish_dir: ./_site
          force_orphan: true
```
in this case I used:
- [peaceiris/actions-gh-pages](https://github.com/peaceiris/actions-gh-pages) to publish pages
- [poetry](https://github.com/python-poetry/poetry/) as python package manager
- `www` as orphan, independent deploy branch
- `_site` as custom `site_dir`

**Reply by Andre601** [reply]
I personally recommend a setup that uses the "GitHub Actions" setting in the Pages option of your repository.
It is more tedious to do, but benefit is that you don't need a separate branch for the published page, while also eliminating extra workflows (Which branch setup uses as it effectively runs a "deploy static page" setup in the end)

```yaml
name: Publish site

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
    #paths: # Recommended to avoid extra builds
    #  - .github/workflows/your_site_publish_file.yml
    #  - docs/**
    #  - mkdocs.yml
    #  - requirements.txt

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: github-pages
  cancel-in-progress: false

jobs:
  buildAndPublish:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Recommended for git localized plugin
      - name: Setup Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python -m pip install -U pip setuptools
          python -m pip install -r requirements.txt # Define your dependencies in this file.
      - name: Build Pages
        run: mkdocs build
      - name: Configure GitHub Pages # No idea if that actually does anything...
        uses: actions/configure-pages@v4
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: site/ # Important. Set to your output dir in MkDocs
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
```
