### DISCUSSION TITLE
TypeError: slugify() takes 0 positional arguments but 2 were given

### DISCUSSION THREAD

**Discussion by kiraware** [mkdocs/mkdocs#3301] [Q&A]
I see deprecated warning about using `uslugify()`, and then i update to `slugify()` in `mkdocs.yml`. But it complain about `TypeError: slugify() takes 0 positional arguments but 2 were given`

```
DeprecationWarning: 'uslugify' is deprecated. 'uslugify' is deprecated in favor of the configurable 'slugify'
function. See documentation for more info.
  File "D:\Document\Project\my-project\venv\lib\site-packages\markdown\extensions\toc.py", line 285, in run       
    el.attrib["id"] = unique(self.slugify(innertext, self.sep), used_ids)
  File "D:\Document\Project\my-project\venv\lib\site-packages\pymdownx\util.py", line 315, in _deprecated_func    
    warnings.warn(
```

I changed  `mkdocs.yml` from this
```yml
markdown_extensions:
  - toc:
      baselevel: 2
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
```

To this
```yml
markdown_extensions:
  - toc:
      baselevel: 2
      permalink: true
      slugify: !!python/name:pymdownx.slugs.slugify
```

This is caused by my `index.md`. If i remove these line, everything runs well.
```md
{%
    include-markdown "../README.md"
%}

```

pip freeze
```
click==8.1.6
griffe==0.32.3
Markdown==3.3.7
markdown-it-py==3.0.0
MarkupSafe==2.1.3
mccabe==0.7.0
mdurl==0.1.2
mergedeep==1.3.4
mkdocs==1.4.3
mkdocs-autorefs==0.4.1
mkdocs-include-markdown-plugin==4.0.4
mkdocs-material==9.1.19
mkdocs-material-extensions==1.1.1
mkdocstrings==0.22.0
mkdocstrings-python==1.2.1
more-itertools==9.1.0
msgpack==1.0.5
mypy==1.4.1
mypy-extensions==1.0.0
nodeenv==1.8.0
packaging==23.1
pathspec==0.11.1
pexpect==4.8.0
pkginfo==1.9.6
pre-commit==3.3.3
ptyprocess==0.7.0
pycodestyle==2.10.0
pydocstyle==6.3.0
pymdown-extensions==10.1
pyparsing==3.0.7
python-dateutil==2.8.2
python-slugify==8.0.1
pywin32-ctypes==0.2.2
PyYAML==6.0.1
pyyaml_env_tag==0.1
rapidfuzz==2.15.1
readme-renderer==40.0
referencing==0.30.0
```

Anyone can help?
