### DISCUSSION TITLE
mermaid is not diagrammed at build

### DISCUSSION THREAD

**Discussion by yosuke-nakamura** [mkdocs/mkdocs#3348] [Q&A]
Hello. - Hello.

When I run `mkdocs build` on a document using mermaid, the mermaid part is not diagrammed.
However, `mkdocs serve` does.

Is there a cause for this?

mkdocs.yaml
```
site_name: TEST
extra:
  generator: false
extra_css:
  - assets/css/style.css
  - assets/css/mkdocs.css

theme:
  name: material
  logo: assets/logo/logo.png
  favicon: assets/logo/favicon.ico
  language: ja

  features:
    - tabs
    - navigation.sections
    - navigation.path
    - content.code.copy
    - navigation.top
    - navigation.instant
    - navigation.prune
    - navigation.footer
  palette:
    primary: deep orange

plugins:

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed
  - admonition
  - pymdownx.details

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

  - pymdownx.smartsymbols
```
