### DISCUSSION TITLE
Breaking styling after a deployment

### DISCUSSION THREAD

**Discussion by Qodestackr** [mkdocs/mkdocs#3375] [Q&A] [answered]
I built a site documentation with this awesome tool. However, after a deployment here:
https://acuvagis.github.io/core-docs/ , the site styling is broken. The local version works though,

The repo: https://github.com/AcuvaGIS/core-docs

Help out, this is a quick issue that am willing to close immediately. Let me know what am doing wrong. Thank you.

**Comment by pawamoy** [comment]
Looks like you're linking your assets using absolute URLs instead of relative ones:

![absoluteassets](https://github.com/mkdocs/mkdocs/assets/3999221/fe4b5b56-c9dd-4544-a34c-76bf59609d9a)

All these should start with `/core-docs/`, but they don't. I'm not sure why, since most of them are not even controlled by you.

**Comment by pawamoy** [comment, marked as answer]
Ah, I think you simply need to fix your site URL:

from

```yaml
site_url: https://acuvagis.com
```

to

```yaml
site_url: https://acuvagis.com/core-docs
# or rather https://acuvagis.github.io/core-docs, not sure about your setup
```

**Reply by Qodestackr** [reply]
Sure, thanks plus adding assets path correctly. `mkdocs` is very smooth. :+1:

**Comment by Qodestackr** [comment]
thank you all for this, and swift responses. It does work now. I have been able to fix. I guess I was just tired, a nap fixed it :smile:

**Comment by Qodestackr** [comment]
This is 404: https://acuvagis.github.io/core-docs/
But where am I getting it wrong?
Unless I type https://acuvagis.github.io/core-docs/home
It will show a 404. Do I need an `index.md` or something? Will figure out.

My current yaml:
```yaml
nav:
  - Home: home.md
  - Getting Started: getting-started.md
  - About:
      - About Us: about/index.md
      - Contributors: about/contributors.md
      - Contributing: contributing/CONTRIBUTING.md
      - Funders: about/funders.md
      - Logos: about/logos.md
  - Contact: contact-us.md
  - Developer Guide: dev-guide/index.md
  - Installations:
      - Install Core Tools: installations/index.md # Mention Tech Stack
      - CKAN Customization: installations/ckan-customization-guide/index.md
      - Frictionless For Portals: installations/frictionless-customization-guide/index.md
      - Monitoring Tools Guide: installations/monitoring/index.md
      - Monitoring with Sentry: installations/monitoring/sentry.md
      - Monitoring with Grafana: installations/monitoring/grafana.md
      - Monitoring with Prometheus: installations/monitoring/prometheus.md
  - Web and Mobile:
      - Web and Mobile GIS: web-mobile-solutions/index.md
      - Web and Mobile Mapping: web-mobile-solutions/web-mapping.md
      - Visualization: web-mobile-solutions/data-viz.md
  - Plugins Development:
      - QGIS: qgis/index.md
      - QGIS Solutions: qgis/qgis-solutions.md
  - Spatial Analysis:
      - Spatial Analysis: analytics/spatial-analysis.md
  - Custom React Tooling:
      - How We Tailor: custom-tooling/index.md
      - Custom React GIS tooling: custom-tooling/react-custom-tooling.md
      - Python Ecosystem: custom-tooling/python.md
      - Cloud and Deployments: custom-tooling/deployments.md
  - ArcGIS:
      - ArcGIS: arcgis/index.md
      - ArcGIS Solutions: arcgis/arcgis-solutions.md
  - Data Portals:
      - CKAN: data-portals/ckan.md
      - Custom Portal Solutions: data-portals/custom-portal-solutions.md
  - Cloud Services:
      - Cloud Development: cloud-services/index.md
      - AWS Experience: cloud-services/cloud-specifics/AWS/aws-intro.md
      - Google Cloud Experience: cloud-services/cloud-specifics/GCP/google-cloud-intro.md
      - Serverless GIS Experience: cloud-services/cloud-specifics/serverless/serverless.md
  - Advanced Techniques:
      - Advanced Techniques: advanced/index.md
#.... More
````
