### DISCUSSION TITLE
Site works on local (mkdocs serve) but not when published on GitHub.

### DISCUSSION THREAD

**Discussion by yaknostoyok** [mkdocs/mkdocs#3432] [Q&A] [answered]
Hi, 
I am sorry because I am pretty sure this is a stupid fuck up but I just can't see it... 
I have this repository: https://github.com/yaknostoyok/mobilitat-manual
I build  the docs on local using mkdocs and it looks just fine:
![imagen](https://github.com/mkdocs/mkdocs/assets/59253112/adfce956-dc6e-405f-8167-8f6c879ac7f3)

I did the mkdocs build and push the changes but the published site just shows the README...
![imagen](https://github.com/mkdocs/mkdocs/assets/59253112/58c31f0a-8b72-4db4-8d0e-95fab94c635e)

I have been trying to figure out what happens but I am just wandering circles... Can anybody please help me? My .yml looks like this:
```
site_name: Manual de Mobilitat
repo_url: https://github.com/yaknostoyok/mobilitat-manual
docs_dir: docs
theme: readthedocs

nav:
  - Inici: index.md
  - Gestió de mobilitat: 
    - Conceptes fonamentals: gestio/gestio-conceptes.md
    - Documents de mobilitat: gestio/gestio-docs.md
  - Referències:
    - Links d'interès: refs/refs-links.md

markdown_extensions:
  - admonition
```

**Comment by Andre601** [comment, marked as answer]
I assume you configured GitHub pages to publish from the docs dir? That's your problem then, because GitHub pulls from the markdown files and by default utilizes jekyll in the bg to render the pages.

If you want the built docs from mkdocs to be published, use `mkdocs gh-deploy` or set up a GitHub Action to build and deploy your stuff.
Using the command, make sure you also configure GitHub pages to target the `gh-pages` branch of your repository that would be created by the command.

**Reply by oprypin** [reply]
Yeah good advice. It's about the configuration of the GitHub repository. You need to publish the gh-pages branch but instead you seem to be publishing the master branch

**Reply by yaknostoyok** [reply]
Thanks a lot!

It was actually what happened... I forgot to mkdocs build so I changed branches and then when made mkdocs things made no sense. 
I read you can change the page to publish to main, isn't that right? 

And if I may, I would like to ask a question about the workflow. Should I:
1. Create my branch derived from main and make my changes.
3. mkdocs build in my branch
3. push my branch and merge it with main
And that would be it? the page will be updated if the page to publish is gh-pages? (Meaning so that changes in gh-pages are maybe derived from main?

**Reply by oprypin** [reply]
> changes in gh-pages are maybe derived from main?

MkDocs doesn't have such a connection. When you run `mkdocs gh-deploy`, it does a build and pushes it to the "gh-pages" branch. It is your task to make sure that you do that only when the main branch is checked out.

GitHub also doesn't have such a connection. It just publishes whatever is on the "gh-pages" branch.

**Reply by Andre601** [reply]
The final page (The one you run using GitHub Pages) is handled on GitHub and from what I recall can you chose these possible options:

- Use content from a specific branch (meaning the entire content of said branch is published)
- Use content from `docs/` folder on a specific branch (Everything in said folder on said branch is used).
- Use GitHub Actions to directly publish to the GitHub Pages environment (This requires to enable `GitHub Actions` as source in the `Pages` settings of your repository)

The `gh-pages` branch is a relict from before GitHub allowed any branch to be chosen, because in the past could you only use `docs/` folder on the default branch or `gh-pages` branch itself, but now there afaik is any combination of these possible (Any branch with or without `docs/` folder).

---

As a personal suggestion would I recommend to use GitHub Actions here and directly build from your main branch and publish to GitHub pages without the need of a separate branch.
It does require some work tho, but should be possible to do easily and can save you time in the future.

Here's a quick setup that should work for you. Tho, it requires the following:

- `Source` in the `Pages` setting of your repository being set to `GitHub Action`
  ![grafik](https://github.com/mkdocs/mkdocs/assets/11576465/ce5668d9-4278-4113-b5fa-25c2f7d1cea9)
- A `requirements.txt` file in the root directory of your repository on the main branch.
  It's used to install any necessary dependencies, namely MkDocs. So at the very least would it contain `mkdocs>=1.5.3`

```yaml
name: Build and deploy

on:
  workflow_dispatch: # Allow manual triggers
  push:
    tags-ignore:
      - '**' # Ignore any tags here
    branches:
      - main
      - master
    #
    # Trigger when either files in the docs folder,
    # the requirements.txt file or the mkdocs.yml file
    # are edited and commited.
    paths:
      - 'docs/**'
      - 'requirements.txt'
      - 'mkdocs.yml'

# These permissions are required for it to work
permissions:
  contents: read
  pages: write
  id-token: wite

# Makes sure only one workflow runs at a time.
concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest
    # This environment is required!
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.pages_url }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Python 3.x
        uses: actions/setup-python@v4
        with:
          python_version: '3.x' # Uses latest 3.x version.
      - name: Install dependencies
        # Alternatively: pip install mkdocs
        run: pip install -r requirements.txt
      - name: Build Docs
        run: mkdocs build
      - name: Configure GitHub Pages
        # I have no idea if this actually needed...
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'site/' # MkDocs builds to site/ by default
      - name: Deploy to GitHub Pages
        id: deployment # This is required for environment
        uses: actions/deploy-pages@v2
```
This action would do the following whenever you push changes to `docs/...`, `requirements.txt` or `mkdocs.yml` on the `main` or `master` branch (Depending on which is your default):

1. Checkout (Clone) your repository
2. Setup python
3. Download dependencies using pip
4. Build the docs with MkDocs
5. Upload the built page content as artifact for github-pages to use
6. Deploy the artifact's content to the GitHub Pages environment (Effectively uploading and updating your site)

I hope this explanation was somewhat understandable 😅 

---

@oprypin I still think a dedicated docs page on how to deploy your docs using GitHub Actions, GitLab Actions, etc. would be useful for people to have. Especially in terms of promoting such stuff...
