### DISCUSSION TITLE
Issue with Immediate Rendering of MathJax Formulas

### DISCUSSION THREAD

**Discussion by mo-anon** [mkdocs/mkdocs#3439] [Q&A] [answered]
I am experiencing an issue with using MathJax for formulas within my documentation.

Problem: When I navigate to a page, the formulas do not render immediately. Instead, the space designated for these formulas remains blank upon the first load. Interestingly, when I refresh the page, the formulas then appear as expected.

Is there a solution available to ensure that the formulas render properly upon the initial page load, eliminating the need for a refresh each time?

**Comment by mo-anon** [comment]
the above happens when using: $$ {whatever} $$.
when using in-line formulas (e.g. $10^{18}$), it just displays "$10^{18}$".

also: this issue does not occur all the time but quite frequently.

**Comment by mo-anon** [comment]
bumping

**Comment by redtide** [comment]
Looks like there is some sort of incompatibility with MathJax in MKDocs' markdown that using directly the javascript causes some quirks. I just noticed that there is a dedicated [plugin](https://squidfunk.github.io/mkdocs-material/reference/math/#mathjax) mentioned in MKDocs Material' docs, so I added it in mkdocs.yml and it fixed the problems I had:

```yml
markdown_extensions:
  pymdownx.arithmatex:
    generic: true
```

**Reply by facelessuser** [reply]
More specifically, unless you actively preserve the MatJax code, the Markdown parser can transform it, breaking MathJax's ability to render it properly. The mention extension actively preserves that content such that it makes it all the way to HTML without getting erroneously treated like Markdown code.

**Reply by redtide** [reply]
> More specifically, unless you actively preserve the MatJax code, the Markdown parser can transform it

This didn't happen, in my case, when using Jekyll and after porting the site to MKDocs wasn't that obvious to me that I needed some markdown plugin/extension to work with MathJax; this because I'm still "new"/not familiar with MKDocs yet and also I'm a bit reluctant towards using plugins in general.

It would be nice to have some "Troubleshoot/FAQ" page in MKDocs user documentation, linked in the menu, that points to some resolutions, like in this case when working with some JS library or missing feature, to point to the plugins page, which has in turn a link to the catalog repo.

**Comment by selfknoww** [comment, marked as answer]
I also encountered this problem, and my solution is as follows.

At first, my config is
```
theme:
  name: 'material'
  features:
    - navigation.tabs 
    - toc.follow
    - navigation.top 
    - navigation.instant 
    - navigation.instant.progress
```
After closing the "instant" feature, I no longer need to refresh the page for the formulas to display correctly.

```
theme:
  name: 'material'
  features:
    - navigation.tabs 
    - toc.follow
    - navigation.top 
    # - navigation.instant 
    # - navigation.instant.progress
```

Here are my other configurations, which are the same as those in the [website](https://squidfunk.github.io/mkdocs-material/reference/math/#mathjax-docsjavascriptsmathjaxjs)
```
markdown_extensions:
  - pymdownx.arithmatex:
        generic: true
```

```
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
```
