### DISCUSSION TITLE
Configuration key conflicts with directory name?

### DISCUSSION THREAD

**Discussion by redtide** [mkdocs/mkdocs#3523] [Q&A]
I've added a `data` key under `extra`' `mkdocs.yml` key:
```yml
extra:
  data:
    layout:
      cards: "data/layout/cards.yml"
      nav:   "data/layout/navigation.yml"
    # ...
```
and I get a `jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'layout'` error.
If I change "data" with something else no problem, so I wonder if it's a name conflict with the actual data directory or I miss some configuration rule.
