### DISCUSSION TITLE
Issues: concat a string in a loop and list append()

### DISCUSSION THREAD

**Discussion by redtide** [mkdocs/mkdocs#3530] [Q&A] [answered]
I have this piece of code that won't work, it seems the `opcode_option_versions` variable is cleaned after the loop. Why?
As in the multi line comment: is it possible to install a jinja extension in MKDocs?

```jinja
{%-set opcode_option_versions = "" %}
{%-if "value" in opcode and "options" in opcode["value"] %}
  {#-
    FIXME: workaround because list.append() seems not working correctly in jinja,
    how to add expression-statement extension to MKDocs? See
    https://jinja.palletsprojects.com/en/2.11.x/templates/#expression-statement
  #}
  {%-for option in opcode["value"]["options"] %}
    {%-if "version" in option and not option["version"] in opcode_option_versions %}
      {%-set opcode_option_versions = opcode_option_versions + ',' + option["version"] %}
      {# {{opcode_option_versions}} here prints ',SFZ v2' in the page (1 loop cycle) #}
    {%-endif %}
  {%-endfor %}
{%-endif %}
{# {{opcode_option_versions}} here prints nothing #}
```
(shrinked) yaml data file converted in dictionary in jinja:
```yml
opcodes:
- name: "trigger"
  value:
    options:
    - name: "attack"
    - name: "release"
    - name: "release_key"
      version: "SFZ v2"
```
