### DISCUSSION TITLE
Nesting multiple navigation levels

### DISCUSSION THREAD

**Discussion by rmscode** [mkdocs/mkdocs#3547] [Q&A] [answered]
I know that this is valid: 

```yaml
- Home: index.md
- Parent:
    - 'Nested Page': 'somepage.md'
    - 'Nested Parent':
        - 'Nested page': `someotherpage.md`
```

But this is not?

```yaml
- Home: index.md
- Parent:
    - 'Nested Page': 'somepage.md'
    - 'Nested Parent':
        - 'Nested page': `someotherpage.md`
        - 'Nested Child':
            - 'Nested Child Page': 'someotherpage2.md'
```

This is what I was trying to do, but received the error `MkDocs encountered an error parsing the configuration file: mapping values are not allowed here`:

```yaml
- Hardware: 
    - hardware/index.md
    - Dell EMC: 
      - hardware/dell-emc/dell-emc.md
        - S4048-ON: # <-- Not allowed here
          - hardware/dell-emc/S4048-ON/overview.md
          - hardware/dell-emc/S4048-ON/os9.md
          - hardware/dell-emc/S4048-ON/os9-debugging.md
          - hardware/dell-emc/S4048-ON/os9-file-management.md
          - hardware/dell-emc/S4048-ON/os9-logging.md
          - hardware/dell-emc/S4048-ON/os9-tty-access.md
          - hardware/dell-emc/S4048-ON/os9-ufd.md
          - hardware/dell-emc/S4048-ON/os9-vlan.md
          - hardware/dell-emc/S4048-ON/os9-vlt.md
          - hardware/dell-emc/S4048-ON/os9-other.md
          - hardware/dell-emc/S4048-ON/os10.md
```

Is anyone aware of a way to achieve what I am looking for?
