### DISCUSSION TITLE
Starting mkdocs in Docker, problem with invalid value for --config-file

### DISCUSSION THREAD

**Discussion by Daksol** [mkdocs/mkdocs#3603] [Q&A] [answered]
Trying to run mkdocs locally as a dev server, using Docker started via a Docker Compose file.
Basically working, but small help needed.

I need to point to a specific mkdocs.yml file which is not in the container root directory (=where the docker-compose.yml file is). The mkdocs.yml file I want to use is part of a cloned documentation repository, so I would prefer not to move that file.

I am presuming that the --config-file paramter does allow you to point to a file in a different directory than the default one. I have tried to do this in the docker-compose file as per below.

The docker-compose file sits in the host file system at ~/docker/mkdocs

So relevant part of docker-compose file looks like this

```
services:
    mkdocs:
          container_name: mkdocs-material
          image: squidfunk/mkdocs-material
          command: serve --dev-addr=0.0.0.0:8005 --config-file=~/docker/mkdocs/lms-community.github.io/mkdocs.yml
          volumes:
            - ~/docker/mkdocs/lms-community.github.io/docs:/docs:rw
          ports:
            - "8005:8005"
```

On startup I get this error
```
Attaching to mkdocs-material
mkdocs-material  | Usage: mkdocs serve [OPTIONS]
mkdocs-material  | Try 'mkdocs serve -h' for help.
mkdocs-material  |
mkdocs-material  | Error: Invalid value for '-f' / '--config-file': '~/docker/mkdocs/lms-community.github.io/mkdocs.yml': No such file or directory
mkdocs-material exited with code 0
```
Things I have tried:

- variants such as enclosing the path in single quotes
- full qualifying the path to the mkdocs.yml file,
- including a space or an equals sign after the '--config-file'

I have verified:
- that the path quoted back in the error message is a valid path to the file.
