### DISCUSSION TITLE
Getting "Unrecognised configuration name" Warning on almost any value

### DISCUSSION THREAD

**Discussion by PinOnAndOffAnOnAgain** [mkdocs/mkdocs#3655] [Q&A] [answered]
After running mkdocs serve
I get this:
WARNING -  Config value 'highlightjs': Unrecognised configuration name: highlightjs
WARNING -  Config value 'custom_dir': Unrecognised configuration name: custom_dir
WARNING -  Config value 'locale': Unrecognised configuration name: locale
INFO    -  Building documentation...
INFO    -  Cleaning site directory
INFO    -  Documentation built in 0.14 seconds
INFO    -  [15:59:49] Watching paths for changes: 'docs', 'mkdocs.yml'
INFO    -  [15:59:49] Serving on http://127.0.0.1:8000/
INFO    -  [15:59:50] Browser connected: http://127.0.0.1:8000/

Almost any configuration name gives the same warning. Also some themes doesn't work (no config file found).

mkdocs.yml :

```yaml
site_name: Bunte Fussballtraeume Leipzig
theme: risonia
highlightjs: true
custom_dir: settings/
locale: de
nav:
  - Home: index.md
  - Schritt 1: 1.md
  - Schritt 2: 2.md
  - Schritt 3: 3.md
  - About: about.md
```

I installed mkdocs via pip on osx 10.14.6., Python 2.7.16

Any idea how to solve that?

**Comment by pawamoy** [comment, marked as answer]
If the YAML config you pasted is exactly what you have in mkdocs.yml, here's how to fix it:

```yaml
site_name: Bunte Fussballtraeume Leipzig
theme:
  name: risonia
  highlightjs: true
  custom_dir: settings/
  locale: de
nav:
  - Home: index.md
  - Schritt 1: 1.md
  - Schritt 2: 2.md
  - Schritt 3: 3.md
  - About: about.md
```

(not entirely sure about where to put `highlightjs`)

**Reply by PinOnAndOffAnOnAgain** [reply]
Thank you for the quick reply. Just c+p your mkdocs.yml and now getting this:

Error: MkDocs encountered an error parsing the configuration file: mapping values are not allowed here
  in "/Users/armi/bft/mkdocs.yml", line 3, column 14

also tried removed the highlightsjs:  true line, but getting the same Error

**Reply by pawamoy** [reply]
Right, sorry, try this:

```yaml
theme:
  name: risonia
  highlightjs: true
  custom_dir: settings/
  locale: de
```
