### DISCUSSION TITLE
dynamic loop through extra.foo

### DISCUSSION THREAD

**Discussion by agardnerIT** [mkdocs/mkdocs#3805] [Q&A] [answered]
Hi all, Asssume `page.title == pageOne`.

This is `extra` block:

```
plugins:
    - search
    - markdownextradata
extra:
  progressbar:
    pageOne:
      - item1
      - item 2
```

Is something like this possible?

```
{% block footer %}
{% if extra and extra.progressbar and extra.progressbar['page.title'] %}
{% for item in extra.progressbar['page.title'] %}
{{ item }}
{% endfor %}
{% endif%}
{% endblock %}
```
