### DISCUSSION TITLE
Does mkdocs.yaml allow for substitutuon and concatenation at all?

### DISCUSSION THREAD

**Discussion by isuftin** [mkdocs/mkdocs#3829] [Q&A] [answered]
What I'd like:

```yaml
---
edit_uri: {my_vcs}/-/ide/project/something/another_something/something_else/edit/development/-/
repo_url: {my_vcs}/something/another_something/something_else
site_url: {my_vcs}/something/something_else
extra:
  my_vcs: !ENV CI_PROJECT_URL
```

Is this possible in any way?
