### DISCUSSION TITLE
index.html in subfolders do not open automatically

### DISCUSSION THREAD

**Discussion by buhtz** [mkdocs/mkdocs#3847] [Q&A] [answered]
I am confused. In this screencast you see in the beginning that I try to open sub pages in my local generated doc (generated via `mkdocs build`). Each section is a subfolder containing its own index.html file. But my browser (latest Debian stable) Firefox doe not open that file by default when clicking on the left menu.

But when I use the docu via `mkdocs serve` it behave well and as expected.

![Peek 2024-10-10 14-53](https://github.com/user-attachments/assets/8a8c94f7-d0b4-4290-97d1-6a9c64ffe324)

I am confused.

This are my content files:
```
src
├── additional.md
├── _images
│   ├── *
├── index.md
├── log.md
├── main-window.md
├── quick-start.md
├── settings.md
├── snapshots-dialog.md
└── user-callback.md
```

This is my `mkdocs.yaml`

```
# SPDX-FileCopyrightText: © 2024 Kosta Vukicevic (stcksmsh)
# SPDX-FileCopyrightText: © 2024 Christian Buhtz <c.buhtz@posteo.jp>
#
# SPDX-License-Identifier: CC0-1.0
#
# This file is released under Creative Commons Zero 1.0 (CC0-1.0) and part of
# the program "Back In Time". The program as a whole is released under GNU
# General Public License v2 or any later version (GPL-2.0-or-later).
# See file/folder LICENSE or
# go to <https://spdx.org/licenses/CC0-1.0.html>
# and <https://spdx.org/licenses/GPL-2.0-or-later.html>.

# Project information
site_name: Back In Time - User Manual
site_author: Back In Time Team

# Source files (markdown)
docs_dir: src

# Output directory
site_dir: html

# site_url: https://backintime-docs.readthedocs.io/en/latest/
# site_description: Back In Time is a simple backup tool for Linux inspired by "FlyBack".

# Repository information
repo_name: backintime
# repo_url: https://github.com/bit-team/backintime

# Entrie labels determined by the the 1st level heading
nav: 
  - 'index.md'
  - 'quick-start.md'
  - 'main-window.md'
  - 'settings.md'
  - 'snapshots-dialog.md'
  - 'log.md'
  - 'user-callback.md'
  - 'additional.md'

markdown_extensions:
  # Boxex for warnings, etc.
  # https://squidfunk.github.io/mkdocs-material/reference/admonitions/
  - admonition
  - toc:
      permalink: true  
  - footnotes
  # Syntax highlightening in code blocks
  # - pymdownx.highlight:
  #     linenums: true
  #     # clickable and referencable lines numbers
  #     anchor_linenums: true
  #     # Highlight (and reference) a bunch of lines
  #     line_spans: __span
  #     # Somehow ease up CSS stuff
  #     pygments_lang_class: true

# Configuration
theme:
    name: material
    logo: _images/logo48.png
    favicon: _images/logo48.png
    language: en
    features:
      # Load content of main page only instead of the whole site
      - navigation.instant
      # Loading in background while hovering over the navigation item
      - navigation.instant.prefetch
      # Unfold all entries in navigation side bar
      - navigation.expand
      # Render navigation path on above the title of each page
      - navigation.path
      # Back-to-top-button
      - navigation.top
      # Render sub-headings in navigation side bar
      - toc.integrate
      - toc.follow
      # Highlight search results
      - search.highlight
      # Link current document to GitHub
      - content.action.edit
      - content.action.view
      # Copy and highlight code blocks
      - content.code.copy
      - content.code.select
    # Colorsettings regarding dark/light mode
    palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: grey
      accent: blue
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
```
