### DISCUSSION TITLE
Deployed Documentation not showing properly because images, css, js and co missing

### DISCUSSION THREAD

**Discussion by Wolf2323** [mkdocs/mkdocs#3883] [Q&A] [answered]
My deployed page does not show properly https://docs.betonquest.com/betonquestplus/. If you look up in the browser console, it shows a lot of `Failed to load resource: the server responded with a status of 404`.

# Setup
First I show you my setup.
I have this repository, where all the basic setup is located in, this setup gets copied into my actual repositories, where I write all the documentation: https://github.com/BetonQuest/CommonProjectFiles/tree/main/docs

## Working setup
I already use this setup in the following repository, where everything just works fine: https://github.com/BetonQuest/BetonQuest and the documentation can be seen here: https://betonquest.org. The main difference is that i use mike to deploy it.

## Not Working
Now Its getting a but more complicated to share everything, as the actual repository is private. But right now I only have a basic setup, so here is my mkdocs.yml:

```yaml
INHERIT: ./docs/mkdocs_parent.yml
site_name: BetonQuestPlus
site_author: BetonQuest Commercial
site_url: https://docs.betonquest.com/betonquestplus/
copyright: >
  <p id="bqCopyright">© 2024-{CurrentYear} BetonQuest Commercial.</p>
  <a href="#__consent">Change cookie settings</a>
edit_uri: ''

extra:
  social:
    - icon: brands/discord
      link: https://discord.gg/rK6mfHq
    - icon: brands/mail
      link: mailto://contact@betonquest.com

#Notice that here are a few strange looking hairspaces in here.
#They make the space between the emojis and the text look equal
nav:
  - 'Home': index.md
  - 'Documentation':
      - 'Changelog': Documentation/CHANGELOG.md
```

Now as this is a private repository, I decided to deploy the pages to a public repository. For that I created a new Repository called https://github.com/BetonQuest/BetonQuestCommercial and the domain is https://docs.betonquest.com/ and I deployed the documentation of BetonQuestPlus in a subdirectory so the url is https://docs.betonquest.com/betonquestplus/.

I deploy this with GitHub actions by running:
```yaml
      - name: Build with mkdocs
        shell: bash --noprofile --norc -euo pipefail {0}
        run: |
          mkdocs build --strict
      - name: Checkout pages repository
        uses: actions/checkout@v4
        with:
          repository: BetonQuest/BetonQuestCommercial
          path: 'gh-pages'
          token: ${{ secrets.ALL_REPOSITORIES_ACCESS_TOKEN }}
      - name: Copy docs to pages repository
        if: "env.VERSION_TYPE == 'release' || env.VERSION_TYPE == 'development'"
        shell: bash --noprofile --norc -euo pipefail {0}
        run: |
          rsync -av --delete ./target/docs/ ./gh-pages/betonquestplus
      - name: Commit and push pages repository
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Deployed docs for version ${{ env.VERSION }}"
          repository: gh-pages
```

# My guess

As I deployed it to a sub directory, may the relative links to the resources do not work anymore. But I thought exactly for this the option `site_url: https://docs.betonquest.com/betonquestplus/` is for. Also by looking up the page code and compare it to my working BetonQuest Pages, I could not find the reason for this.

# Additional thoughts

Is GitHub pages not like I can access all resources on the page with a direct path to it? So In the BetonQuest pages, I can access the icon with the url
https://betonquest.org/DEV/_media/brand/Icon/Icon32.ico
but in BetonQuestPlus it is not possible to access it:
https://docs.betonquest.com/betonquestplus/_media/brand/Icon/Icon32.ico

**Comment by pawamoy** [comment]
Quick guess: shouldn't you `rsync -av --delete ./target/docs/ ./gh-pages/` instead?

- Here's your "gh-pages" branch (actually main in a different repo): https://github.com/BetonQuest/BetonQuestCommercial.
- Here's my gh-pages branch (actual gh-pages branch here, but it makes no difference to GitHub Pages as long as configured properly): https://github.com/mkdocstrings/griffe/tree/gh-pages.

Both our docs are served under `domain/something` (https://docs.betonquest.com/betonquestplus/ for you, https://mkdocstrings.github.io/griffe/ for me), but in your case the files are in a subfolder, and in my case they are in the root.

**Reply by Wolf2323** [reply]
The actual goal is to have them in a sub folder, so I can deploy other projects under other sub folders.

**Reply by pawamoy** [reply]
I see. Well I'm not sure if this is supported by GitHub pages / MkDocs :confused:

**Reply by Andre601** [reply]
I think you can?
Haven't followed the entire chat but using GitHub actions can you directly deploy to pages.

**Reply by pawamoy** [reply]
> Haven't followed the entire chat but using GitHub actions can you directly deploy to pages.

Sure, the question is whether you can, from a single Pages instance / repository, deploy multiple subfolders. To me, these subfolders should be built as part of the main site, and deployed as such, not from a distinct repository / pages setup.

To illustrate:

- I deploy https://example.com from repo A
- I deploy https://example.com/subsite1 from repo B
- But I cannot deploy https://example.com/subsite2 from repo B as well, because that means I have sub-site files in actual subfolders in repo B, while GitHub Pages expects files to be in the root of the repository and configured branch. Or simply because one repo = one subsite in GitHub Pages.

Well, that's only a guess. Maybe repo B is just missing some files in the root to make this possible.

**Reply by Andre601** [reply]
Your example assumes the stanard "deploy from branch (and folder)" setup, when I explicitly mentioned deploying directly.

Using deployment from a branch is honestly dated and a direct deploy should be preferred here.

For example do I have this setup for one of my pages:
```yaml
name: Deploy Site

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/publish_site.yml
      - .snippets/**
      - docs/**
      - mkdocs.yml
      - requirements.txt

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: github-pages
  cancel-in-progress: false

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Checkout Repositoryy
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Python 3
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python -m pip install -U pip setuptools
          python -m pip install -r requirements.txt
      - name: Build Site
        run: mkdocs build
      - name: Configure Pages
        uses: actions/configure-pages@v5
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site/
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deploy
```
The main benefit of this would be, that you can directly deploy from any branch and any folder really, but issue is, you need to explicitly configure a (sub)domain in the pages setting as any cname file is ignored.

I'm sure there is a possible way to achieve what they want here. Like maybe have different target paths set for the build directory.
In general do I feel like their setup to be kinda... overcomplicated?
