### DISCUSSION TITLE
Integrating already made html files into a mkdocs site

### DISCUSSION THREAD

**Discussion by jasonnicholson** [mkdocs/mkdocs#3944] [Q&A] [answered]
I auto generate a bunch of html files from code. I want to integrate these html files into an mkdocs site. I can get the links working but the pages do not integrate into lunr. I know that either I need to communicate to mkdocs to include the html files in the search index or I need regenerate the search index. I have tried for about 36 hours at this point and am stuck. I have successfully generated an index but my index breaks the search functionality. What do you recommend?

- docs
  - html
    - a.html
    - b.html
    - c.html
  - index.md

### mkdocs.yml
```yml
site_name: My Docs
theme: readthedocs
plugins:
  - search
  - update_search_index
nav:
  - Home: index.md
  - Functions/Scripts:
    - a: html/a.html
    - b: html/b.html
    - c: html/c.html
  ```
