### ISSUE TITLE
Question: How to Access Nested Extra Variables in Theme

### ISSUE THREAD

**Issue by michaeltlombardi** [mkdocs/mkdocs#1002]
### Intent
I'm adding a built-in capacity for my orgs theme to include links to related documentation sites - essentially an additional nav item for submodules or related infrastructure or whatever.

```
.Modules
|
+--[SubModule1](https://link/to/submodule1)
|
+--[SubModule2](https://link/to/submodule2)
|
+--[etc]()
```

### Configuration
```yaml
extra:
    linked_docs:
        - submodule1:
            - name: "submodule1"
            - url:      "https://link/to/submodule1"
```

### Implementation
```html
{% if config.extra.linked_docs %}
{% for docsite in config.extra.linked_docs %}
<li>
    <a href="{{ docsite.url }}">{{ docsite.name }}</a>
</li>
{% endfor %}
```

**Note:** I'm aware this won't nest but I can't get it to work as is when trying to display just one link.

### Result
Nothing displays for where I'd expect that nav item to pop up, no other weirdness either. Just flat fails.

I'm reasonably sure I'm doing something wrong.

**Comment by waylan** [comment]
Your config:

```yaml
extra:
    linked_docs:
        - submodule1:
            - name: "submodule1"
            - url:      "https://link/to/submodule1"
```

would translate into the following Python objects:

```python
{
    'extra': {
        'linked_docs': [
            {
                'submodule1': [
                    {'name': 'submodule1'},
                    {'url': 'https://link/to/submodule1'}
                ]
            }
        ]
    }
}
```

You have two dicts nested in a list, nested in a dict, nested in a list, nested in a dict, nested in a dict.  Your template would need to be (untested):

```django
{% if config.extra.linked_docs %}
{% for docsite in config.extra.linked_docs %}
<li>
    <a href="{{ docsite.submodule1[1].url }}">{{ docsite.submodule1[0].name }}</a>
</li>
{% endfor %}
```

Note that each attribute of `submodule1` is in a separate dict as each item is a list item (starts with `-`). Therefore, you need to reference each by index and the dict key is redundant. Also as `linked_docs` is a list, the `docsite` variable in the template is the dict object. You still need to look inside its key to get to the children objects.

If you refactor your config and remove the lists, you should have a much simpler structure:

```yaml
extra:
    linked_docs:
        submodule1: "https://link/to/submodule1"
```

Then your template would be (again, untested):

```django
{% if config.extra.linked_docs %}
{% for name, url in config.extra.linked_docs.items %}
<li>
    <a href="{{ url }}">{{ name }}</a>
</li>
{% endfor %}
```

Note that `linked_docs.items()` will return a key/value tuple, which you can assign to the variables `name` and `url`. The actual values to not need to be named in the config.

**Comment by michaeltlombardi** [comment]
@waylan Thanks for the detailed answer and elucidation! I'll test this tomorrow as soon as I get back into the office.

Vastly prefer the refactored layout.

**Comment by michaeltlombardi** [comment]
Hmm, I seem unable to access dicts under `linked_docs`.

## Config
```yaml
extra:
    linked_docs:
        somedoc: "doc.domain.com"
```

## Template Attempts
```html
{% if config.extra.linked_docs %}
    {% for object in config.extra.linked_docs %}
        <li>
            <a href="#">{{ object }}</a>
        </li>
    {% endfor %}
{% endif %}
```

**Output:** `{'SomeDoc': 'doc.domain.com'}`

I've tried accessing the objects in config.extra.linked_docs via `.key`, `.value`, `.children`, `.item` and always end up with null output.  Outputting just `Object` seems to give me the full object with depths to it. Trying to access deeper levels doesn't appear to work properly either:

```html
{% if config.extra.linked_docs %}
                    {% for object in config.extra.linked_docs %}
                    {% for title in object %}
                        <li>
                            <a href="{{ object.SomeDoc }}">{{ title }}</a>
                        </li>
                    {% endfor %}
                    {% endfor %}
                {% endif %}
```

**Output:** SomeDoc

Trying to set the url as something like `{{ object.{{ title }} }}` doesn't parse, so that was a no go. I found it interesting that the value of `title` was the actual title - if I can get the url parsed from here I should be 75% of the way to completion.

Other things I tried:

```html
{% if config.extra.linked_docs %}
    {% for object in config.extra.linked_docs %}
        <li>
            <a href="#">{{ object.SomeDoc }}</a>
        </li>
    {% endfor %}
{% endif %}

{% if config.extra.linked_docs.items %}
    {% for title, url in config.extra.linked_docs.items %}
        <li>
            <a href="{{ url }}">{{ title }}</a>
        </li>
    {% endfor %}
{% endif %}
```

I've only been able to successfully grab the url by specifying `object.SomeDoc` so far.

**Comment by waylan** [comment]
Try this (add the parens after `items`):

```django
{% if config.extra.linked_docs.items %}
    {% for title, url in config.extra.linked_docs.items() %}
        <li>
            <a href="{{ url }}">{{ title }}</a>
        </li>
    {% endfor %}
{% endif %}
```

Sorry, I forget  some of the subtle differences between Jinja and Django. In Jinja you have to use full Python expressions. It doesn't assume you want to call a callable unless you explicitly call it.

**Comment by waylan** [comment]
Oh and you'll want your config to include the full URL:

```yaml
extra:
    linked_docs:
        somedoc: "http://doc.domain.com"
```

**Comment by michaeltlombardi** [comment]
I'll try using `items()` in the morning, but I seem to have frankenstein'd the template together at this point with the following:

```html
{% if config.extra.linked_docs %}
{% for doctype in config.extra.linked_docs %}
{% for doctype,documents in doctype|dictsort %}
    <li class="dropdown{% if doctype.active %} active{% endif %}">

        <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{ doctype }} <b class="caret"></b></a>
        <ul class="dropdown-menu">
        {% for document in documents %}
        {% for title,url in document|dictsort %}
            <li {% if document.active %}class="active"{% endif %}>
                <a href="{{ url }}">{{ title }}</a>
            </li>
        {% endfor %}    
        {% endfor %}
        </ul>
    </li>
{% endfor %}
{% endfor %}
{% endif %}
```

Ugly, but it seems to have done what I was trying to do. Will see if `items()` lets me clean it up. Discovered the full URL issue once I got to the point from my previous post, good catch.

**Comment by michaeltlombardi** [comment]
I was able to get things to work (except for the `document.active` setting) using `.item()` but I had to fix my config:

```yaml
extra:
    linked_docs:
        doctype1:
            somedoc: "doc.domain.com"
            anotherdoc: "doc2.domain.com"
        doctype2:
            somedoc: "dok.domain.com"
            anotherdoc: "dok2.domain.com"
```

I had been erroneously including everything as a list item, similar to how `pages` are laid out in the config. The variables were being seen as lists instead of having items, causing me some of the problems from the start of this post.
