### ISSUE TITLE
Second level sidebar css

### ISSUE THREAD

**Issue by memeplex** [mkdocs/mkdocs#1024]
The base.css file for mkdocs theme contains:

``` css

/* Nav: second level (shown on .active) */
.bs-sidebar .nav .nav {
    display: none; /* Hide by default, but at >768px, show it */
    margin-bottom: 8px;
}
.bs-sidebar .nav .nav > li > a {
    padding-top:    3px;
    padding-bottom: 3px;
    padding-left: 30px;
    font-size: 90%;
}
```

But I'm failing to see how this is used in [toc.html](https://github.com/mkdocs/mkdocs/blob/master/mkdocs/themes/mkdocs/toc.html).

Is this css fragment a residual of a previous version?
