### ISSUE TITLE
Impossible to generate "no-http-server" version (unpretty urls)

### ISSUE THREAD

**Issue by castarco** [mkdocs/mkdocs#1110]
Hi,

I think that the `mkdocs` command should have an option to generate "complete" (but not absolute) paths, without the assumption of a HTTP server behind the scene.

I'll be more concrete. Imagine the following `mkdocs.yml` file:

```yml
site_name: The guide
pages:
    - Home: index.md
    - HowTo: howto/index.md
    - Troubleshooting: troubleshooting/index.md
    - Programs: programs/index.md
```

Then, the generated paths are `/`, `howto/`, `troubleshooting/`, and `programs/` . The problem is that, if I'm generating "offline" documentation, to be opened from the file system, the browser won't infer that must load the `index.html` file placed inside the specified directory.

I understand the need of "pretty urls", but I think that an option to disable pretty urls is needed.
