### ISSUE TITLE
3rd level navigation tree

### ISSUE THREAD

**Issue by happicamper** [mkdocs/mkdocs#1140]
Does this project support 3rd level navigation? I can only use the second level on .yaml file. Thank you for your response.

**Comment by waylan** [comment]
Yes, MkDocs should support as many levels as you want. However, not all themes do. What problem are you encountering?

**Comment by happicamper** [comment]
Can you give me a format for mkdocs.yml with a lot of in-depth navigation tree while using a certain theme. I'm currently using material theme. Thank you very much for your fast response.

**Comment by waylan** [comment]
For the format see the discussion about this we just had earlier today in #1139. However, when I say not all themes support more than two levels what I mean is that the theme needs to be altered (the template code needs refactored) to make it work with more than two levels. Up until recently MkDocs only supported two levels. While we now support any number of levels, not all themes have been updated. You need to address that with the theme author.

To determine whether the problem lies with the theme or your mkdocs.yml format, I would suggest temporarily switching to the `mkdocs` theme which is known to support many levels. Get your multilevel nav working there, and then switch back to your theme of choice. If it doesn't work, then you know it is a problem with the theme and not with MkDocs.

**Comment by happicamper** [comment]
Oh, thank you for your answers! it really helped me understand the format. The only problem that I'm facing now is that is it required to put:
```
- Home: index.md
- Parent:                                               < this empty navigation
    - 'Nested Page': 'somepage.md'
    - 'Nested Parent':                             < this empty navigation 
        - 'Nested nested page': `someotherpage.md`
```
those empty navigation links before a navigation that has a content of markdown.md? thank you so much for your time.

**Comment by waylan** [comment]
Yes you understand. However, the "parents" are not really "empty". They contain the "nested" list. As a reminder, YAML is a subset of JSON. So let's define that in JSON:

```jSON
[
    {'Home': 'index.md'},
    {'Parent':
        [
            {'Nested Page': 'somepage.md'},
            {'Nested Parent':
                [{'Nested nested page': 'someotherpage'}]
            }
        ]
    }
]
```

Notice that `'Nested Parent`' has a child: `[{'Nested nested page': 'someotherpage'}]`, which expressed in  YAML is `- 'Nested nested page': 'someotherpage.md'`.

As you can see, there is no way to define a URL for the parents. It is not possible in the JSON, which means it also is not possible in YAML. This was part of the discussion in #73. In an attempt to resolve that issue, I experimented with a workaround #1042, but I'm not convinced it's a good idea. Personally, I'm okay with this limitation.

**Comment by happicamper** [comment]
Oh, thank you very much for the explanation relating it to JSON it makes sense to me now. I tried to create a navigation tree with the format earlier #1139  and now I can use 3 level navigation but when attempting for the fourth it doesn't apply.  Still using theme "material". Hey, buddy thank you again I'm gonna close this issue because the 3rd level navigation is satisfied.

**Comment by happicamper** [comment]
Also by trying few times where should i put the next entry of navigation now it works! It looks like this:
```
- Nav:
    - 'Nav': 'readme.md'
    - Nav:
        - 'Nav': 'readme.md'
        - Nav:
            - 'Nav': 'readme.md'
            - 'Nav': 'readme.md'
            - Nav:
                - Nav': 'readme.md'
                - Nav': 'readme.md'
                - Nav:
                    - 'Nav': 'readme.md'
                    - 'Nav': 'readme.md'
                    - Nav:
                        - 'Nav': 'readme.md'
                        - 'Nav': 'readme.md'
```
Cheers @waylan for your help! 👍
