### ISSUE TITLE
[question] how to disable syntax highlighting for a code block?

### ISSUE THREAD

**Issue by ketzacoatl** [mkdocs/mkdocs#1144]
Using code block fences to display an asciiart diagram, mkdocs provides syntax highlighting to the block and the asciiart diagram looks funny. Is there a way to disable syntax highlighting for a specific code block, or is there a better way to include the diagram in monospace so it's displayed correctly?

**Comment by d0ugal** [comment]
It can depend on the theme, because themes add their own highlighting, but this will work for any that use highlight.js

    ```text
    wont be highlighted
    ```

**Comment by ketzacoatl** [comment]
TY!

**Comment by Gwend4l** [comment]
Hi! Sorry to answer on this old issue, but the ` ```text ` syntax does not work for me, and keywords are still highlighted. Any advice?

**Comment by waylan** [comment]
According to the [docs][1], `nohighlight` disables highlighting for a code block:

    ```nohighlight
    some content here
    ```

[1]: https://highlightjs.org/usage/

**Comment by oprypin** [comment]
This is way too intrusive for a default behavior.

I ended up using the "codehilite" extension, it **just works**. One of the two options, I'm not sure which one I'll go for, yet:

* ```yaml
  theme:
    name: material
  markdown_extensions:
    - codehilite:
        guess_lang: False
  ```
  
  (this theme includes Pygments styles by default, others don't)

* ```yaml
  theme:
    name: readthedocs
    highlightjs: false
  markdown_extensions:
    - codehilite:
        guess_lang: False
        noclasses: True
  ```

  (default themes include non-configurable highlightjs by default...... thanks?)
  
  Or, rather than "noclasses", use CSS like [in this comment](https://github.com/mkdocs/mkdocs/issues/1019#issuecomment-238671470). Or link it by URL [from a CDN](https://www.google.com/search?q=pygments+css+cdn)
