### ISSUE TITLE
Separators (Groups?) as Pages

### ISSUE THREAD

**Issue by omento** [mkdocs/mkdocs#1187]
I apologize in advance if this is not the place for this, but I'm looking for clarification on setting up custom page configurations. What I'm looking for right now is the ability to use separators as pages. For example, the configuration I'm using right now is:

```YAML
pages:
  - Welcome to Redshift: index.md
  - Getting Started:
    - System Requirements: getting-started/system-requirements.md
    - Installation:
      - Installation Information: getting-started/installation.md
      - Installing on Windows: getting-started/installation/windows-installation.md
      - Installing on Linux: getting-started/installation/linux-installation.md
    - Licensing:
      - Licensing Information: getting-started/licensing.md
      - Node Locked Licenses: getting-started/licensing/node-locked.md
      - Floating Licenses: getting-started/licensing/floating.md
    - Additional Configuration: getting-started/additional-configuration.md
```

If I were to remove 'Licensing Information' and place it's link into the parent object of 'Licensing', the build would fail with an error like so:

```
ParserError: while parsing a block mapping
      in "C:\Users\mjr14019\Documents\redshift-docs\mkdocs.yml", line 19, column 5
    expected <block end>, but found '-'
      in "C:\Users\mjr14019\Documents\redshift-docs\mkdocs.yml", line 20, column 5
```

I take it this is a current limitation of the pre-1.0 release? Being able to do this would help clear up clutter a bit and reduce duplicate naming in the navigation.
