### ISSUE TITLE
Embed images

### ISSUE THREAD

**Issue by zzart** [mkdocs/mkdocs#138]
According to the docs 

```
mkdocs.yml
docs/
    CNAME
    index.md
    subpage.md
    img/
        screenshot.png
```

```
index.md
![Screenshot](img/screenshot.png)
```

This is all good if you adding images to index.md

Now let's consider subpage: 

```
subpage.md
![Screenshot](img/screenshot.png)
```

This image isn't found as server wants it to be in subpage/img/screenshot.png ?? 
So this forces invalid markup which doesn't work with other MD engines! 

```
subpage.md
![Screenshot](../img/screenshot.png)
```

**Comment by gipi** [comment]
Sorry if I comment on this closed issue, but this situation with nested pages and images is not working with mkdocs 1.1.2 and I cannot find useful info in the documentation; in my case I have

```yaml
nav:
- Home: index.md
- Computer:
  - Hardware: hw.md
  - Embedded Systems:
    - General: embedded/index.md
    - Microcontrollers: embedded/micro.md
```

where inside ``embedded/micro.md`` there is an image with path ``images/STM32-pinout.png`` but it's not rendered since the final path is not adapted to match the layout of the repo, indeed the ``mkdocs serve`` complains with

``WARNING -  Documentation file 'embedded/micro.md' contains a link to 'embedded/images/STM32-pinout.png' which is not found in the documentation files.``.
