### ISSUE TITLE
TypeError: unhashable type: 'dict' when configuring theme

### ISSUE THREAD

**Issue by kbherbert** [mkdocs/mkdocs#1439]
## Description

Opening this issue, per @squidfunk. See [comments from mkdocs-material #737](https://github.com/squidfunk/mkdocs-material/issues/737). 

When attempting to configure the theme according to the documentation, I am receiving the following error after running `python -m mkdocs build`:

```
2018-03-14T18:35:17.0547488Z   File "C:\Users\tfsbuild\AppData\Roaming\Python\Python36\site-packages\mkdocs\config\config_options.py", line 326, in run_validation
2018-03-14T18:35:17.0547488Z     if value in themes:
2018-03-14T18:35:17.0703709Z TypeError: unhashable type: 'dict'
2018-03-14T18:35:17.1172494Z ##[error]Process completed with exit code 1.
```

See below for `.yml` configuration.

### Expected behavior

There should be no errors, and the theme should accept the options.

### Actual behavior

See above error.

### Steps to reproduce the bug

1. Add the settings to the `.yml` file
2. Run `python -m mkdocs build`

### Package versions

* Python: 3.6.3
* MkDocs: 0.17.1  (**edited**)
* Material: 2.7.0

### Project configuration

``` yaml
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

markdown_extensions:
  - codehilite

pages:
- Home: 'index.md'
```

However, if I simply change to the following, the build works fine every time:

``` yaml
theme: 'material'

markdown_extensions:
  - codehilite

pages:
- Home: 'index.md'
```

### System information

* OS: Windows
