### ISSUE TITLE
generated sitemap.xml does not include links with depth > 2 from mkdocs.yml - 0.17.3.

### ISSUE THREAD

**Issue by wmartindale408** [mkdocs/mkdocs#1481]
I am using mkdocs 0.17.3.
I don't see that the generated sitemap.xml includes links that have a depth > 2. For example below, the pages/links under **Python** and **Ruby** are not included (but index.md is).

```
- Home: index.md
- Technology: 
  - Python:
    - Installation: tech/python/install.md
    - Tutorial: tech/python/tutorial.md
  - Ruby:
    - Installation: tech/ruby/install.md
    - Tutorial: tech/ruby/tutorial.md
```
