### ISSUE TITLE
invalid blockquote font size 

### ISSUE THREAD

**Issue by ghorwin** [mkdocs/mkdocs#1509]
Current mkdocs (0.17.3) generates invalid blockquote font sizes for several styles, including the built-in mkdocs style (see link below). The problem appears when "serving" the webpage locally and in the deployed site.

Example: see blockquote at bottom of page, and blockquotes on other pages.

http://bauklimatik-dresden.de/postproc/2/export/

The css contains the line
```css
     blockquote p{font-size:17.5px;font-weight:300;line-height:1.25}
```
which is responsible for the large blockquote text.

Is this a general issue that should be fixed in next release? What is a meaningful workaround?
