### ISSUE TITLE
Navigation not working on Microsoft SharePoint

### ISSUE THREAD

**Issue by Cuurjol** [mkdocs/mkdocs#1573]
Hello.

I faced the problem about working navigation-links in my project-documentation. I created my project-documentation and published all the content into Microsoft SharePoint platform. Url web-site where I published all the content: http://ilyin1/DocLib/

mkdocs.yml:
```
site_name: ИНСТРУКЦИЯ ПО СЭД ДЛЯ ТЕХНОЛОГОВ
theme: 
    name: rtd-dropdown
    custom_dir: custom_theme
extra_css: [extra.css]
use_directory_urls: false
pages:
    - Введение: index.md
    - Создание и заполнение справочников: directory.md
    - Создание сайтов картотек: cardIndexSites.md
    - Создание типов контента: contentType.md
    - Создание групп документов: documentGroups.md
    - Настройка сайтов картотек: settingUpCardIndexSites.md
    - Настройка процессов: processConfiguration.md
    - Создание рабочих мест: workplace.md
    - Настройка профиля: profileSetup.md
    - Настройка доступа: accessSetup.md
```

index.md:
```
## Порядок настройки системы:

1. [Создание и заполнение справочников](directory.md).
2. [Создание сайтов картотек](cardIndexSites.md)
3. [Создание типов контента](contentType.md) (карточек документов/проектов).
4. [Создание групп документов](documentGroups.md).
5. [Настройка сайтов картотек](settingUpCardIndexSites.md).
6. [Настройка процессов](processConfiguration.md).
7. [Создание рабочих мест](workplace.md).
8. [Настройка профиля](profileSetup.md): категории задач, персональные оповещения, типовые формулировки, шаблоны заполнения форм, управление замещением.
9. [Настройка доступа](accessSetup2.md).
```

I noticed that two files (mkdocs.yml and index.md) form links differently. For example:

1. mkdocs.yml -> `Создание и заполнение справочников: directory.md` -> `http://ilyin1/directory/index.html`
2. index.md -> `[Создание и заполнение справочников](directory.md)` -> `http://ilyin1/DocLib/directory/index.html`

Whether it is possible somehow in a file `mkdocs.yml` to make so that links for navigation were formed not so `http://ilyin1/directory/index.html`, and so `http://ilyin1/DocLib/directory/index.html`?

A similar situation occurs when I try to work with my project-documentation offline in File System. In the navigation I get links of this kind:

mkdocs.yml:
```
file:///index.html
file:///directory/index.html
etc
```

index.md:
```
file:///C:/Python/my-project/site/index.html
file:///C:/Python/my-project/site/directory/index.html
etc
```

I apologize in advance if this is somewhere written in the documentation, and I did not notice it.
