### ISSUE TITLE
Navbar link to homepage doesn't exist

### ISSUE THREAD

**Issue by pkomiske** [mkdocs/mkdocs#1575]
I'm running mkdocs 1.0 on python3.6 with a simple nav structure, partly shown below:

```yaml
nav:
  - Home: index.md
  - Getting Started:
    - Installation: installation.md
    - Tutorial: tutorial.md
    - FAQ: faq.md
```

The issue is that there is no link associated with Home when the website is rendered. It acts like a section heading like Getting Started which is text only. I did not previously have this issue with earlier versions of mkdocs. I'm using the readthedocs theme with a tiny bit of customized CSS (but the custom CSS has not changed from previously when I did not have this issue).
