### ISSUE TITLE
Build targets link incorrectly to base path compared to Serve

### ISSUE THREAD

**Issue by martinbira** [mkdocs/mkdocs#1579]
After the 1.0 upgrade all my links used as references broke when using `mkdocs build`. I've performed tests with the Default theme, ReadTheDocs theme and Material theme to rule out theme specific issues.

All my links used in .md-files are defined in the form of `[link-id]: /path/to/page/ "Title text"` and has worked as expected before the upgrade. Locally both with `mkdocs serve` and `mkodcs build` on a Win 10, and `mkdocs build` on our Linux build servers. Now when using `mkdocs build` both locally and on the build servers, all links referenced as above 404s but works correctly locally with `mkdocs serve`.

I tried to change the form of the links to `[link-id]: path/to/page/ "Title text"` but that just made things worse both with `build` and `serve`. 

I've compiled my findings below:
Local project is placed in `file:///C:/DevTest/`

### mkdocs.yml
```yaml
site_name: 'DevTest'
site_dir: 'site'
use_directory_urls: true
strict: true

nav:
  - Root:
    - Home: index.md
    - Level 1:
      - Overview: level-1/index.md
      - Level 2:
        - Source page: level-1/level-2/index.md
  - Feature 1: 
    - Home: feature-1/index.md
    - Level 1:
      - Target page: feature-1/level-1/index.md
```

### Expected behaviour
With link in .md for "Source page": `[link]: /feature-1/level-1/ "Feature 1 - Level 1"`
Expected HTML source: `<p><a href="/feature-1/level-1/" title="Feature 1 - Level 1">Feature 1 - Level 1</a></p>`
Expected serve target: `http://127.0.0.1:8000/feature-1/level-1/`
Expected build target: `file:///C:/DevTest/site/feature-1/level-1/`
Target received by right clicking the link in Google Chrome and selecting "Copy link adress".

### Actual behaviour
**Default theme**
Serve HTML source: `<p><a href="/feature-1/level-1/" title="Feature 1 - Level 1">Feature 1 - Level 1</a></p>`
Serve target: `http://127.0.0.1:8000/feature-1/level-1/`
Build HTML source: `<p><a href="/feature-1/level-1/" title="Feature 1 - Level 1">Feature 1 - Level 1</a></p>`
Build target: `file:///C:/feature-1/level-1/`

**ReadTheDocs theme**
Serve HTML source: `<p><a href="/feature-1/level-1/" title="Feature 1 - Level 1">Feature 1 - Level 1</a></p>`
Serve target: `http://127.0.0.1:8000/feature-1/level-1/`
Build HTML source: `<p><a href="/feature-1/level-1/" title="Feature 1 - Level 1">Feature 1 - Level 1</a>`
Build target: `file:///C:/feature-1/level-1/`

**Material**
Serve HTML source: `<p><a href="/feature-1/level-1/" title="Feature 1 - Level 1">Feature 1 - Level 1</a></p>`
Serve target: `http://127.0.0.1:8000/feature-1/level-1/`
Build HTML source: `<p><a href="/feature-1/level-1/" title="Feature 1 - Level 1">Feature 1 - Level 1</a></p>`
Build target: `file:///C:/feature-1/level-1/`
