### ISSUE TITLE
README.md -> index.md should be optional

### ISSUE THREAD

**Issue by Galarzaa90** [mkdocs/mkdocs#1580]
This is a really useful feature, but it should be optional.

I have a `README.md` file in my repository exclusively to render it on GitHub, indicating that the documentation uses format not compatible with GitHub, and that it should be viewed on the generated site.

See: https://github.com/Galarzaa90/NabBot/tree/master/docs

Now, I also have an `index.md` file in the `docs` folder, and that is the actual homepage of my site, and now it is getting overriden by `README.md` and there's no way to see the homepage anymore.

See:
- https://galarzaa90.github.io/NabBot/ - Generated Site
- https://github.com/Galarzaa90/NabBot/blob/master/docs/index.md  - My index.md file

And this is my `pages`/`nav` section:
```yml
nav:
    - Home: index.md
    - Changelog: changelog.md
    - Install Guide: install.md
    - Permissions: permissions.md
    - FAQ: faq.md
    - Features:
      - Overview: features/index.md
      - Autoroles: features/autoroles.md
      - Groups: features/groups.md
    - Commands:
      - Overview: commands/index.md
      - Admin commands: commands/admin.md
      - General commands: commands/general.md
      - Info commands: commands/info.md
      - Loot commands: commands/loot.md
      - Mod commands: commands/mod.md
      - Owner commands: commands/owner.md
      - Roles commands: commands/roles.md
      - Settings commands: commands/settings.md
      - Tibia commands: commands/tibia.md
      - TibiaWiki commands: commands/tibiawiki.md
      - Tracking commands: commands/tracking.md
    - Hosting:
      - Configuration: hosting/config.md
      - Messages: hosting/messages.md
      - Cogs: hosting/cogs.md
```

Full file: https://github.com/Galarzaa90/NabBot/blob/master/mkdocs.yml
