### ISSUE TITLE
Add support for external doc link

### ISSUE THREAD

**Issue by xiaojiang01** [mkdocs/mkdocs#1585]
Our platform have multiple repos. Each repo have some docs. We wanted still keep the doc next to the relevant code, but wanted to create a centralized documentation repo to make the browsing, searching across multi repo easier. Does Mkdocs support link to a page outside of the repo like below:
```
pages:
    - Home: index.md
    - Pattern: github.com/org1/docs/Patterns.md
    - Setup: github.com/org2/docs/setup.md
    - Support: support.md
```

**Comment by waylan** [comment]
On version 1.0 (but not before) you can include links in your navigation to outside pages. Of course, those outside pages will still exist elsewhere. However, to link to them you need to use full URLs: `https://example.com/link/to/page`.

**Comment by xiaojiang01** [comment]
This is awesome! I just upgraded and had a try in my local. With below config, I would hope the Mkdocs CONTRIBUTING.md would be shown on my doc site like I have a doc file in local while it is actually went to the external site.  It this how the external like navigation is implemented or did I miss any configuration?
```
pages:
    - Home: index.md
    - Pattern: Patterns.md
    - Architecture: architecture.md
    - Support: https://github.com/mkdocs/mkdocs/blob/master/CONTRIBUTING.md
```
I am expecting:
<img width="942" alt="screen shot 2018-08-12 at 1 00 39 am" src="https://user-images.githubusercontent.com/11673732/43998752-3437678e-9dcb-11e8-93da-1cbea33483b6.png">

The Actual Result:
<img width="889" alt="screen shot 2018-08-12 at 12 54 24 am" src="https://user-images.githubusercontent.com/11673732/43998719-687d74b2-9dca-11e8-8a34-ec0f53b7cddc.png">
