### ISSUE TITLE
Question: Can I create pages from mkdocs.yml ?

### ISSUE THREAD

**Issue by HWataru** [mkdocs/mkdocs#1593]
Hi

does mkdocs support officially to create pages file ?

I created [simple helper method](https://gist.github.com/HWataru/5f22bcd94c332c002d567fda525546c9).   I would appreciate it if mkdocs supports command like

```
> mkdocs init
...
create new file new_page.md
```

Thank you

**Comment by waylan** [comment]
No, we don't offer such a feature. Although, not sure what value it would have. All it would do would be to create an empty plain text file. Your text editor should be able to do that. If you really want to create a new blank file from the command line, then there are various existing system commands you could use.

If I understand the request correctly, you want to add new files to the `nav` setting of the config and then use that to create the files. The problem is that the config will fail to load as config validation will fail when it encounters files which are listed but do not exist. In other words, you can't add files to the config until after they are created.

**Comment by HWataru** [comment]
>The problem is that the config will fail to load as config validation will fail when it encounters files which are listed but do not exist. In other words, you can't add files to the config until after they are created.

Yap I knew it. But first of all, I create page composition before I write document with mkdocs.

```yml
nav:
  - about: about.md
  - getting started:
    - requirements: getting_started/requirements.md
    - installation: getting_started/installation.md
    - sample code: getting_started/sample_code.md
  - refference:
     ....
```

After that, I start to write document. So it's required for me to create pages from my config yml.

How do you think it?
