### ISSUE TITLE
extra_javascript and extra_css outside docs_dir 

### ISSUE THREAD

**Issue by ngtrian** [mkdocs/mkdocs#1662]
I has config mkdocs.yaml with **extra_javascript** and **extra_css** outside `docs_dir `
```yaml
extra_css:
  - ../lib/extra.css

extra_javascript:
  - ../lib/extra.js
```
Seem it not working
