### ISSUE TITLE
Development Override for Certain Mkdocs.yml values

### ISSUE THREAD

**Issue by sheldonhull** [mkdocs/mkdocs#1681]
I want to provide the values for 
```
repo_name
repo_url
edit_uri
```
in my dev branch that i publish internally to allow edits I want to set these. 
However, I want to ensure the master branch for production release does not set these values as they point to inaccessible private servers. How can I properly ensure mkdocs.yml is still not in the gitignore list, but that I allow my dev branch to provide these values while production does not get these set? 

I couldn't find clarity on a "mkdocs.dev.yml" type of approach, so any guidance would be appreciated if there is a solution to this. This is sort of similar to the plugin config I noticed here that sets something to enabled if env = value.

```yml
plugins:
    - search
    - pdf-export:
        verbose: true
        media_type: print
        enabled_if_env: ENABLE_PDF_EXPORT
```
