### ISSUE TITLE
Markdown content of  <details> not converted to html

### ISSUE THREAD

**Issue by cakrit** [mkdocs/mkdocs#1687]
mkdocs version 1.0.1

For the following general MD syntax:
```
<details>
 <summary>SUMMARY TEXT</summary>
 MARKDOWN CONTENT
</details>
```
Expected behavior: "MARKDOWN CONTENT" is be translated to HTML (e.g. dashes should become lists)

Actual behavior: "MARKDOWN CONTENT" is treated as text. 

Verified with Material and Alabaster themes.

**Comment by froschdesign** [comment]
@cakrit 
This behaviour is correct, because the Markdown formatting syntax is not processed within block-level HTML tags.

MkDocs uses [Python-Markdown](https://python-markdown.github.io/) as parser for Markdown. The parser supports extensions and there you will find the solution: https://python-markdown.github.io/extensions/extra/

**Comment by waylan** [comment]
Closed as an upstream issue. Although, as pointed out, the behavior is correct.

**Comment by cakrit** [comment]
I appreciate the quick response. I added a few more extensions, but still getting the same result. Can you help me identify which one would do the trick? The relevant extansions I've added can be seen below:

```
 - pymdownx.arithmatex
 - pymdownx.betterem:
    smart_enable: all
 - pymdownx.caret
 - pymdownx.critic
 - pymdownx.details
 - pymdownx.emoji:
    emoji_generator: !!python/name:pymdownx.emoji.to_svg
 - pymdownx.inlinehilite
 - pymdownx.magiclink
 - pymdownx.mark
 - pymdownx.smartsymbols
 - pymdownx.superfences
 - pymdownx.tasklist:
    custom_checkbox: true
 - pymdownx.tilde
 - pymdownx.betterem
 - pymdownx.superfences
 - markdown.extensions.footnotes
 - markdown.extensions.attr_list
 - markdown.extensions.def_list
 - markdown.extensions.tables
 - markdown.extensions.abbr
 - pymdownx.extrarawhtml
```
