### ISSUE TITLE
Read extra variable data from file(s)

### ISSUE THREAD

**Issue by wilhelmer** [mkdocs/mkdocs#1698]
I find the '[extra](https://www.mkdocs.org/user-guide/configuration/#extra)' variable to be very useful, especially in combination with plugins like [markdownextradata](https://github.com/rosscdh/mkdocs-markdownextradata-plugin).

It would be nice if mkdocs could also read the key/value pairs from seperate files, similar to extra_css and extra_javascript. Something like:

#### mkdocs.yml
```yaml
extra_yml:
    - data.yml
```
#### data.yml

```yaml
customer:
    name: Your name here
    web: www.example.com
    salt: salt.example.com
```

Or is there already a way to achieve this?
