### ISSUE TITLE
Read in extra data about a file in path heirarchy

### ISSUE THREAD

**Issue by byrnereese** [mkdocs/mkdocs#1709]
A feature I have seen requested is a way to hide pages. I was contemplating this myself in my own docs project and was wondering if the following mkdocs.yml syntax is supported, or could be:

```yml
nav:
   - 'Page Name': 'page1.md'
   - 'Section Name':
      - 'Another Page': 
           - file: 'page2.md'
           - hidden: True
```

In other words, could the nav/page tree be serialized into or from a hierarchy that allows for more meta data to be associated with a node?
