### ISSUE TITLE
Changing the favicon not working

### ISSUE THREAD

**Issue by TheTimBecker** [mkdocs/mkdocs#1717]
Version 1.0.4

https://www.mkdocs.org/#changing-the-favicon-icon

I tried putting my own favicon in `docs/img/favicon.ico` but it's not getting picked up by `mkdocs serve` or `mkdocs build`. I tried with the Google favicon to make sure it didn't have something to do with my favicon specifically.

I'm just working through the tutorial, so my project is very bare bones. Am I missing something?

directory structure
```
.
├── docs
│   ├── about.md
│   ├── img
│   │   └── favicon.ico
│   └── index.md
└── mkdocs.yml
```

mkdocks.yml
```yml
site_name: MkLorum
nav:
    - Home: index.md
    - About: about.md
```

**Comment by waylan** [comment]
This is a duplicate of #1671, which has been fixed in #1672 and will be available in the next release.

**Comment by matthewcornell** [comment]
I have the same problem. I just installed via pip: `mkdocs, version 1.0.4 from /Users/xx/.local/share/virtualenvs/mkdocs-play-WU87r0Tr/lib/python3.6/site-packages/mkdocs (Python 3.6)
`. That release was on `Sep 7, 2018`, and the above fix was on `Nov 2, 2018`. Is the project still active? I see recent commits... Thank you.

**Comment by waylan** [comment]
> will be available in the next release

We have made no new releases since version 1.0.4. As we are volunteers who work on MkDocs in our spare time, we can't always do a release immediately after a fix has been applied. I do not know when the next release will be made, but when it is, it will contain the fix.

**Comment by pavinduLakshan** [comment]
I'm still facing this issue. The favicon is in docs/images and I'm referencing it in the mkdocs.yml as follows, but still I can't see the favicon when running with `mkdocs serve`. Any help is highly appreciated.

```yaml
# Configuration
theme: material
theme:
  name: material
  palette:
    scheme: preference
    primary: deep-orange
    accent: deep-orange
  custom_dir: theme/material
  logo: images/logo.svg
  favicon: images/favicon.png
  highlightjs: true
  feature:
    tabs: true
  language: en
```
