### ISSUE TITLE
Top-level 'nav' order not respected on ReadTheDocs

### ISSUE THREAD

**Issue by jacebrowning** [mkdocs/mkdocs#1723]
Given this table of contents:

```yaml
nav:
- Home: index.md
- Options:
  - ...
- Types:
  - ...
- About:
  - ...
```
https://github.com/jacebrowning/datafiles/blob/189fadfed677cc0a11eec13ddaaef6565696472d/mkdocs.yml

The top-level headings are rendered out-of-order on ReadTheDocs:

![](https://zappy.zapier.com/56AD4D28-3A3E-455D-8046-01CFAB5FB41F.png)

https://datafiles.readthedocs.io/en/latest/

Here is the build log: https://readthedocs.org/api/v2/build/8387498.txt

---

Locally, `mkdocs` is producing the correct order. Have I misconfigured `mkdocs` in some way?
