### ISSUE TITLE
Indent the second row

### ISSUE THREAD

**Issue by wuhaiyang** [mkdocs/mkdocs#1731]
![cd540bee-2612-42f8-a66c-471cf45198ec](https://user-images.githubusercontent.com/8447716/51758766-71d55100-2101-11e9-8624-829f7600dcb9.png)

mkdocs.yml

theme:
```yaml
name: 'material'  
markdown_extensions:
  - extra
  - admonition
  - codehilite
  - legacy_em
  - meta
  - nl2br
  - sane_lists
  - smarty
  - toc
  - wikilinks
  - pymdownx.tasklist  
  - def_list
```
