### ISSUE TITLE
Math expression does not render correctly.

### ISSUE THREAD

**Issue by doosik71** [mkdocs/mkdocs#1733]
$$L_i = {1 \over N} \sum_i \sum_{j \ne y_i} [ \max(0, f(x_i;W)_j - f(x_i;W) + \Delta) ]$$

    $$L_i = {1 \over N} \sum_i \sum_{j \ne y_i} [ \max(0, f(x_i;W)_j - f(x_i;W)_{y_i} + \Delta) ]$$

First one is ok, but second one fails. There are something unknown problem around underscore and braces.

**Comment by doosik71** [comment]
Below is my yaml and js file configuration.

- mkdocs.yml
```
site_name: My Docs
markdown_extensions:
  - extra
  - tables
  - fenced_code
extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - mathjaxhelper.js
theme: readthedocs
```

- docs\mathjaxhelper.js
```
window.MathJax = {
  tex2jax: {
    inlineMath: [ ["$","$"], ["\\(","\\)"] ],
    displayMath: [ ["$$","$$"], ["\\[","\\]"] ]
  },
  TeX: {
    TagSide: "right",
    TagIndent: ".8em",
    MultLineWidth: "85%",
    equationNumbers: {
      autoNumber: "AMS",
    },
    unicode: {
      fonts: "STIXGeneral,'Arial Unicode MS'"
    }
  },
  displayAlign: "center",
  showProcessingMessages: false,
  messageStyle: "none"
};
```

 Thanks.

**Comment by algo99** [comment]
Not sure what are you doing wrong, but this way we use inline LaTeX in our documentation:

```yaml
markdown_extensions:
    - ...
    - mdx_math
    - ...

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS_HTML
```
