### ISSUE TITLE
Errors with markdown_extensions and travis-ci 

### ISSUE THREAD

**Issue by ncarboni** [mkdocs/mkdocs#1734]
I am having a problem with mkdocs and travis-ci. 
I am setting up travis-ci to build up my documentation website on each commit instead of deploying everything myself. The current set of parameters works perfectly with the command `mkdocs serve`, and I do not have any issue also if I do a `mkdocs gh-deploy`.

However, when I tried to use travis-ci I get the error:
```
ERROR   -  Config value: 'markdown_extensions'. Error: configs 
Aborted with 1 Configuration Errors!
The command "mkdocs build -f ../mkdocs.yml --site-dir doks/" failed and exited with 1 during .
```

I get this error only if I do install and have in my mkdocs.yml a markdown lightbox extension. I tried with both [markdown-lightbox](https://github.com/AliciaSchep/markdown-lightbox) and [lightgallery markdown](https://github.com/g-provost/lightgallery-markdown) to check if maybe one of them was the problem, but I get the same issue with both. Has anyone had a similar problem or know what could it causes it/how to get around it?

Below the log from travis-ci, travis.yml and my mkdocs.yml.

```
running install
running bdist_egg
running egg_info
creating lightgallery.egg-info
writing requirements to lightgallery.egg-info/requires.txt
writing lightgallery.egg-info/PKG-INFO
writing top-level names to lightgallery.egg-info/top_level.txt
writing dependency_links to lightgallery.egg-info/dependency_links.txt
writing manifest file 'lightgallery.egg-info/SOURCES.txt'
reading manifest file 'lightgallery.egg-info/SOURCES.txt'
writing manifest file 'lightgallery.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
copying lightgallery.py -> build/lib
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
copying build/lib/lightgallery.py -> build/bdist.linux-x86_64/egg
byte-compiling build/bdist.linux-x86_64/egg/lightgallery.py to lightgallery.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying lightgallery.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying lightgallery.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying lightgallery.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying lightgallery.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying lightgallery.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/lightgallery-0.1.0-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing lightgallery-0.1.0-py2.7.egg
Copying lightgallery-0.1.0-py2.7.egg to /home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages
Adding lightgallery 0.1.0 to easy-install.pth file
Installed /home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/lightgallery-0.1.0-py2.7.egg
Processing dependencies for lightgallery==0.1.0
Searching for Markdown==3.0.1
Best match: Markdown 3.0.1
Adding Markdown 3.0.1 to easy-install.pth file
Installing markdown_py script to /home/travis/virtualenv/python2.7.14/bin
Using /home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages
Finished processing dependencies for lightgallery==0.1.0
0.26s$ mkdocs build -f ../mkdocs.yml --site-dir doks/
ERROR   -  Config value: 'markdown_extensions'. Error: configs 
Aborted with 1 Configuration Errors!
The command "mkdocs build -f ../mkdocs.yml --site-dir doks/" failed and exited with 1 during .
```

travis.yml :

```yml
env:
  global:
    secure: [//key]

language: python # Set the build language to Python

#python: 3.6 # python version

branches: master # Set the branch to build from

install:
    - pip install mkdocs # Install the required dependencies
    - pip install mkdocs-material
    - pip install pymdown-extensions
    - git clone https://github.com/g-provost/lightgallery-markdown.git
    - cd lightgallery-markdown
    - python setup.py install
    - mkdocs build -f ../mkdocs.yml --site-dir doks/
```
    
My mkdocs yml:

```yml
site_name: name
#repo_url: https://github.com/address
site_description: name

# Customization
extra:
  social:
    - type: globe
    - link: name
  

# pagination  
nav:
    - Project Home: index.md
    - Entity Reference Model:
      - Instruction: instruction.md
      - Artist : et/person.md
      - Artwork: et/artwork.md
    - Modelling Examples:
      - Instruction: pattern/instruction.md
      - Shared: pattern/general.md
      - Temporal: pattern/temporal.md
#     - Conceptual: pattern/conceptual.md
      - Physical: pattern/physical.md  
    - Ontology Extension:
      - Extension: schema.md

theme:
  name: 'material'
  logo: 'images/logo.png'
  favicon: 'images/favicon.ico'
  font:
    text: 'Source Sans Pro'
    code: 'IBM Plex Mono'
  custom_dir: 'theme/'
  palette:
    primary: 'white'
 
markdown_extensions:
  - pymdownx.smartsymbols
  - lightgallery
  - pymdownx.mark
  - markdown.extensions.attr_list
  - pymdownx.superfences
  - pymdownx.details
  - toc:
      permalink: true
  - codehilite:
      linenums: true
  - meta
  - footnotes
  - admonition
  - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_div_format

  

extra_css:
#  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.css
  - 'stylesheets/extra.css'
extra_javascript:
#  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.min.js
```

Thanks!

**Comment by waylan** [comment]
It would appear that you have an error in your `markdown_extensions` config setting. However, it also appears that the error is being raised by Markdown, which is not passing a clear message back to MkDocs. So you'll need to use the process of elimination. Change one item at a time until you find the one causing the error.

To avoid pushing to your CI after each small change, you might want to try setting up a local Python virtualenv with the exact same dependencies installed as on Travis. It is possible that there is something you are missing. However, if that doesn't provide a solution, you will need to push each small change to your CI until to find the one which is raising an error. I realize this one-at-a-time method is less than ideal, but I'm not sure how else to work it out if you can't replicate is locally.

The first thing I would try is the `pymdownx.superfences` config. The `custom_fences` value should contain a dict, but you have a list which contains a dict. Remove the hyphen (`-`) from infront of `name`:
```yaml
  - pymdownx.superfences:
        custom_fences:
            name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_div_format
```

If that doesn't resolve it, then remove each extension one-at-a-time until to find the one which is raising an error. When you find it, make sure all the proper dependencies are installed, you spelled it correctly, etc.
