### ISSUE TITLE
Active Tab not working correctly

### ISSUE THREAD

**Issue by chrisprijic** [mkdocs/mkdocs#1737]
In my current use case, I'm having a particular issue where the navigation tabs are not being highlighted in certain cases. I don't know the exact pattern or cause, but I've detailed a particular situation below.

## Platform
Windows 10
Python 3.7
Mkdocs 1.0.3
Mkdocs-Material 3.0.4

Current mkdocs.yml:

```yml
site_name: Test
site_description: "Documentation for Test"
site_author: 'Test Author'
site_url: 'https://test.com'
copyright: 'Copyright © 2019 | Test Inc.  | All Rights Reserved'

theme:
  name: 'material'
  custom_dir: 'theme'
  include_search_page: false
  search_index_only: true
  palette:
    primary: 'blue'
    accent: 'blue'
  logo: 'images/logo.png'
  favicon: 'images/logo.png'
  feature:
    tabs: true

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_css:
  - 'styles/branding.css'
  - 'styles/api.css'

nav:
  - Guides:
    - Cat1:
      - P1: guides/P1.md
      - P2: guides/P2.md
      - P3: guides/P3.md
    - Cat2:
      - P4: guides/P4.md
```

## Desired Behavior: 

When on Page P4, "Guides" tab should be active.

## Viewed Behavior:

When on Page P4, no tab is marked "active".

## Additional Notes:

Since looking at Mkdocs-material [here](https://github.com/squidfunk/mkdocs-material/blob/master/src/partials/tabs-item.html), I don't think this is an issue with Mkdocs-Material -- their if-statement marks active tabs if mkdocs labels the tab active. 

If there's any additional information needed, I'd be happy to provide it.
