### ISSUE TITLE
Option to include markdown header/footer on each page

### ISSUE THREAD

**Issue by majkinetor** [mkdocs/mkdocs#1741]
I have header and footer that I want to use on each page. I am currently using `markdown_include` plugin and that works fine. However, I still need to write on each page:

```
...
{!_inc/footer.md!}
```
It would be great to add into config or via plugin such feature. For example:

```yaml
extra_content:
     header: |
             Some **markdown** here
             and here
     footer: {!_inc/footer.md!}       
```

If this is already possible via some way (that doesn't include external preprocessing) please let me know how. Sphyx has comparative feature - `rst_prolog` & `rst_epilog`
