### ISSUE TITLE
broken sitemap.xml with external link in nav

### ISSUE THREAD

**Issue by brandongc** [mkdocs/mkdocs#1742]
A `mkdocs.yml` like:

```yaml
nav:
    - Home: index.md
    - Test: https://www.example.com
    - User Guide:
        - Writing Your Docs: user-guide/writing-your-docs.md
```

results in a sitemap.xml that google search console throws errors for:

```
    <url>
     <loc></loc>

     <changefreq>daily</changefreq>
    </url>
```
