### ISSUE TITLE
Live reload + Docker/Vagrant

### ISSUE THREAD

**Issue by robinandeer** [mkdocs/mkdocs#178]
I'm trying to build my documentation in a Docker container with a shared folder between the VM and my local computer. However, mkdocs (or watchdog I guess) doesn't seem to register when I edit files locally. Therefore the live rebuild feature doesn't work.

Has anyone experienced something similar? I know that setting up e.g. Flask (using --reload) in the same way works just as expected.

My Dockerfile:

``` Dockerfile
FROM dockerfile/python
ADD . /code
WORKDIR /code
RUN pip install mkdocs

EXPOSE 8000
CMD ["mkdocs", "serve"]
```

My fig.yml file (if you've use it, basically just setting command line options for Docker) looks like this:

``` yaml
docs:
  build: docs
  volumes:
    - docs:/code
  ports:
    - "8000:8000"
```
