### ISSUE TITLE
Allow relative external links (in nav or in pages) to be "framed" or enclosed into the main site page

### ISSUE THREAD

**Issue by smarie** [mkdocs/mkdocs#1806]
It is currently possible to use external links in the navigation pane. These external links can either be provided as absolute URLS, or as relative ones. The [doc](https://www.mkdocs.org/user-guide/configuration/) states that "Any path which is not found in the files is assumed to be an external link.".

Could it be possible that by default or with some new option, relative links are "framed" into the site rather that leaving the current page to open the new one ? 

My use case is that I would like to create a "main" web site in a github repository, with easy navigation to the web sites of other repositories. Since all of them are in github, there is no cross-site: all of them are sub-paths of the base "github pages" host name https://smarie.github.io/ .

```yaml
(...mkdocs.yml for https://smarie.github.io/ALL )
nav:
    - Home: index.md
    - Test:
        - makefun_absolute: https://smarie.github.io/python-makefun/  # this would leave current page to open the new page
        - makefun_relative: ../../python-makefun  # this would open the new page "inside" the current page
```

In terms of how this could be done, well I am not a HTML expert so just a few ideas I can think of - I let you decide whichever would lead to the smoothest results:

 - iframe: probably very bad looking but very simple to do. Both the secondary sidebar and md-contents would be replaced by the frame, leaving only the Primary sidebar and header/footer.

 - if the external site is itself a mkdocs-generated site (which is the case for me) some more customized integration could maybe happen, leading to smoother results?

This would definitely be a cool way to link various sites generated for various github repositories, under a unique umbrella.

EDIT: see https://smarie.github.io/ALL_OF_THE_ABOVE/ for an illustration of today's behaviour (click on python on the left and select one library)
