### ISSUE TITLE
Google Adsense

### ISSUE THREAD

**Issue by fpscan** [mkdocs/mkdocs#1820]
Hi Everyone,

I was wondering if there is any documentation for adding Google Adsense. What I have done so far is 

```yaml
extra:
  **content: adsense.html**
  version: '0.1.0'
  font:
    text: 'Roboto'
```

and made put adsense code into adsense.html file
