### ISSUE TITLE
Plugins and Extensions plugin is not installed after added to .yml

### ISSUE THREAD

**Issue by HRSlab** [mkdocs/mkdocs#1836]
#### After Installation of plugins and/or extensions and configuring it in `mkdocs.yml` :  

```ERROR   -  Config value: 'plugins'. Error: The "git-committers" plugin is not installed ```

## Here what I did:

```
MacBook1313:hrs MacbookPro$ mkdocs serve
INFO    -  Building documentation... 
ERROR   -  Config value: 'plugins'. Error: The "git-committers" plugin is not installed 

Aborted with 1 Configuration Errors!
MacBook1313:hrs MacbookPro$ pip3 install mkdocs-git-committers-plugin
Requirement already satisfied: mkdocs-git-committers-plugin in /usr/local/lib/python3.7/site-packages (0.1.8)
Requirement already satisfied: PyGithub>=1.43 in /usr/local/lib/python3.7/site-packages (from mkdocs-git-committers-plugin) (1.43.8)
Requirement already satisfied: mkdocs>=0.17 in /usr/local/lib/python3.7/site-packages (from mkdocs-git-committers-plugin) (1.0.4)
Requirement already satisfied: deprecated in /usr/local/lib/python3.7/site-packages (from PyGithub>=1.43->mkdocs-git-committers-plugin) (1.2.6)
Requirement already satisfied: pyjwt in /usr/local/lib/python3.7/site-packages (from PyGithub>=1.43->mkdocs-git-committers-plugin) (1.7.1)
Requirement already satisfied: requests>=2.14.0 in /usr/local/lib/python3.7/site-packages (from PyGithub>=1.43->mkdocs-git-committers-plugin) (2.22.0)
Requirement already satisfied: click>=3.3 in /usr/local/lib/python3.7/site-packages (from mkdocs>=0.17->mkdocs-git-committers-plugin) (7.0)
Requirement already satisfied: livereload>=2.5.1 in /usr/local/lib/python3.7/site-packages (from mkdocs>=0.17->mkdocs-git-committers-plugin) (2.6.1)
Requirement already satisfied: PyYAML>=3.10 in /usr/local/lib/python3.7/site-packages (from mkdocs>=0.17->mkdocs-git-committers-plugin) (5.1)
Requirement already satisfied: Jinja2>=2.7.1 in /usr/local/lib/python3.7/site-packages (from mkdocs>=0.17->mkdocs-git-committers-plugin) (2.10.1)
Requirement already satisfied: tornado>=5.0 in /usr/local/lib/python3.7/site-packages (from mkdocs>=0.17->mkdocs-git-committers-plugin) (6.0.2)
Requirement already satisfied: Markdown>=2.3.1 in /usr/local/lib/python3.7/site-packages (from mkdocs>=0.17->mkdocs-git-committers-plugin) (3.1.1)
Requirement already satisfied: wrapt<2,>=1.10 in /usr/local/lib/python3.7/site-packages (from deprecated->PyGithub>=1.43->mkdocs-git-committers-plugin) (1.11.2)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/site-packages (from requests>=2.14.0->PyGithub>=1.43->mkdocs-git-committers-plugin) (1.25.3)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/local/lib/python3.7/site-packages (from requests>=2.14.0->PyGithub>=1.43->mkdocs-git-committers-plugin) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/site-packages (from requests>=2.14.0->PyGithub>=1.43->mkdocs-git-committers-plugin) (2019.6.16)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.7/site-packages (from requests>=2.14.0->PyGithub>=1.43->mkdocs-git-committers-plugin) (3.0.4)
Requirement already satisfied: six in /usr/local/lib/python3.7/site-packages (from livereload>=2.5.1->mkdocs>=0.17->mkdocs-git-committers-plugin) (1.12.0)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.7/site-packages (from Jinja2>=2.7.1->mkdocs>=0.17->mkdocs-git-committers-plugin) (1.1.1)
Requirement already satisfied: setuptools>=36 in /usr/local/lib/python3.7/site-packages (from Markdown>=2.3.1->mkdocs>=0.17->mkdocs-git-committers-plugin) (41.0.1)
MacBook1313:hrs MacbookPro$ mkdocs serve
INFO    -  Building documentation... 
ERROR   -  Config value: 'plugins'. Error: The "git-committers" plugin is not installed 

Aborted with 1 Configuration Errors!
```

## This is my configuration file:

```YAML
nav:
    - Welcome: index.md
    - User Persona: users.md
    - User Stories: features.md
    - Timeline: timeline.md
    - Tasks: tasks.md
    - Budget: cost.md
    - Site Map: sitemap.md
    - Wireframes: wireframe.md
    - Change Requests: change.md
    - Submit bugs: bug.md

theme:
  name: null
  custom_dir: mkdocs-material/material
  language: en
  palette:
    primary: 'blue'
    accent: 'light blue'
  font:
    text: Titillium Web
    code: Roboto Mono
  logo: 'images/HRSlogo-rounded-base.png'
  feature:
    tabs: false

extra_css:
  -  stylesheets/extra.css
  -  stylesheets/small.css
  -  https://fonts.googleapis.com/icon?family=Material+Icons
  
extra_javascript:
  -   'javascripts/extra.js'

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - tables
  - markdown.extensions.tables

plugins:
  - search
  - git-committers
```

## Versions: 

`mkdocs: 1.0.4`
`Python: 3.7.4`
`mkdocs-material:: 4.4.0`
