### ISSUE TITLE
Search and custom templates not working on custom themes

### ISSUE THREAD

**Issue by oscarmcm** [mkdocs/mkdocs#1895]
Hi, Im working on docs site using mkdcos, with a custom theme, but when I try to test the search or the 404 template, this is not properly copied neither to the build dir or to the test/dev dir, this is the project layout im using

```shell
demo-project
├── custom_theme
│   ├── 404.html
│   ├── main.html
│   ├── mkdocs_theme.yml
│   └── search.html
├── docs
│   └── index.md
└── mkdocs.yml
```

and this is the `mkdocs.yml` content

```yml
site_name: My Docs
theme:
  name: null
  custom_dir: custom_theme
```

and this the `mkdocs_theme.yml` content

```yml
static_templates:
    - 404.html

include_search_page: true
search_index_only: false
```

Everything here is equal as the docs points on how to [create a custom theme](https://www.mkdocs.org/user-guide/custom-themes/#creating-a-custom-theme) the very strange thing here is if you set the `theme.name` to X value, like `readthedocs` for example, the templates are properly copied because (as the docs point):

> Generally, when building your own custom theme, the theme.name configuration setting would be set to null. However, if the theme.custom_dir configuration value is used in combination with an existing theme, the theme.custom_dir can be used to replace only specific parts of a built-in theme. 

Which means that the templates arent copied if the `theme.name` is set to `null`.

Thanks.

**Comment by waylan** [comment]
A `mkdocs_theme.yml` is not used for the `custom_dir`. In that case, the theme config is defined in the `theme` setting of `mkdocs.yml`. Therefore, your `mkdocs.yml` file should contain:

```yml
site_name: My Docs
theme:
  name: null
  custom_dir: custom_theme
  static_templates:
    - 404.html

  include_search_page: true
  search_index_only: false
```
