### ISSUE TITLE
Setting links to open in new tabs is not working

### ISSUE THREAD

**Issue by nocode99** [mkdocs/mkdocs#1958]
mkdocs version: 1.0.4
python version: 3.7.0

mkdocs extension:
```
# Markdown extensions
markdown_extensions:
  - admonition
  - codehilite
  - smarty
  - meta
  - toc:
      permalink: True
  - markdown_include.include:
      base_path: docs
```

Something like `[Title](https://github.com){.new-tab}` just renders as [Title](url){.new-tab}

Here is a snippet of the html that is generated:

`<p><a href="https://github.com">Title</a>{.new-tab}</p>`

I've also tried using `{target=_blank}` with similar behavior as above.

**Comment by waylan** [comment]
Attribute lists require that the [`attr_list`][1] extension be enabled. You need to add that to the `markdown_extensions` config setting:

```yml
markdown_extensions:
  - admonition
  - codehilite
  - smarty
  - meta
  - toc:
      permalink: True
  - markdown_include.include:
      base_path: docs
  - attr_list
```

[1]: https://python-markdown.github.io/extensions/attr_list/
