### ISSUE TITLE
Refer to same file several times in contents

### ISSUE THREAD

**Issue by Vanderhoof** [mkdocs/mkdocs#1974]
Hello!
I am building a project which should have two structure trees. So in the contents there will be two branches which refer to the same files with different subcaptions and different level of nesting.

For example, I have a source file `auth.md` and I want it to appear two times, nested under `Basic -> Authentication` subcaptions, and `Alternative -> Auth` subcations. I define pages like this:

```yaml
pages:
- basic:
  - "Authentication": auth.md
- Alternative:
  - "Auth": auth.md
```

It all seems to work, but no matter which link I click in the contents:

![](https://i.imgur.com/tsF0sNu.png)

After the page loads, I have always the "Alternative" subcaption active in contents:

![](https://i.imgur.com/NZbZ5CE.png)

Is there a way to point mkdocs which link was clicked if there are several links pointing to one file in the contents?

**Comment by waylan** [comment]
Yes, MkDocs assumes each page occurs only once. As a reminder, MkDocs is a ***static** site generator*. That means that the page `auth.md` is only built once with one of the locations in the nav being the "active" location (this location is "static"). If you want it to appear as if there are two separate locations, then you need two separate files/pages.

Of course, I understand that you don't want to have two copies of the same file, as edits would be a pain. I would suggest using a symbolic link. Have the actual file at one location, and then link to that file from the other location. MkDocs will see the linked file as a separate page and build two pages, each with its own different "active" nav menu item. Perhaps something like this:

```yaml
pages:
- basic:
  - "Authentication": basic-auth.md
- Alternative:
  - "Auth": alt-auth.md
```
