### ISSUE TITLE
Load categories README.md

### ISSUE THREAD

**Issue by lyz-code** [mkdocs/mkdocs#1975]
FIrst of all, thank you for the awesome program.

I was wondering if there was a way that the navigation panel would load the README of the categories.

Imagine the following directory tree:

```
└── docs
    ├── about.md
    └── life_automation
        ├── taskwarrior.md
        ├── grocy.md
        └── README.md
```

I'd like to have the following `nav` bar:

```yaml
nav:
  - About: 'about.md'
  - Life Automation: 
      - Grocy: life_automation/grocy.md
      - Taskwarrior: life_automation/taskwarrior.md
```

So when anyone clicks over the `Life Automation` menu, it get's unfolded and the `life_automation/README.md` get's loaded. This is the default behavior for GitBooks, (see an [example](https://wiki.nikitavoloboev.xyz/meta).

With the current behavior, I see the following options:

```yaml
nav:
  - Life Automation: 
      - Introduction: life_automation/README.md
      - Grocy: life_automation/grocy.md
```

Which looks good in the nav bar, but the *next* and *previous* lower buttons are not descriptive.

Or using `Life Automation` in place of `Introduction`, which looks good in the *next* and *previous* buttons, but looks bad in the nav bar.

How do you usually tackle this cases?

I've searched in the issues but I haven't found a solution, sorry if I missed it.
