### ISSUE TITLE
readthedocs - table formatting under 1.1

### ISSUE THREAD

**Issue by keiranmraine** [mkdocs/mkdocs#2028]
The formatting under 1.1 has changed quite dramatically for the `readthedocs` option.  Is this intentional?

Table from 1.0.4:

![Screen Shot 2020-03-20 at 16 23 04](https://user-images.githubusercontent.com/3740323/77184234-6ee8ad00-6ac7-11ea-852e-536fa3309e79.png)

Table from 1.1:

![Screen Shot 2020-03-20 at 16 23 15](https://user-images.githubusercontent.com/3740323/77184258-760fbb00-6ac7-11ea-814f-2a23b344857b.png)

My `mkdocs.yml` (variables expanded in bash script):

```yml
site_name: CI reports - $CI_PROJECT_PATH
repo_url: $CI_PROJECT_URL
repo_name: GitLab
edit_uri: null
site_description: CI reports for $CI_PROJECT_PATH
theme:
     name: readthedocs
nav:
$NAV
```
