### ISSUE TITLE
the right of the page not full

### ISSUE THREAD

**Issue by Harryjun** [mkdocs/mkdocs#2049]
There is a blank on the right side of the page I generated with the theme. Did I write something wrong

![image](https://user-images.githubusercontent.com/12987792/78457938-72dc1800-76e0-11ea-98f4-43e7467b2aee.png)

```
site_name: PyTorch Tutorial
site_author: MengLingJun
copyright: Copyright &copy; 2020 <a href="https://www.cloudcver.com">MengLinjun</a>, Maintained by the <a href="https://www.cloudcver.com">CloudCver Team</a>.
#copyright: 'Copyright © 2019-2020 CloudCver All Rights Reserved '
nav:
- 介绍: 'index.md'
- 构建自定义数据集: 'prepare_data.md'
- 关于: 'aboutme.md'
theme: #readthedocs
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - django
markdown_extensions:
- pymdownx.tasklist
- pymdownx.arithmatex
- pymdownx.caret
- pymdownx.critic
- pymdownx.details
- pymdownx.inlinehilite
- pymdownx.magiclink
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.superfences

```
