### ISSUE TITLE
Unable to Create New Page

### ISSUE THREAD

**Issue by Goldenclaw112** [mkdocs/mkdocs#2115]
In the `mkdocs.yml` file I put down the following:
```
site_name: site
nav:
    - Home: index.md
    - About: about.md
```
however, even with this (I've ensured the files are in `docs/`) I'm unable to create new pages.
