### ISSUE TITLE
Problem of rendering color with slate color scheme

### ISSUE THREAD

**Issue by advpetc** [mkdocs/mkdocs#2123]
Hi, thank you for developing this awesome theme!

I have a problem of displaying the line number for my code when using dark mode color scheme:

<img width="499" alt="Screen Shot 2020-06-10 at 11 25 56 PM" src="https://user-images.githubusercontent.com/15725244/84344971-bdab5d80-ab71-11ea-9638-defdce3467af.png">

As you can see from the screenshot, the line number's background color is very similar to the number characters, making it very unidentifiable. Just wondering if there is any workaround for this? Thanks.

Here are the essential part of my mkdocs.yml
```
theme:
  name: material
  palette:
    scheme: 'slate'
    primary: 'blue grey'
    accent: 'teal'
markdown_extensions:
  - codehilite:
      guess_lang: false
      use_pygments: true
      noclasses: true
      pygments_style: monokai
      linenums: true
```
