### ISSUE TITLE
Command line argument to not build hidden/specific pages

### ISSUE THREAD

**Issue by majkinetor** [mkdocs/mkdocs#2125]
Prior to v1.0 this was default behavior and was changed in #699.

While this option is great, there are use cases where I wouldn't like to not build such pages (or specific pages). 

## Example

I keep functional spec, technical docs and user manual in the same mkdocs project. So my nav sections contains something like:

```
...
nav: 
- Functional spec:      #in folder funspec
...
- Tehcnical docs        #in folder techdoc
...
- User manual           #in folder user
...
```

On specific environment, I might want to deploy full docs or only specific sections, such as user manual. I have a script that removes unwanted sections from the nav and produces new config file. I don't want to remove files before build since that is destructive operation and it would be ideal to have some flags to deal with this suh as:

```
# do not build anything not in nav, as before #699 
mkdocs --config-file mkdocs-user.yml --no-hidden    

# better, let us ignore by glob
mkdocs --config-file mkdocs-user.yml --exclude funspec/* --exclude techdoc/*
```

**Comment by DariuszPorowski** [comment]
@majkinetor I had a similar case. I tried to use mkdocs-excludes plugin, but it does not meet my requirements, and unfortunately, it's not maintained anymore.
I developed a plugin for includes/excludes that supports nav filtering based on excludes.

You can find it here: https://github.com/DariuszPorowski/mkdocs-file-filter-plugin#navigation-filtering

It works for me, and I am happy to get feedback, ideas, improvements, etc.

**Comment by majkinetor** [comment]
@DariuszPorowski 

What I ended up doing is changing the mkdocs.yml file in build process to produce new `mkdocs-<section>.yml` file which excludes all other sections. For example:

```yaml
    - exclude:
        glob: [ _*.md ]
        regex: [(funspec|user|admin)/.+]
```

Regex part is empty in `mkdocs.yml` and if I run my build script with parameter, such as `build -Section technical` it excludes funspec, user and admin docs by crafting the above regex and putting it into new `mkdocs-technical.yml`. This works, but its not ideal because real time editing of mkdocs yaml does not propagate to `mkdocs-<section>.yml` as that requires build step.

I took a quick look at your plugin and it seems like mkdocs-exclude on steroids but doesn't really solve my problem (unless I am missing something). What I would need is definining sections (or, you could say, environments, as I publish different docs on different environments but develop all together in single mkdocs repository) and way to build specific one, probalby via env var.

```yaml
- sections:
     fuctional: funspec/*
     technical: tech/*
     user: user/*
     administrative: admin/*    
```

then I would set up which ones I want via env var: `MKDOCS_SECTION: functional, technical` to include only pages in those folders.

If you are willing to do something like that (or equivalent) I can participate in testing on your repo.

**Comment by DariuszPorowski** [comment]
@majkinetor 

I think what you are looking for is supported out-of-the-box, try:

```yaml
# mkdocs.yml -> plugins
- file-filter:
    config: !ENV [MKDOCS_SECTION]
    enabled_on_serve: true # enabled by default
    filter_nav: true # enabled by default
```

and `.file-filter.*.yml` is watching on serve for real time editing.

### exclude technical section only, build the rest

`export MKDOCS_SECTION=".file-filter.technical.yml"`

```yaml
# .file-filter.technical.yml
exclude_regex: [(funspec|user|admin)/.+]
```

### include only admin section, exclude the rest

`export MKDOCS_SECTION=".file-filter.admin.yml"`

```yaml
# .file-filter.admin.yml
include_glob:
  - funspec/*
  - tech/*
  - user/*
  - admin/*

exclude_glob:
  - "*.md"
```
