### ISSUE TITLE
Wrong breadcrumbs order for nested navigation items

### ISSUE THREAD

**Issue by Silthus** [mkdocs/mkdocs#2143]
Originally posted on rtd: https://github.com/readthedocs/readthedocs.org/issues/7263

## Details

* Read the Docs project URL: https://art.silthus.net/en/latest/admin/syntax/
* Build URL (if applicable): https://github.com/art-framework/art-framework/blob/alpha/mkdocs.yml
* Read the Docs username (if applicable): Silthus

## Expected Result

The breadcrumbs on the top of the page should be ordered according to the navigation tree.
The breadcrumbs should show `Docs >> Server Admins >> ART Syntax >> Requirements` instead.

## Actual Result

The breadcrumbs are switched when going beyond three levels deep into the navigation.

![image](https://user-images.githubusercontent.com/755327/86766830-5f2baf00-c04b-11ea-9e8d-409669ff07f8.png)

This is my config:

```yaml
site_name: ART-Framework
site_description: 'Home of the documentation for the ART-Framework.'
site_author: 'Michael Reichenbach'
docs_dir: docs/
repo_url: 'https://github.com/art-framework/art-framework'
nav:
  - Home: index.md
  - 'Server Admins':
    - 'Quickstart': 'admin/quickstart.md'
    - 'Installation': 'admin/installation.md'
    - 'ART Syntax':
      - 'General Syntax': 'admin/syntax.md'
      - 'Actions': 'admin/actions.md'
      - 'Requirements': 'admin/requirements.md'
      - 'Trigger': 'admin/trigger.md'
  - 'Developers':
    - 'Quickstart': 'developer/quickstart.md'
    - 'Creating ART':
      - 'Actions': 'developer/actions.md'
      - 'Requirements': 'developer/requirements.md'
      - 'Trigger': 'developer/trigger.md'
  - 'Issue Tracker': 'https://github.com/art-framework/art-framework/issues'
  - 'About': 'about.md'
theme:
  name: 'readthedocs'
```
