### ISSUE TITLE
Support for relative base_path in markdown_extensions

### ISSUE THREAD

**Issue by dersimn** [mkdocs/mkdocs#2154]
Many extensions need to know the base path of the currently rendered Markdown file, as they are supposed to include assets relative to the markdown file. Two of them are:

- [markdown-include](https://github.com/cmacmackin/markdown-include)
- [pymdownx.snippets](https://facelessuser.github.io/pymdown-extensions/extensions/snippets/)

Both make use of the config variable `base_path` for including other files, so in order to configure it, you would specify:

```yaml
markdown_extensions:
  - pymdownx.snippets:
      base_path: docs
  - markdown_include.include:
      base_path: docs
```

# Currently

Please take a look at this [example repository](https://github.com/dersimn/mkdocs-snippets-issue).

```
|-- README.md
|-- docs
|   |-- big_topic
|   |   |-- index.md
|   |   `-- more_important_code.c
|   |-- index.md
|   `-- smaller_topic
|       |-- hello_world.c
|       `-- index.md
`-- mkdocs.yml
```

Currently you would have to include the `*.c` files with their full path, so in both files you would have to write:

```
    --8<-- "smaller_topic/hello_world.c"
```

```
    --8<-- "big_topic/more_important_code.c"
```

# Why is this bad?

This is fine for Markdown files that are created and maintained for just one website, but we are currently including generic sub topics into our site that are shared among many repositories via `git submodule`. For e.g. some introduction topic on how to set up Docker. It's obvious that include paths must be relative to the Markdown file in this case, like:

```
    --8<-- "hello_world.c"
```

```
    --8<-- "more_important_code.c"
```

# Desirable solution

If we want to be able to specify relative paths in every Markdown file, the `base_path` variable need to change with every Markdown file to be rendered, so it can't simply be included in `mkdocs.yml`.  
This makes my feature request different from #998 #777 #761, because I'm not able to alter the `.md` files as they are shared over multiple projects.

It would be nice if we could specify something like

```yaml
markdown_extensions:
  - pymdownx.snippets:
      base_path: $relative
  - markdown_include.include:
      base_path: $relative
  - one of many other extensions that use exacly 'base_path' as variable:
      base_path: $relative
```

that would then make MkDocs add the currently valid path as `base_path` variable for each rendered Markdown file.

This is an issue for the one who _calls_ the plugin, and not the plugin itself, as an additional (dynamic) `base_path` must be exchanged [at this point in code](https://github.com/mkdocs/mkdocs/blob/ff0b7260564e65b6547fd41753ec971e4237823b/mkdocs/structure/pages.py#L173):

```python
md = markdown.Markdown(
    extensions=extensions,
    extension_configs=config['mdx_configs'] or {}
)
```

Currently (with the upper config from my example), `extension_configs` would contain something in the structure of [this](https://python-markdown.github.io/reference/#extension_configs):

```python
extension_configs = {
    'pymdownx.snippets': {
        'base_path': '$relative'
    },
    'markdown_include.include': {
        'base_path': '$relative'
    }
}
```

We need to replace `$relative` here with the proper path depending on the current navigation.

[1]: https://facelessuser.github.io/pymdown-extensions/faq/#github-ish-configurations

**Comment by ahojukka5** [comment]
I just first time tried `pymdownx.snippets` and yeah, indeed, this would be an awesome feature. I'm still structuring my document tree and probably I have to change all those paths to snippets yet so many times...

**Comment by dersimn** [comment]
Patched version of mkdocs: https://github.com/dersimn/mkdocs
..the change is quite small by the way: https://github.com/dersimn/mkdocs/commit/afbcab87325f40334fd8b80d35c1f17790eefce3
Demo repository + instructions: https://github.com/dersimn/mkdocs-snippets-issue

**Comment by jorgegomezcq** [comment]
Hi, what's the status on this?

**Comment by pawamoy** [comment]
I don't think there was any progress. But I didn't know about this issue and I opened this discussion some time ago: https://github.com/mkdocs/mkdocs/discussions/2833

**Comment by pawamoy** [comment]
I actually very much like the idea of variables provided by MkDocs: `$docs_dir`, `$config_dir`, and whatever else is relevant. I don't care about the syntax: there might be a way to use env vars instead, if MkDocs itself exports them:

```yaml
markdown_extensions:
- pymdownx.snippets:
    base_path: !ENV MKDOCS_CONFIG_DIR
```

**Comment by oprypin** [comment]
I think I'd like to make it work like this:

```yaml
markdown_extensions:
  - pymdownx.snippets:
      base_path:
        - !relative  # Relative to current.md
        - !docs_dir  # Relative to docs_dir
        - !config_dir  # Relative to mkdocs.yml
```

The issue is that indeed now we need some way to dig through the parsed YAML and find and replace the placeholders. There doesn't seem to be any standard way for that.

Alternatively for a solution that's much much cleaner on MkDocs side but worse on the extension side, the value would actually be dynamically computed, but then we'd require each destination extension to call `str(value)` on anything that expects these dynamic values.

Otherwise of course places like this one get an error
https://github.com/facelessuser/pymdown-extensions/blob/67b084e6d14cbfa0c6c457e14aeb0e007f67a91a/pymdownx/snippets.py#L161
`TypeError: stat: path should be string, bytes, os.PathLike or integer, not _YamlPlaceholder`
