### ISSUE TITLE
The text after a checkbox gets forced to a new line

### ISSUE THREAD

**Issue by kaffarell** [mkdocs/mkdocs#2160]
If I create a normal checkbox like this: 
```
## Todo
 * [x] IE support

```
The text "IE support" is on a new line below the checkbox:
![image](https://user-images.githubusercontent.com/42062381/88763914-4a3acb00-d174-11ea-9af4-b1a27de0c6fa.png)

HTML:
![image](https://user-images.githubusercontent.com/42062381/88764023-7fdfb400-d174-11ea-8a8a-cc0feaaaa59b.png)

I fixed this in the frontend (chrome devtools) by adding the `display: inline;` property to the label with the class `task-list-control`.

OS: Windows 10
mkdocs version: 1.1.2
Theme: Read the Docs
Config File:
```
site_name: Parallax
nav:
    - Docs: index.md
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - javascript

markdown_extensions:
    - admonition
    - pymdownx.tasklist:
        custom_checkbox: true


```
Let me know if you need anymore info...
