### ISSUE TITLE
Headings not working with readthedocs sidebar

### ISSUE THREAD

**Issue by snaptopixel** [mkdocs/mkdocs#218]
The [configuration page](http://www.mkdocs.org/user-guide/configuration/) mentions configuring headings using an extra string, but it is not working in the `readthedocs` theme.

The following configuration yields the screenshot below:

``` yaml
site_name: LightSpeed VT Documentation
pages:
- ['index.md', 'Home']
- ['boilerplate/getting-started.md', 'Boilerplate', 'Getting Started']
- ['boilerplate/icons.md', 'Boilerplate', 'Icons']
theme: readthedocs
```

![Sidebar](https://www.dropbox.com/s/5mpuo4unenef0wv/Screenshot%202014-11-13%2010.25.38.png?dl=1)

I would _think_ that the "Getting Started" and "Icons" pages would be listed under a "Boilerplate" heading.

Note that It is possible to get sub menus, but you have to have all content on one page and use headings. This may be the intended behavior.
