### ISSUE TITLE
math expressions 

### ISSUE THREAD

**Issue by timofeev41** [mkdocs/mkdocs#2188]
**Hello there!** I'm trying to create website (using mkdocs) where I can share and edit my math notes. But I can't understand how can I add extensions (such [as](https://facelessuser.github.io/pymdown-extensions/extensions/arithmatex/))
I found only one oppened issue with this topic (it was 5 years ago and solution isn't working)
What can i do now?

**Comment by dhirschfeld** [comment]
In my `mkdocs.yml` I have:
```yaml
# Extensions
markdown_extensions:
  - admonition:
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.details:
  - pymdownx.inlinehilite:
  - pymdownx.mark:
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.arithmatex:
  - pymdownx.tabbed:
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
          custom_icons:
          - assets/.icons

extra_javascript:
  - assets/javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js
  - https://cdn.jsdelivr.net/npm/mermaid@8.5.2/dist/mermaid.min.js
```

***Note:*** the `extra_javascript` section at the bottom. In the `assets/javascripts` folder I have the below `mathjax.js` file:
```js
window.MathJax = {
  tex: {
    tagSide: "right",
    tagIndent: ".8em",
    multlineWidth: "85%",
    tags: "ams"
  },
  options: {
    ignoreHtmlClass: 'tex2jax_ignore',
    processHtmlClass: 'tex2jax_process',
    renderActions: {
      find: [10, function (doc) {
        for (const node of document.querySelectorAll('script[type^="math/tex"]')) {
          const display = !!node.type.match(/; *mode=display/);
          const math = new doc.options.MathItem(node.textContent, doc.inputJax[0], display);
          const text = document.createTextNode('');
          const sibling = node.previousElementSibling;
          node.parentNode.replaceChild(text, node);
          math.start = {node: text, delim: '', n: 0};
          math.end = {node: text, delim: '', n: 0};
          doc.math.push(math);
          if (sibling && sibling.matches('.MathJax_Preview')) {
            sibling.parentNode.removeChild(sibling);
          }
        }
      }, '']
    }
  }
};
```

I can then write latex by setting the code-fence language to `math`.

HTH
