### ISSUE TITLE
Issue when trying to add nav elements - top and left side nav on mkdocs.yml

### ISSUE THREAD

**Issue by NavyaG-lab** [mkdocs/mkdocs#2199]
Hi,
I am trying to have the menu on top and the left side nav with expand and collapse options, so I added

 ```yaml
nav:
      - Home: README.md
      - Data users: dataset/etl/tutorial.md
      - What's new: whats-new.md
```

I've got the error:

**`INFO    -  The following pages exist in the docs directory, but are not included in the "nav" configuration:`**
So, I've added the pages under the nav and it throws error 

**MkDocs encountered as error parsing the configuration file: while parsing a block mapping**

```yaml
nav:
  - Home: README.md
  - Developer documentation:
     - About:
        - Squad 1: 
           - About squads: about/README.md
           - Data Infra history: about/data-infra/history.md
           - Data Infra overview: about/data-infra/overview.md
              - Data Infra languages and stacks: about/data-infra/services-language.md
     -  Runbooks: writing/writing_runbooks.md
      - Alerts: writing/templates/alerts-playbook.md
- Data users:
   - Data: dataset/etl/tutorial.md
```

The following is the theme i am using:

```
theme:
  name: 'material'
  features:
    - instant
```     

Can someone help me with this please?
