### ISSUE TITLE
Build failed when using Gitlab Runner

### ISSUE THREAD

**Issue by SDBonhof** [mkdocs/mkdocs#2250]
Hi,

I have created a simple page that I want to host using gitlab pages. 

I have installed a runner for gitlab to perform my CI pipeline that is defined as described on the [mkdocs-material page](https://squidfunk.github.io/mkdocs-material/publishing-your-site/)
``` 
image: python:3.6.9
pages:
  stage: deploy
  only:
    - master
  script:
    - pip install mkdocs-material
    - mkdocs build --site-dir public
  artifacts:
    paths:
      - public
```

When pushing a commit the runner starts executing the job, installing mkdocs-material successfully. However, once it reaches the `mkdocs build --site-dir public` command, I run into the following error:
![Screenshot from 2020-12-09 14-50-48](https://user-images.githubusercontent.com/31927964/101638105-f26b7500-3a2d-11eb-9a91-b8077962ee1e.png)

I cannot imagine that this is really a python error, more likely something else is not correctly set up but I wouldn't know what. Running the command locally does succeed.

Versions:
```
Ubuntu: 18.04
Python: 3.6.9
mkdocs: 1.1.2
mkdocs-material: 6.1.7
markdown: 3.3.3
```

gitlab-runner/config.toml:
```
concurrent = 1
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "stefan2"
  url = "https://gitlab.tudelft.nl"
  token = "kn9XybypCBo6ZYFxN7gf"
  executor = "shell"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
```

I am not very familiar with runners, but my guess would be that a runner running on my system should use the same packages as when I run it locally?

Thanks in advance!
