### ISSUE TITLE
Failed to pre-build search index. Error: [Errno 2] No such file or directory: 'node'

### ISSUE THREAD

**Issue by inouthack** [mkdocs/mkdocs#2327]
using mkdocs 1.1.2 with lunr 0.5.8

the mkdocs file has the following entry

```yaml
plugins:
      - search:
            lang: en
            prebuild_index: true
      - minify:
            minify_html: true
```

created some test markdown files in a single-level hierarchy to explore mkdocs.

the following error is seen when 'mkdocs serve' or 'mkdocs build' is done.

```
Failed to pre-build search index. Error: [Errno 2] No such file or directory: 'node'
```

as far as i understand 'search' plugin is built-in and needs to be enabled in mkdocs.yml configuration file. 

what could i be missing here. any pointers ?
