### ISSUE TITLE
Parse emoji shortcodes in navbar and table of contents

### ISSUE THREAD

**Issue by jasper-zanjani** [mkdocs/mkdocs#2329]
It appears that emoji shortcodes are only parsed in page bodies but not in the navbar and table of contents. If parsing was done on these other sections then emoji could be used to make them more navigable. I for one would love to be able to have the ability to put icons to make relevant section headings and documents more distinct.

Keep in mind that although I am actually using the material theme and emoji support appears to be poor in general in the default mkdocs theme (the emoji are rendered excessively large, occupying the full width of the enclosing container), I am at least able to reproduce the error in both themes, which means it is not an error specific to material but rather a feature missing in the mkdocs package. 

- The red box on the right shows that an emoji shortcode was not parsed when it occurred in the first-order (`h1`) heading of the document. This shortcode was parsed correctly in the page body (again, excessively large but correct nonetheless).
- The red box on the left shows a second-order (`h2`) heading that was not parsed in the table of contents. Again, the page body did render the emoji.

Note that the emoji that do appear in other headings are literals ("⭐") and not shortcodes ("`:star:`").

![Screenshot 2021-03-17 141728](https://user-images.githubusercontent.com/8889926/111517661-af572700-872b-11eb-9d14-fae98e5b323e.png)

## mkdocs.yml

```yml
site_name: 🧠
theme:
    name: material
    shortcuts:
        search: 191

markdown_extensions:
    - pymdownx.tabbed
    - pymdownx.superfences
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg

```

## Versions

OS: Ubuntu 20.04 (WSL)

- Python 3.8.5
- mkdocs 1.1.2
- mkdocs-material 6.2.3
- pymdown-extensions 8.1
