### ISSUE TITLE
Using relative links above docs_dir

### ISSUE THREAD

**Issue by drwelby** [mkdocs/mkdocs#2348]
I have a standard project structure like:

```
- code
- mkdocs.yml
- changelog.md
- docs
    - doc.md
```

I'm using the default `docs_dir` of `docs` and I'd like to do this in mkdocs.yml:

```yaml
nav:
  - Documentation: doc.md
  - Changelog: ../changelog.md
```

But I can't find a way to make relative links work for markdown sources. Is there another trick to this, or should I just set up the deploy to copy the changelog to the docs directory?
