### ISSUE TITLE
Feature request: Make the search index pipeline configurable

### ISSUE THREAD

**Issue by wilhelmer** [mkdocs/mkdocs#2380]
With the release of [lunr.py 0.6.0](https://pypi.org/project/lunr/0.6.0/), the lunr pipeline is now [configurable](https://lunr.readthedocs.io/en/latest/customisation.html#pipeline-functions). See my [feature request there](https://github.com/yeraydiazdiaz/lunr.py/issues/75).

This means you can now generate a pre-built search index with, e.g., disabled stemming. 

It would be nice to integrate this functionality in the `search` plugin, so we can modify the pipeline when using `prebuilt_index`, as outlined [here](https://github.com/squidfunk/mkdocs-material/issues/1483#issuecomment-597012895):

```yml
- search:
    prebuild_index: python
    pipeline:
        - stemmer: false
        - trimmer: true
        - stopWordFilter: true
```

Currently, themes that modify the pipeline can only do this when the index is not pre-built, leading to inconsistent search behavior depending on whether `prebuilt_index` is enabled or not.

**Comment by squidfunk** [comment]
The syntax could be simplified to:

``` yaml
- search:
    prebuild_index: python
    pipeline:
        - stemmer
        - trimmer
        - stopWordFilter
```

If a transform should be omitted, it could just be dropped from `search.pipeline`, so IMHO there's no need for booleans. That's at least how we solve it over at Material. Also, the order in which the transforms are defined should be honored.

**Comment by wilhelmer** [comment]
Agreed.

**Comment by waylan** [comment]
I'm not opposed to the idea. A PR is welcome. That said, please keep in mind the discussion in yeraydiazdiaz/lunr.py#94.

**Comment by wilhelmer** [comment]
Doesn't the node-based method of pre-building the index have the same problem? We can't configure the pipeline there either.

**Comment by waylan** [comment]
> Doesn't the node-based method of pre-building the index have the same problem? We can't configure the pipeline there either.

Yes, that's correct. However, when search was removed from MkDocs' core and refactored into a plugin, the intention was to simply replicate the basic behavior of the preexisting feature as a demonstration that the new Plugin API worked. However, the hope has always been that a third party search plugin would be created which added additional features and flexibility. We have never intended for the builtin search plugin to be the end-all be-all search solution. Therefore, if anyone wants to configure the pipeline using the node-based method, then that would need to be developed as a third-party plugin as well.

In the end, what I'm saying is that we don't intend to add this feature into MKDocs directly. We would prefer that this be implemented as a third-party plugin. While a plugin could be minimal and subclass the builtin plugin to add on a few features, I think an ideal solution would be for a third party plugin to provide a complete search solution that could become the standard way for users to get search in MkDocs.

**Comment by squidfunk** [comment]
This feature is now implemented in Material for MkDocs' own built-in search plugin and is already part of the v9 beta:

``` yaml
- search:
    pipeline:
      - stemmer
      - trimmer
      - stopWordFilter
```
