### ISSUE TITLE
Question: how to avoid html escape?

### ISSUE THREAD

**Issue by zillionare** [mkdocs/mkdocs#2419]
I had to have some raw html put into my markdown, for example, like this:

```
# this is a header {: #app }
<script>
console.log('load some js here'
</script>
<template>
{{ message }}
</template
```
I need above html not processed by mkdocs/mkdocs-material, and just passed as it is to finaly generated html page, and let js to handle the rest.

However, those raw html tags has been escaped as:
```
&lt;template &gt;
```
so they will not be handled by js.

How to make this happen? I mean, which part is escaping those html tag and is there any option to disable it?

here is my mkdocs.yml (no plugins and extensions)

```yaml
site_name: 
site_url: 
#strict: true

nav:
  - Home: index.md
theme:
  name: material
  language: zh
  palette:
    primary: light blue
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.instant
    - navigation.tabs.sticky
extra_css:
  - stylesheets/extra.css
  - stylesheets/font.css
  - stylesheets/md.min.css
  - stylesheets/vuetify.min.css
extra_javascript:
  - javascripts/vue.js
  - javascripts/vuetify.js
  - javascripts/main.js
```
