### ISSUE TITLE
Docker Image For `mkdocs` + `plantuml`

### ISSUE THREAD

**Issue by loganknecht** [mkdocs/mkdocs#2465]
Hello!

# Gratitude

Thanks for the wonderful tool! It makes our documentation look so professional!

# Use Case

I'm working with `mkdocs` to generate consistent documentation across my organization's team.

# Current Situation

The issue is that we use `GitLab` `Markdown` syntax and by default they support `PlantUML`

I've managed to figure out a way to configure our setup like so

```yaml
markdown_extensions:
    # Code block highlighting
    - pymdownx.highlight
    # Nesting code blocks
    - pymdownx.superfences
    # Insert code from other files
    - pymdownx.snippets
    # Inline code block highlighting
    - pymdownx.inlinehilite
    - plantuml_markdown:
          server: http://www.plantuml.com/plantuml
```

And then I can generate locally like this
```bash
docker run \
		--rm \
		-it \
		--workdir /app \
		--volume $(MAKEFILE_DIRECTORY):/app \
		--entrypoint /bin/sh \
		squidfunk/mkdocs-material \
		-c "pip install plantuml-markdown; mkdocs build --verbose --site-dir documentation_preview"
```

But it would be pretty cool to not obligate me to install pip like this, and instead have an image that allows me to use plantuml with minimal friction.

# Request

- Is there a maintained docker image that includes `PlantUML` that is also approved of by the maintainers of `mkdocs`?
- If not, is it an unreasonable request to have this added to the default docker image?
- If that's not possible, do you have a suggested work around that I have not already discussed?
