### ISSUE TITLE
Getting live reload 404 errors

### ISSUE THREAD

**Issue by framirez-bz** [mkdocs/mkdocs#2474]
Hi there, 
Seeing this error when using `mkdocs serve` to test my site out locally. The site works fine but just wondering why that error keeps popping up.  We are using Material for the theme.

```
WARNING  -  [14:26:07] "GET /livereload HTTP/1.1" code 404
```

Please let me know if you need additional information.

## mkdocs.yml

```
# Project information
site_name: Our Documentation Site
site_description: Internal Site
site_url: <internal_url>
repo_url: <internal_url>
repo_name: Docs Repo

# Navigation
nav:
  - Home: index.md

######################################
##### DO NOT EDIT ANYTHING BELOW #####
######################################

theme:
  name: 'material'
  custom_dir: docs/overrides
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - search.highlight
    - search.suggest
    - search.share
  logo: 'images/logo.png'
  favicon: 'images/siteicon.png'
  font:
    text: 'IBM Plex Sans'
    code: 'IBM Plex Mono'

  palette:
    primary: 'blue'
    accent: 'deep orange'
  icon:
    repo: fontawesome/brands/github
extra_css:
  - 'stylesheets/extra.css'
extra_javascript:
  - javascripts/mathjax-config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/npm/mathjax@3.1.2/es5/loader.js
  - https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.js

# Plugins and Extensions
plugins:
  - search
  - autolinks
  # DO NOT Enable Tags, this is an upcoming feature that I am prepping for. It will break things if you do.
  #- tags:
  #    tags_file: tags.md
  - git-revision-date-localized:
      type: timeago
      locale: en
      fallback_to_build_date: true
      exclude:
        - index.md
markdown_extensions:
  - codehilite:
      guess_lang: true
      use_pygments: true
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: false
      toc_depth: 4
  - fontawesome_markdown
  - markdown_include.include:
      base_path: .
  - meta
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.pathconverter
  - pymdownx.saneheaders
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: .
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.tilde
```

## requirements.txt
```
Babel==2.9.1
click==7.1.2
fontawesome-markdown @ https://github.com/bmcorser/fontawesome-markdown/archive/master.zip
future==0.18.2
ghp-import==2.0.1
gitdb==4.0.7
GitPython==3.1.14
importlib-metadata==4.5.0
Jinja2==2.11.3
joblib==1.0.1
livereload==2.6.3
lunr==0.5.8
Markdown==3.3.4
markdown-include==0.6.0
MarkupSafe==1.1.1
mergedeep==1.3.4
mkdocs==1.2.1
mkdocs-autolinks-plugin==0.4.0
mkdocs-git-revision-date-localized-plugin==0.9.2
mkdocs-material==7.1.8
mkdocs-material-extensions==1.0.1
nltk==3.6.2
packaging==20.9
Pygments==2.9.0
pymdown-extensions==8.2
pyparsing==2.4.7
python-dateutil==2.8.1
pytz==2021.1
PyYAML==5.4.1
pyyaml-env-tag==0.1
regex==2021.4.4
six==1.16.0
smmap==4.0.0
tornado==6.1
tqdm==4.60.0
watchdog==2.1.2
zipp==3.4.1
```
