### ISSUE TITLE
Rendering math equations?

### ISSUE THREAD

**Issue by xin-jin** [mkdocs/mkdocs#253]
Just wondering if it is possible to render math equations?

**Comment by smaret** [comment]
Are these extensions available on readthedoc?

**Comment by d0ugal** [comment]
@smaret from memory, you can have readthedocs build your documentation in a virtualenv and thus have any Python requirements you need. However, I've not tried this in a while.

**Comment by Ken-B** [comment]
@smaret @d0ugal 
I've used latex both inline and equations in markdown for my documentation on readthedoc. I've used [this math extension](https://github.com/mitya57/python-markdown-math).

You can check the setup on [my LAI project](https://github.com/ETC-UA/LeafAreaIndex.jl). Basically, you
* add setup.py and mdx_math.py from the math extension to your `docs` directory
* add to the mkdocs.yml file:
    * `markdown_extensions: [math]`
    * `extra_javascript: ['https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML','mathjaxhelper.js']`
* add a file `mathjaxhelper.js` to your `docs` folder with following content

```
MathJax.Hub.Config({
  config: ["MMLorHTML.js"],
  jax: ["input/TeX", "output/HTML-CSS", "output/NativeMML"],
  extensions: ["MathMenu.js", "MathZoom.js"]
});
```

For readthedocs I also noticed you need an index.md file in your docs directory and listed under `[pages]`, otherwise it will automatically use the README.md file in your main directory, disregarding any files in your docs directory.

**Comment by d0ugal** [comment]
@Ken-B Neat, thanks for that report.

As a side, I'm not a fan of the README customisation ReadTheDocs :)

**Comment by gipi** [comment]
@Ken-B thanks, works pretty well

**Comment by Ken-B** [comment]
I don't know what exactly changed, but my previous solution no longer works. Luckily I've found an easier way.

Use the same (excellent) third-party markdown extension as before: [mdx_math](https://github.com/mitya57/python-markdown-math). Copy the `setup.py` and `mdx_math.py` from this extension to your root project folder.

Now my `mkdocs.yml` contains:

```
python:
   version: 2 # for unicode
   setup_py_install: true

#the third-party extenison mdx_math.py comes with a setup.py script
# Thank you Dmitry Shachnev (https://github.com/mitya57/python-markdown-math) 
markdown_extensions: 
    - mdx_math:
        enable_dollar_delimiter: True #for use of inline $..$
    - fenced_code
    - codehilite
    - footnotes

# Required to load the MathJax javascript for the mdx_math.py
extra_javascript: ['https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML']
```

No need for an extra file with javascript or other files in the `/docs/` directory.
