### ISSUE TITLE
Publish to a subdirectory with gh_deploy

### ISSUE THREAD

**Issue by planetf1** [mkdocs/mkdocs#2534]
I would like to be able to public a MkDocs generated site to a subdirectory on GitHub Pages ie to site/
This allows me to have another action as part of my ci/cd process that also generates GitHub Pages content publishing to non-conflicting files/directories.
In my case I am documenting 'helm charts' as well as serving up a helm repository for Kubernetes.

With MkDocs as it stands I wasn't able to see how to do this, since I needed to ensure the call to ghp_import in https://github.com/mkdocs/mkdocs/blob/master/mkdocs/commands/gh_deploy.py needs to specify a 'prefix' parameter as per https://github.com/c-w/ghp-import : 
```'-x PREFIX, --prefix=PREFIX
                        The prefix to add to each file that gets pushed to the
                        remote. Only files below this prefix will be cleared
                        out. [none]'
```

Additionally I noted that when using ghp_import and publishing without using 'force', and especially if any other activity is updating files in GitHub Pages, it is best to ensure in a GitHub action that a full fetch is done (fetch-depth: 0) so that the branch the action modifies is up to date.

I have ended up with an action as follows for my project at https://github.com/odpi/egeria-charts which so far seems to address this challenge. 
```

 name: "MkDocs"

 on:
   push:
     branches: [main]

 jobs:
   deploy:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
         with:
           # We need all history - we we can later switch to gh-pages
           fetch-depth: 0
       - uses: actions/setup-python@v2
         with:
           python-version: 3.x
       # Ensure we have the latest version of ghp_import
       - run: pip install mkdocs-material ghp_import
       # Manually run the mkdocs build (config is set to use 'site' to publish to)
       - run: mkdocs build
       # mkdocs doesn't allow a subdir to be published to, so run ghp-import directly
       # All content will go to 'site' and will leave root content untouched
       - run: ghp-import site -m 'Updated mkdocs' -p -x site -n
```
It could be useful to add the tip on the fetch to the action docs (and this is something that could be addressed in ghp_import itself - another tool?), but also specifically for this project, to allow the prefix parameter to be passed to ghp_import.
