### ISSUE TITLE
Update RTD theme from upstream

### ISSUE THREAD

**Issue by marcelstoer** [mkdocs/mkdocs#2538]
@waylan last updated the RTD theme from upstream 0.4.1 in 2018 with #1594. Upstream is now at [0.5.2](https://github.com/readthedocs/sphinx_rtd_theme/releases/tag/0.5.2) and I think it's time to bring  MkDocs' copy on-par.

While I _could_ just copy the version into a PR I was wondering if there will be dragons lurking with such an approach. So, maybe someone a bit more familiar with this project could provide insights as for how to properly test such a change.

Btw, what prompted me to look into this was the improved styling of the navigation captions.  
 
<img width="712" alt="Screen Shot 2021-08-08 at 21 35 32" src="https://user-images.githubusercontent.com/624195/128643713-dfead9f1-5a23-49ca-a2ab-f6c4a600336e.png">

I could fix this in my site by adding a few lines to my `extra.css` but I thought updating the theme would be a bit more "sustainable".

```css
.wy-menu-vertical header,
.wy-menu-vertical p.caption {
  color: #55a5d9;
  font-size: 85%;
  margin: 12px 0 0;
}
```
