### ISSUE TITLE
Readthedocs theme css missing blue headlines

### ISSUE THREAD

**Issue by darkdragon-001** [mkdocs/mkdocs#2645]
The following statement is missing in the old version of `mkdocs/themes/readthedocs/css/theme.css`:
```css
.wy-menu-vertical p.caption {
    color: rgb(85, 165, 217)
}
```
