### ISSUE TITLE
Issue with HTML pages

### ISSUE THREAD

**Issue by Stefan-CPlanet** [mkdocs/mkdocs#2678]
Hello, I have project and my yaml page looks like this:

```
site_name: Test Docs
theme:
  name: material
plugins:
  - section-index
nav:
  - HOME: index.md
  - Instruction: instruction.html
```

The issue is that when I click on the HTML page from the menu, The page does open but without mkdocs menu.

I have HTML instead of a markdown page since I have PDF instructions filled with pictures that I need to publish, it's easy to convert to HTML but not so much to Markdown.

What is the proper way to do this?

Also on another note I am running mkdocs with:
`@reboot /usr/bin/tmux new-session -d -s "MKDOCS" "cd /var/www/mkdocs && mkdocs serve -a 192.168.0.5:8080"
`is there a better way to run it in the background?

Thanks
