### ISSUE TITLE
Menu items are not in italic, sections is.

### ISSUE THREAD

**Issue by kierun** [mkdocs/mkdocs#2696]
### Description

![screenshot](https://user-images.githubusercontent.com/3079575/144606956-0f985fc0-30a1-4d64-b91e-46bcb577b19a.png)

The menu showing the different sections does not support italic. However, the section does.

Previously report in [squidfunk/mkdocs-material #3293](https://github.com/squidfunk/mkdocs-material/issues/3293) but it appears to be an upstream issue.

### Expected behaviour

The menu should be in italic as well.

### Actual behaviour

The menu is not in italic.

### Steps to reproduce

1. Create a markdown file with an italic in the title: `# ook _eek_ ook`
2. Run `mkdocs serve`
3. Look at the page, especially at the menu.

### Package versions

```bash
√ ; python --version
Python 3.10.0
√ ; mkdocs --version
mkdocs, version 1.2.3 from /home/usr/.pyenv/versions/3.10.0/lib/python3.10/site-packages/mkdocs (Python 3.10)
√ ; pip show mkdocs-material | grep -E "^Version"
Version: 8.0.2
√ ;  pip show mkdocs
Name: mkdocs
Version: 1.2.3
Summary: Project documentation with Markdown.
Home-page: https://www.mkdocs.org
Author: Tom Christie
Author-email: tom@tomchristie.com
License: BSD
Location: /home/usr/.pyenv/versions/3.10.0/lib/python3.10/site-packages
Requires: click, ghp-import, importlib-metadata, Jinja2, Markdown, mergedeep, packaging, PyYAML, pyyaml-env-tag, watchdog
Required-by: mkdocs-material
```

### Configuration

```yaml
site_name: My Top Secret stuff™
theme:
  name: material
  font:
    text: "PT Sans Narrow"
  favicon: assets/favicon.png
  palette:
    scheme: slate
    primary: teal
  logo: assets/logo.png
  features:
    - navigation.instant
markdown_extensions:
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      use_pygments: true
      auto_title: true
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.superfences
```

### System information

```bash
√ ; uname -a
Linux nightwatch.neverness.org 5.15.6-100.fc34.x86_64 #1 SMP Wed Dec 1 13:41:51 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
√ ; cat /etc/redhat-release
───────┬────────────────────────────────────────────────────────────────────────
       │ File: /etc/redhat-release
───────┼────────────────────────────────────────────────────────────────────────
   1   │ Fedora release 34 (Thirty Four)
───────┴────────────────────────────────────────────────────────────────────────
√ ; firefox --versino
√ ; firefox --version
Mozilla Firefox 94.0
```
