### ISSUE TITLE
Allow users to use a custom `edit_uri` in markdown frontmatter

### ISSUE THREAD

**Issue by HonkingGoose** [mkdocs/mkdocs#2745]
## Intro

I help out with the Renovate documentation site.

I've set things up so that our published documentation pages have a button (pencil icon) that takes the reader to the correct place to edit the source files. This makes it easier to fix small things without having to search for the correct place to make the edit.

## Configuration

- We have a publishing repository: `renovatebot/renovatebot.github.io`
- But most of the source files live here: `renovatebot/renovate`

To get the pencil button working, I needed to manually point to our source repository.

Relevant `mkdocs.yml` config file snippet:

```yml
# Upstream Git repository information
# https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/
repo_name: renovatebot/renovate
repo_url: https://github.com/renovatebot/renovate
edit_uri: edit/main/docs/usage/
```

## Problem

The hard-coded `edit_uri` does not work for files that are not in the `main/docs/usage` folder on the `renovatebot/renovate` repository.

## Proposed solution

We could work around this problem by specifying our own `edit_uri` link in the Markdown frontmatter at the top of the affected files, for example:

```markdown
---
edit_uri: edit/main/lib/manager/ansible/readme.md
---

Supports Docker-type dependency extraction from Ansible configuration files.

If you need to change the versioning format, read the [versioning](https://docs.renovatebot.com/modules/versioning/) documentation to learn more.

...
```

The idea here is that users can override the `edit_uri` that they set in their `mkdocs.yml` config file, but putting a custom `edit_uri` in the source file Markdown frontmatter.

## Previous feature request at `mkdocs/material`

I've opened this feature request at the Material for MkDocs project first. [^feature]
The maintainer of Material for MkDocs thinks this kind of feature belong in the `mkdocs/mkdocs` project, so I'm opening this issue to see what you think. 😉

[^feature]: https://github.com/squidfunk/mkdocs-material/issues/3454
