### ISSUE TITLE
relative url start with "../" in nav no longer works

### ISSUE THREAD

**Issue by akinmr** [mkdocs/mkdocs#2752]
When I tried to make a link to an external resource in `nav` section of mkdos.yml, using the following example, the actual output HTML omits "../" in the relative URL and I couldn't point to external resources out of mkdocs with relative URL.
https://www.mkdocs.org/user-guide/configuration/#nav

The minimal mkdocs.yml to reproduce the problem is as follows:
```yaml
site_name: Example
site_url: https://example.com/foo/

nav:
    - Parent: '../'
    - Sibling: '../some/dir/'
    - Home: './'
    - Index: 'index.md'
```
When I compile it with empty docs/index.md file, the navigation section in site/index.html became as follows:
```html
<!-- Main navigation -->
<ul class="nav navbar-nav">
    <li class="navitem">
        <a href="./" class="nav-link">Parent</a>
    </li>
    <li class="navitem">
        <a href="some/dir/" class="nav-link">Sibling</a>
    </li>
    <li class="navitem">
        <a href="./" class="nav-link">Home</a>
    </li>
    <li class="navitem active">
        <a href="." class="nav-link">Index</a>
    </li>
</ul>
```
What I expect was that the link of "Parent" should point to "../"(= https://example.com/) and the link of Sibling should point to "../some/dir"(=https://example.com/some/dir/), which are outside of the generated doc.

I remember this way (Sibling case) worked in past, but when I recompiled the document with the latest mkdocs,  it started emitting unexpected URL.

**Comment by bloer** [comment]
I just encountered the same issue.  Surprised such a killer bug has not received any response

**Comment by oprypin** [comment]
I confirm that https://github.com/mkdocs/mkdocs/pull/2296 (released in 1.2) changed this behavior.

The thing is, this usage was never supported and always showed warnings anyway:
```
WARNING -  A relative path to '../' is included in the 'nav' configuration, which is not found in the documentation files 
```

In MkDocs nav, relative links are always assumed to be links to Markdown documents within the site.

You can use this appoach instead:
```yaml
site_url: https://example.com/known/absolute/path/

nav:
    - Sibling: '/known/absolute/some/dir/'
```

I am not sure if this will be revisited.
