### ISSUE TITLE
Feature request / question: gzip and brotli & zopfli compression

### ISSUE THREAD

**Issue by do-me** [mkdocs/mkdocs#2779]
### Feature request 

Compression is quite important for fast sites. 

It would be very convenient if mkdocs provided an automatic feature for the most common compression methods like gzip and brotli for static files and zopfli for png's. 

### Question: GitHub Action

Someone wrote a convenient [GitHub action](https://github.com/StefH/ghaction-CompressFiles) but I'm not sure how to integrate it best (also see [this issue](https://github.com/StefH/ghaction-CompressFiles/issues/1)). The problem is that the command `mkdocs gh-pages` is abstracting all steps hence not allowing for simple modifications or steps in between. 

How could the standard [GitHub action](https://squidfunk.github.io/mkdocs-material/publishing-your-site/#github-pages) be tweaked in order to include the above compression action (or any other)? Here's the example for the material theme.

```
name: ci 
on:
  push:
    branches:
      - master 
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material 
      - run: mkdocs gh-deploy --force
```
