### ISSUE TITLE
Edit_url not recognised/ignored

### ISSUE THREAD

**Issue by zierbeek** [mkdocs/mkdocs#2830]
Hi all, I want to create an edit button for the nightly docs of a project. It's on a different branch. I tried several setups of the edit_uri without succes. the browser doesn't seem to even change where it's pointing to .  The edit_uri doesn't seem to have any influence

```yaml
repo_url: https://github.com/hay-kot/mealie/
repo_name: hay-kot/mealie
edit_uri: "edit/mealie-next/docs/docs/"
```
