### ISSUE TITLE
Changes to mkdocs.yml file not picked up during serve while editing site

### ISSUE THREAD

**Issue by aphive** [mkdocs/mkdocs#2900]
When you run `mkdocs serve --dirtyreload` it says:

```
INFO     -  [20:51:58] Watching paths for changes: 'docs', 'mkdocs.yml'
```

This makes it seem like when you make changes to your `mkdocs.yml` it should reload and pick up the changes but for some reason it does not and I have to hard stop and restart the site for changes to be picked up.

Is this by design or is this a bug?

I've tried it with just `mkdocs serve` and `mkdocs serve --livereload` and it does the same thing.

**Comment by oprypin** [comment]
As far as I'm aware, it indeed reloads all such changes. If you believe otherwise, you'll have to show the exact steps so that I could observe your findings myself.

**Comment by aphive** [comment]
Let me know how I can do this and I will work with you.

Basically what's happening at the moment is that I add a new page in the doc dir then add it to the nav section of the mkdocs.yml file, the reload seems to happen on command line but nothing happens on the site itself.

**Comment by aphive** [comment]
Here is the base of my mkdocs.yml

```
site_name: Site Name
site_description: My Site Description

nav:
- Home: 'index.md'
- Requirements: 'requirements.md'
- About: 'about.md'
- Library:
  - Getting Started: 'library/getting_started.md'
  - General Info: 'library/general_info.md'
  - Message Boxes: 'library/message_boxes.md'

######################################
##### DO NOT EDIT ANYTHING BELOW #####
######################################

theme:
  name: 'material'
  custom_dir: docs/overrides
  features:
    - announce.dismiss
    - navigation.indexes
    - navigation.instant
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.suggest
    - search.share

  logo: 'images/site_logo.png'
  favicon: 'images/favicon.png'
  font:
    text: 'IBM Plex Sans'
    code: 'IBM Plex Mono'

  palette:
    primary: 'black'
    accent: 'deep orange'
  icon:
    repo: fontawesome/brands/github
extra_css:
  - 'stylesheets/extra.css'
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6

# Plugins and Extensions
plugins:
  - search
  - autolinks
  - git-revision-date-localized:
      type: timeago
      locale: en
      fallback_to_build_date: true
      exclude:
        - index.md
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - codehilite:
      guess_lang: true
      use_pygments: true
  - def_list
  - footnotes
  - md_in_html
  - meta
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.pathconverter
  - pymdownx.saneheaders
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: .
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - toc:
      permalink: false
      toc_depth: 4
```
