### ISSUE TITLE
Help needed: switching to Hatch build, pyproject.toml

### ISSUE THREAD

**Issue by oprypin** [mkdocs/mkdocs#2989]
* [x] Part 0: https://github.com/mkdocs/mkdocs/pull/2990
* [x] Part 1: https://github.com/mkdocs/mkdocs/pull/2988
* [x] Part 2: https://github.com/mkdocs/mkdocs/pull/2992
* [x] Part 3: https://github.com/mkdocs/mkdocs/pull/2991

I am trying to switch away from setup.py and currently settling on [Hatch](https://hatch.pypa.io/).

I have successfully made the packaging and uploading work correctly and produce ~same wheels.

What I am having trouble with:

* **Our integration with Babel is hard-wired into setup.py**
   https://github.com/mkdocs/mkdocs/blob/8315ece4f66e3c0044908f5cee3b23cff9f03914/setup.py#L39

   https://github.com/mkdocs/mkdocs/blob/1a43c4a111de55fbdd2397dbe5557ec3335665fa/setup.py#L114

   https://github.com/mkdocs/mkdocs/blob/dcf7583e2b8e7d89e731922862e49cabf733ea41/mkdocs/commands/babel.py#L30

    **How can I still perform the same actions without requiring setup.py?**

     * Secondary concern: the configuration of Babel overall is hard-wired into setup.cfg, with no upstream solution.
     * Nice to have: as I understand, running `compile_catalog` should really become a [build hook](https://hatch.pypa.io/1.5/plugins/build-hook/custom/).

* Minor: Flake8 config doesn't understand pyproject.toml

* Nice to have: migrate from Tox to [hatch envs](https://hatch.pypa.io/latest/environment/).
   I got started on that in Part 3^ but having trouble wrapping my head around replacing some messy existing setups:

   * How to get testing with pinned minimal requirements as a separate env
       https://github.com/mkdocs/mkdocs/blob/1a43c4a111de55fbdd2397dbe5557ec3335665fa/tox.ini#L10-L14

       Maybe I have to resort to adding a 'min-versions' extra that is equivalent to the main dependencies but with manually replaced comparisons from `>=` to `==`. Even then it's a bit messy with matrices.

       * Nice to have: what if we didn't have to manually maintain a copied list of minimal dependencies?

   * integration-no-babel :confounded: 

      https://github.com/mkdocs/mkdocs/blob/1a43c4a111de55fbdd2397dbe5557ec3335665fa/tox.ini#L80-L85

      Should it be another env? Is it viable to refactor it to not require an uninstall command? Hm.

   * Matrices are a bit hard to understand but I *think* I'll be able to replace that [in CI](https://github.com/mkdocs/mkdocs/blob/master/.github/workflows/tox.yml)

   * What I don't understand about Hatch: can it really not:
       * Run several *scripts* within one invocation?
       * Group several *scripts* across different environments?
     
      My gripe is that I want several scripts that need empty environments but I want to run them all at once.
      E.g. [this "markdown" style check](https://github.com/mkdocs/mkdocs/commit/dcf7583e2b8e7d89e731922862e49cabf733ea41#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R128) has no business being clumped into the 'style' env (it doesn't use the dependencies), but I was forced to do it just to be able to group the invocations below.
       
      This might lose us some functionality compared to Tox.

cc @ofek (I see you've been helping other projects)
cc @ultrabug

**Comment by oprypin** [comment]
* Tox doesn't like being called without setup.py??

    https://github.com/mkdocs/mkdocs/actions/runs/3168802775/jobs/5160262025
<pre>
> Run <b>python -m tox -e mypy</b>
GLOB sdist-make: /home/runner/work/mkdocs/mkdocs/setup.py
ERROR: No dist directory found. Please check setup.py, e.g with:
     python setup.py sdist
</pre>

**Comment by facelessuser** [comment]
I've actually got babel working on one of my projects with Hatch: https://github.com/facelessuser/Rummage/blob/master/hatch_build.py#L63

**Comment by ofek** [comment]
- > running `compile_catalog` should really become a [build hook](https://hatch.pypa.io/1.5/plugins/build-hook/custom/)

   As @facelessuser mentioned, yup!

- > what if we didn't have to manually maintain a copied list of minimal dependencies?

   Hmm interesting, I could add a custom https://hatch.pypa.io/latest/plugins/environment-collector/reference/ just like build hooks

- > Matrices are a bit hard to understand

   afaict your matrix would be like (in a `hatch.toml`):

   ```toml
   [[envs.default.matrix]]
   python = ["37", "38", "39", "310", "pypy3"]
   type = ["unittests", "min-req", "integration", "integration-no-babel"]
   ```

- > Run several scripts within one invocation?

   Yup https://hatch.pypa.io/latest/config/environment/overview/#scripts

- > Group several scripts across different environments? [...] My gripe is that I want several scripts that need empty environments

   A top-level undocumented `scripts` is supported (and [tested](https://github.com/pypa/hatch/blob/hatch-v1.5.0/tests/cli/run/test_run.py#L495-L532)) where you can just call `hatch run <ENV>:...` several times. The invocation requires a special empty env syntax `hatch run :...`

- > Tox doesn't like being called without setup.py??

   ```ini
   [tox]
   isolated_build = true
   ```

**Comment by oprypin** [comment]
Thanks for the replies! I'll keep working on this and get back if I run into more difficulties.

**Comment by ultrabug** [comment]
Thanks @ofek and @facelessuser 

TIL about Hatch... hmm.

**Comment by oprypin** [comment]
OK! The parts other than switching from tox are done, it went well!

I'll probably want to keep the "Used by" section on GitHub. So I'll probably have to create a fake setup.py :confounded:  ala
[squidfunk/mkdocs-material@`be14b45` (#4341)](https://github.com/squidfunk/mkdocs-material/pull/4341/commits/be14b45f27ac655856383ed6633b1f0792941135)
So I had a little question - is the `install_requires` part of it even necessary? If I don't care about adding my +1 to other projects' "Used by"

**Comment by oprypin** [comment]
And yes, I see how you replace pybabel setuptools integration... by just removing it and reproducing every command manually :sweat_smile:  

Had to be done, then.

* https://github.com/mkdocs/mkdocs/pull/2990

**Comment by ofek** [comment]
> is the `install_requires` part of it even necessary?

Nope!

**Comment by oprypin** [comment]
I am currently looking at the matrix.
Actually not sure if this will work
```toml
type = ["unittests", "min-req", "integration", "integration-no-babel"]
```

Because we're running two different commands for "unittests" and "integration"

**Comment by oprypin** [comment]
I am currently looking at the matrix.
Actually not sure if this will work
```toml
type = ["unittests", "min-req", "integration", "integration-no-babel"]
```

Because we're running two different commands for "unittests" and "integration"

https://github.com/mkdocs/mkdocs/blob/1a43c4a111de55fbdd2397dbe5557ec3335665fa/tox.ini#L14

https://github.com/mkdocs/mkdocs/blob/1a43c4a111de55fbdd2397dbe5557ec3335665fa/tox.ini#L17

What I have for the moment is
```toml
[tool.hatch.envs.test]
dependencies = [
    "coverage",
]
[tool.hatch.envs.test.scripts]
test = "coverage run --source=mkdocs --omit 'mkdocs/tests/*' -m unittest discover -p '*tests.py' mkdocs --top-level-directory ."
[[tool.hatch.envs.test.matrix]]
python = ["37", "38", "39", "310", "pypy3"]
type = ["unittests", "min-req", "integration", "integration-no-babel"]
[tool.hatch.envs.test.overrides]
matrix.type.features = [
    { value = "i18n", if = ["unittests", "integration"] },
    { value = "min-versions", if = ["min-req"] },
]
```

**Comment by ofek** [comment]
haven't tested

```toml
[tool.hatch.envs.test]
dependencies = [
    "coverage",
]
[tool.hatch.envs.test.scripts]
run = ["_info"]  # default with no override match
_info = "python --version"
_test-unit = "coverage run --source=mkdocs --omit 'mkdocs/tests/*' -m unittest discover -p '*tests.py' mkdocs --top-level-directory ."
_test-integration = "python -m mkdocs.tests.integration"
_coverage = [
    "coverage xml",
    "coverage report --show-missing",
]
[[tool.hatch.envs.test.matrix]]
python = ["37", "38", "39", "310", "pypy3"]
type = ["unittests", "min-req", "integration", "integration-no-babel"]
[tool.hatch.envs.test.overrides]
matrix.type.features = [
    { value = "i18n", if = ["unittests", "integration"] },
    { value = "min-versions", if = ["min-req"] },
]
matrix.type.scripts = [
    { key = "run", value = ["_info", "_test-unit", "_coverage"], if = ["unittests"] },
    { key = "run", value = ["_info", "_test-integration"], if = ["integration"] },
    { key = "run", value = ["_info", "_test-unit"], if = ["min-req"] },
]
```

**Comment by oprypin** [comment]
Wowww thanks! That'll be hugely helpful

**Comment by oprypin** [comment]
OK! Opened the next part, it seems to work well!
* https://github.com/mkdocs/mkdocs/pull/2991

Regarding your example, just this part didn't work for me:

```toml
[tool.hatch.envs.test.overrides]
matrix.type.scripts = [
    { key = "run", value = ["_info", "_test-unit", "_coverage"], if = ["unittests"] },
```

``TypeError: Option `value` in entry #1 in field `tool.hatch.envs.test.overrides.matrix.type.scripts` must be a string``

But I used an indirection through strings instead, luckily you're showing that prominently as well :)
