### ISSUE TITLE
GitHub Checkin Build failing in mkdocs/gh-docs with Node.js 12 actions are deprecated

### ISSUE THREAD

**Issue by valhuber** [mkdocs/mkdocs#3086]
My GitHub checkins are failing with as shown below.

I know this has been discussed in Stack Overflow, but if there was a fix I missed it.  I did do the [mkdocs upgrade](https://squidfunk.github.io/mkdocs-material/upgrade/), it did not help.  The `pip show mkdocs-material` shows: 

```
Name: mkdocs-material
Version: 9.0.0
Summary: Documentation that simply works
Home-page: 
Author: 
Author-email: Martin Donath <martin.donath@squidfunk.com>
License: 
Location: /Users/val/dev/ApiLogicServer/venv/lib/python3.10/site-packages
Requires: colorama, jinja2, markdown, mkdocs, mkdocs-material-extensions, pipdeptree, pygments, pymdown-extensions, regex, requests
Required-by: 
```

<img width="1319" alt="GitHub Checkin Fails" src="https://user-images.githubusercontent.com/5579631/210254120-d9e08d4c-df94-46b2-8ada-86819c61a2a9.png">

Project: [https://github.com/valhuber/ApiLogicServer](https://github.com/valhuber/ApiLogicServer).

with: https://github.com/valhuber/Docs-ApiLogicServer

**Comment by valhuber** [comment]
Fixed, many thanks to [this posting](https://discourse.julialang.org/t/node-js-12-actions-deprecation-warning-on-github/88718).

Edit your yaml file (access as shown below), and alter `uses: actions/checkout@v2` to `v3` as shown below:

```yaml
name: ApiLogicServer
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material 
      - run: mkdocs gh-deploy --force
 ```

<img width="1253" alt="edit-actions-yaml" src="https://user-images.githubusercontent.com/5579631/210600467-dbd848d2-1106-468f-81e0-b14e84be56f2.png">
