### ISSUE TITLE
markdown in div row is not aligned horizontally 

### ISSUE THREAD

**Issue by lrlunin** [mkdocs/mkdocs#3115]
Hello everybody,
thank you for such a powerful tool for building my documentation. I am now trying to reproduce [this example ](https://yakworks.github.io/docmark/cheat-sheet/#row-divs) with markdown code aligned in the same row. I added this to my `mkdocs.yml`:
```yaml
markdown_extensions:
    # Python Markdown
    - abbr
    - attr_list
    - toc:
          permalink: true
          toc_depth: "2-6"
    - pymdownx.highlight
    - admonition
    - pymdownx.details
    - pymdownx.progressbar
    - pymdownx.extra
```
and added the following code in order to test two possible layouts in my `installation.md` file:
```html
<div class="two-column" markdown="1">

!!! warning
    expected left

</div>
<div class="two-column" markdown="1">

!!! warning
    expected right

</div>  
<div class="row" markdown="1">

| Column1 | Column2 |
| ------- | ------- |
| 1       | 1       |

| Column3 | Column4 |
| ------- | ------- |
| 2       | 2       |

!!! warning
    expected right

</div>
```
However none of this two examples works as expected and I have both of the block takes the whole width of the page:
![image](https://user-images.githubusercontent.com/1849145/215323135-f6cca6ae-74c9-45d0-9bd2-a212c6c4407d.png)
