### ISSUE TITLE
[Feature Request] Less confusing edit_uri implementation

### ISSUE THREAD

**Issue by tyleraharrison** [mkdocs/mkdocs#3121]
## Summary

When setting the `edit_uri` to something like: `edit/main/docs/`, it looks like the word `edit` in the URI is automatically being parsed to the word `raw` for viewing. Generally, its probably bad practice to replace the string `edit` with `raw`. If someone is using a Git repo that has edit and view functionality but the URI does not have the word `edit` in it (or the viewing URI isn't `raw`), they will not be able to use the `content.action.view` feature. Below are some test results of trying different values for `edit_uri`:

| Test | edit_uri | Edit Link | View Link | Notes |
| --- | --- | --- | --- | --- |
| No `edit_uri` | Not set | `repo/edit/master/docs/` | `repo/raw/master/docs/` | Expected behavior |
| Include `edit` | `edit/main/docs/` | `repo/edit/main/docs/` | `repo/raw/main/docs/` | Expected behavior |
| Replace `edit` | `lorem_ipsum/main/docs/` | `repo/lorem_ipsum/main/docs/` | `repo/lorem_ipsum/main/docs/` | Generates the same URL |
| Omit `edit` | `main/docs/` | `repo/main/docs/` | `repo/main/docs/` | Generates the same URL |
| Move `edit` | `lorem_ipsum/edit/main/docs/` | `repo/lorem_ipsum/edit/main/docs/` | `repo/lorem_ipsum/raw/main/docs/` | Expected behavior (?) |

## Details

- Platform: I've tested with the following:
  - `Ubuntu 22.04.1 LTS, Linux kernel 5.17.5, x86_64` with Python `3.10.6`
  - Docker `python:3.9-alpine` image

- MkDocs version: `9.0.11`

- MkDocs-Material version: `1.4.2`

- `mkdocs.yml`:

```yaml
site_name: ...
site_url: ...
site_description: ...
site_author: ...
repo_url: https://github.com/(author name)/(repo name)
repo_name: (repo name)
remote_branch: main
edit_uri: 'edit/main/docs/'

nav:
    - Home: index.md

theme:
    name: material
    features:
        - content.action.edit
        - content.action.view
```

## Recommendations

I think the easiest way to do this is to allow the user to specify a `view_uri` and an `edit_uri`. Keeping the old `edit_uri` behavior should be fine, but in addition allow the use of `view_uri` to fix any mismatch in URIs.
