### ISSUE TITLE
readthedocs theme does not follow configuration options

### ISSUE THREAD

**Issue by quarkytale** [mkdocs/mkdocs#3187]
Regarding configuration options as explained in https://github.com/mkdocs/mkdocs/blob/master/docs/user-guide/choosing-your-theme.md, my project's `mkdocs.yml` has the following set:
```
theme:
    name: readthedocs
    prev_next_buttons_location: none
    navigation_depth: 2
    collapse_navigation: True
    titles_only: False
    sticky_navigation: False
```
but the resulting site built does not follow that. There's still the "Previous" and "Next" buttons functioning. And the side navigation bar drops down to show all titles even when `collapse_navigation` is True (issues https://github.com/mkdocs/mkdocs/issues/3111 and https://github.com/mkdocs/mkdocs/issues/1904 still valid).

This happens when the nav bar entry has more than 3 levels
```
 - Section:
   - Category1:
     - 'Entry 1': entry1.md
     - 'Entry 2': entry2.md
   - Category2:
   <etc>
```

Other options seem to be functioning as expected.
