### ISSUE TITLE
[FR] Alternative setting for highlightjs

### ISSUE THREAD

**Issue by redtide** [mkdocs/mkdocs#3189]
Current:
```yml
highlightjs: true
hljs_languages:
- ...
hljs_style: ...
```
Alternative:
```yml
highlightjs:
  languages:
     builtin:
     - cpp
     extra (or custom or whatever):
     - relative or abs url to customlanguage.min.js
  style: ...
```
or if #2171 would be (finally) a thing (or not, needs some strategy to support also only 1 mode by defining 1 of  2):
```yml
highlightjs:
  ...
  style:
    light: same as hljs_style
    dark: dark hljs theme to use on dark mode
```
