### ISSUE TITLE
Missing tables when using ``mkdocstrings`` to generate api-ref under the theme ``readthedocs``

### ISSUE THREAD

**Issue by chensgit169** [mkdocs/mkdocs#3378]
version info: ``python=3.11.4``, ``mkdocs==1.5.2``, ``mkdocstrings==0.23.0``

Generated docs by the following ``mkdocs.yml``
```YAML
site_name: My Docs
theme: readthedocs

nav:
  - Home: index.md
  - Language Switch: language.md
  - Quick Start:
      - Basics: basics.md
      - Developments: developments.md
  - API reference: my_package_docs.md  # apiref here!

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [../..]
        options:
          docstring_style: google
  - search
```
where ``my_package_docs.md`` use command of ``mkdocstrings``:
```markdown
::: my_package
    
```
The problem I encountered is that there is no **table box** for **Parameters** and **Returns**, which is not expected:
![image](https://github.com/mkdocs/mkdocs/assets/109205133/387bac67-0333-4580-9401-6311b237cbc8)

I have tried other theme including ``mkdocs``, ``material``... And they worked exactly fine, yet ``readrgedocs`` is just the theme I need. I wonder if someone has met the same problem and may help. Thank you in advance.
