### ISSUE TITLE
Extending search.separator seems not to work

### ISSUE THREAD

**Issue by Kevin-De-Koninck** [mkdocs/mkdocs#3410]
## Description

`plugins[].search.separator` seems not to work in version `1.5` (tested with `1.5.2` and `1.5.3`). I extended it with ''[\s\-\.]+'' in order to allow searching for dots. But this change is not reflected in the search results. as soon as I add a dot in the search box, no results appear.

The relevant config snippet:

```  yaml
plugins:
  - search:
      separator: '[\s\-\.]+'  # Add dot as a word separator
```

The previous version that I used was `1.2.3`. In that version, extending the search separator worked.
