### ISSUE TITLE
YAML inherit breaking the search plugin

### ISSUE THREAD

**Issue by nbanyan** [mkdocs/mkdocs#3422]
I am using yml INHERIT to seperate site specific configuration settings from settings that should be the same across all my team's MkDocs projects.  To do this I have a `mkdocs-core.yml` that the `mkdocs.yml` inherits from.  The `plugins` section should be listed in the `mkdocs-core.yml`, but when I do that the `search` plugin breaks (the search box doesn't render) if the `exclude` plugin is also declared.  But if they are declared in the `mkdocs.yml`, they work without issue.  The behavior suggests it is a problem with inheritance, but could it be a bug/quirk with `exclude` instead?

```yml
plugins:
  - search
  - offline
  - exclude:
      glob:
        - "mkdocs/snippet example.md"
 ```
