### ISSUE TITLE
Google Analytics 4 tag not appearing in <head>

### ISSUE THREAD

**Issue by djenkins-nefco** [mkdocs/mkdocs#3478]
I've read through #2252 and it seems the end result there was the addition of this syntax:
```
extra:
  analytics:
    provider: google
    property: G-***********
```
However, when adding that to my mkdocs.yml and publishing, there is nothing in the `<head>` and Google doesn't detect the tag.

The Mkdocs guide still references `google_analytics: ['UA-**********', 'site-name.org']`, which must be old and the Material docs reference the same method above.

**Comment by orlasp** [comment]
I'm having the same issue. As another option I added a gtag.js file into the extra javascripts and pointed to that in the .yml but that didn't make any difference. Currently Analytics says "Your Google tag wasn't detected on your website." Any suggestions would be great.

**Comment by tomchristie** [comment]
Let's close this off in favor of https://github.com/mkdocs/mkdocs/issues/3630

Including GA should be supported as a template override, not a config option.

**Comment by mhcpan** [comment]
try this: 

```
theme:
  name: mkdocs
  analytics:
    gtag: G-XXXXXXXXXX
```
