### ISSUE TITLE
readthedocs theme hides nav items when the window height is too small to contain them

### ISSUE THREAD

**Issue by cha0s** [mkdocs/mkdocs#348]
If you have a nav with a bunch of items and then make the screen height too small so that a scrollbar appears, the scrollbar won't go all the way down, because the prev, next, Github footer thing is covering it.

You can fix this by adding a CSS rule like:

```css
.wy-menu-vertical ul {
    margin-bottom: 2em;
}
```

though you may prefer another approach. This works though.
