### ISSUE TITLE
readthedocs: `prev_next_buttons_location` always at bottom - not working?

### ISSUE THREAD

**Issue by r-heimann** [mkdocs/mkdocs#3483]
According to the mkdocs documentation you can use `prev_next_buttons_location` to move the buttons to a different position:

https://www.mkdocs.org/user-guide/choosing-your-theme/#readthedocs

```
prev_next_buttons_location: One of bottom, top, both , or none. Displays the “Next” and “Previous” buttons accordingly. Default: bottom.
```

But none of the options seem to change anything, its always on the bottom. Is this a bug?

Example `mkdocs.yml`:

```yaml
site_name: Test
theme: 
  name: readthedocs
  prev_next_buttons_location: 'both'
  titles_only: true
site_dir: public
```
