### ISSUE TITLE
is_homepage is False if the homepage contains subpages

### ISSUE THREAD

**Issue by joserebelo** [mkdocs/mkdocs#3551]
Our homepage contains multiple subpages:

```yml
nav:
  - Home:
    - index.md
    - page2.md
    - page3.md
```

In the is_homepage property:

https://github.com/mkdocs/mkdocs/blob/7186f4ce9c88e7c445ef90fee85c065ca297a7c8/mkdocs/structure/pages.py#L134-L136

the `page.is_top_level` property is False for the homepage index page.

It's not clear to me what the impact of removing the is_top_level from the condition would be.
