### ISSUE TITLE
Cannot build documentation from behind symlink.

### ISSUE THREAD

**Issue by icedwater** [mkdocs/mkdocs#3565]
I can't build a documentation folder that is symlinked from somewhere else, but copying it in is fine. I'll also file this bug on @squidfunk's [repo](https://github.com/squidfunk/mkdocs-material), in case something in the docker distribution is causing the issue.

## Steps to reproduce:

1. Create a test folder, `~/abcd`.
2. Write a simple `test.md` into the directory, e.g. `echo # hello > abcd/test.md`.
3. Symlink this test folder into the docs_dir: `ln -s /home/user/abcd /data/mkdocs/docs`.
4. Check that the symlink works: `ls -l /data/mkdocs/docs`.
5. The documentation server refuses to update, citing the error shown [here](https://superuser.com/q/1827866).
6. Remove the symlink: `rm /data/mkdocs/docs/abcd`.
7. Copy the folder into the docs_dir: `cp -r abcd /data/mkdocs/docs/efgh`.
8. The site only refreshes after a `docker-compose restart`, showing the `Efgh` directory.

The following are my mkdocs.yml, 
**mkdocs.yml**
```yml
dev_addr: '10.10.0.10:3333'
docs_dir: /docs/docs

site_name: Tips and Tricks

theme:
    name: 'material'

markdown_extensions:
    toc:
        permalink: true
```

**docker-compose.yml**
```yml
version: '3'

services:
  mkdocs:
    image: squidfunk/mkdocs-material
    ports:
      - "3333:8000"
    volumes:
      - /data/mkdocs:/docs
    stdin_open: true
    tty: true
    restart: unless-stopped
```
