### ISSUE TITLE
Content only uses half the width available

### ISSUE THREAD

**Issue by MartinHugh** [mkdocs/mkdocs#3597]
We have documentation which contains text and tables from .md markup (which is deployed using mike as we are also using versioning).

The version selector/menu occupies the left 15% of the screen which fine, however of the remaining 85%, only the left hand half is used. The right hand 42% or so is blank,

This looks a little odd when showing text, but much worse, nearly all the tables displayed require horizontal scrolling in order to see all the columns.

Is there a way of working around this?

mkdocs.yml is as follows

```
site_name: Product Documentation

theme:
  name: readthedocs
  locale: en
  navigation_depth: 3
  include_sidebar: false
  icon:
    repo: fontawesome/brands/git


plugins:
  - search:
      separator: '[\s\-\.]+'
      min_search_length: 3
      indexing: 'full'

repo_url: <removed>
repo_name: 'Github'
edit_uri: 'blob/main/docs/'

nav:
  - Home: 'index.md'
  - User Manual: 'user_manual.md'
  - Troubleshoot: 'troubleshoot.md'
  - About: 'about.md

```
