### ISSUE TITLE
plugin autorefs installed but not found

### ISSUE THREAD

**Issue by binooetomo** [mkdocs/mkdocs#3685]
Hi.
I need to have link to a cell of table.
So I installed [mkdocs-autorefs](https://github.com/mkdocstrings/autorefs). 

```
(venv)  ✘ bino@corobalap  ~/zonesync   main ±  pip freeze
Babel==2.14.0
certifi==2024.2.2
charset-normalizer==3.3.2
click==8.1.7
colorama==0.4.6
configparser==6.0.1
deepdiff==7.0.1
dnspython==2.6.1
ghp-import==2.1.0
idna==3.6
Jinja2==3.1.3
Markdown==3.6
MarkupSafe==2.1.5
mergedeep==1.3.4
mkdocs==1.6.0
mkdocs-autorefs==1.0.1
mkdocs-get-deps==0.2.0
mkdocs-material==9.5.19
mkdocs-material-extensions==1.3.1
ordered-set==4.1.0
packaging==24.0
paginate==0.5.6
pathspec==0.12.1
platformdirs==4.2.1
ply==3.11
Pygments==2.17.2
pymdown-extensions==10.8
python-dateutil==2.9.0.post0
PyYAML==6.0.1
pyyaml_env_tag==0.1
regex==2024.4.16
requests==2.31.0
six==1.16.0
tomli==2.0.1
urllib3==2.2.1
watchdog==4.0.0
```

my mkdocs.yml
```
site_name: ZoneSync
plugins:
  - search
  - autorefs

markdown_extensions:
  - tables
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight:
      #use_pygments: true
      line_spans: __span
      anchor_linenums: true
      pygments_lang_class: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
theme:
  name: material
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - content.code.copy
    - content.tooltips
    - content.code.annotate

extra:
  annotate:
    json: [.s2]

```

but when I do 'mkdocs serve', got error

```
(venv)  ✘ bino@corobalap  ~/zonesync   main ±  mkdocs serve
ERROR   -  Config value 'plugins': The "autorefs" plugin is not installed

```
