### ISSUE TITLE
Substring search does not work

### ISSUE THREAD

**Issue by Sero42** [mkdocs/mkdocs#3693]
When Searching for "HandsOn" in a documentation that contains a chapter with name "(HandsOn)" nothing is found

**Comment by 9ao9ai9ar** [comment]
Use Material for MkDocs's [search settings](https://squidfunk.github.io/mkdocs-material/plugins/search/#config.separator):

```yaml
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'

```
