### ISSUE TITLE
sourcing an external js library with in mkdocs

### ISSUE THREAD

**Issue by gauravcodepro** [mkdocs/mkdocs#3722]
Hi, i am trying to source an external js library with in mkdocs such as highcharts and chartsjs but it is not rendering the chart. even in case of the plotly, the chart is not rendering when the build is done and deployed unless you put a ``` !<DOCTYPE hmtl> and then it renders. 

Can you point me to the page or the link where an external js can be called without calling the HTML tag as to deply it with in the container. I put the js into the /docs/javascripts/plot-charts.js 

thank you,
Gaurav

**Comment by pawamoy** [comment]
Sorry but it's unclear. Show us what you tried, and explain what is not working as expected.

You can pass URLs to external files in the `extra_javascript` setting.

**Comment by gauravcodepro** [comment]
@pawamoy thank you for the response and please see below the asked information. 
```
site_name: genomes
site_url: mywebsite address
plugins:
  - search: {}
  - encryptcontent: {}
extra_javascript:
  - javascripts/chart.js
theme:
  name: cosmo
nav:
  - Home: main.md
 ```
So here i am trying to put a chart plotting library in a folder named javascript in the docs folder and then using all the sub-functions. However, when i am rendering it, it is not taking the plots in the web render. 

However, when i put the <!DOCTYPE html> as the file indicating it is as HTML file rather than a markdown syntax file, the plots are rendered. 

Let me know if anything else need to be changed. I will try also passing the url of the same. 

Thank you,
Gaurav

**Comment by gauravcodepro** [comment]
@pawamoy 

so, for a trial run. i added the link such as 
```
site_name: genomes
site_url: mywebsite address
plugins:
  - search: {}
  - encryptcontent: {}
extra_javascript:
  - <script src="https://cdn.plot.ly/plotly-2.33.0.min.js" charset="utf-8"></script>
theme:
  name: cosmo
nav:
  - Home: main.md
 ```
and the build went through and so do the serve but getting the following and the plots are not rendering.  
```
WARNING -  [20:07:58] "GET /genomes/%3Cscript%20src=%22https:/cdn.plot.ly/plotly-2.33.0.min.js%22%20charset=%22utf-8%22%3E%3C/script%3E HTTP/1.1" code 404
```
Thank you,
Gaurav
