### ISSUE TITLE
multiple pymdownx.superfences supported?

### ISSUE THREAD

**Issue by BioLaoXu** [mkdocs/mkdocs#3769]
I like mkdocs, but I want to use both mermaid and vegalite plugins, here is my mkdoc.yml configuration, but he only supports mermaid, if I change the position of the two plugins, when the vegalite is configured in front, vegalite will take effect and mermaid will not work:

```
markdown_extensions:
    - pymdownx.superfences: 
          custom_fences: 
              - name: mermaid
                class: mermaid
                format: !!python/name:mermaid2.fence_mermaid_custom
    - pymdownx.superfences: 
          custom_fences: 
              - name: vegalite
                class: vegalite
                format: !!python/name:mkdocs_charts_plugin.fences.fence_vegalite
```

I would like to know how to configure pymdownx.superfences for multiple third-party plugins, and expect your reply,thanks!

**Comment by facelessuser** [comment]
`custom_fences` is a list, put all of your custom fences under it, not under two separate `pymdownx.superfence` instances:

```
markdown_extensions:
    - pymdownx.superfences: 
          custom_fences: 
              - name: mermaid
                class: mermaid
                format: !!python/name:mermaid2.fence_mermaid_custom
              - name: vegalite
                class: vegalite
                format: !!python/name:mkdocs_charts_plugin.fences.fence_vegalite
```
