### ISSUE TITLE
MkDocs Builds Successfully Locally but Not Reflecting Changes on ReadTheDocs

### ISSUE THREAD

**Issue by xueyil9** [mkdocs/mkdocs#3779]
### Description

I have successfully updated and pushed changes to the `merge-my-changes` branch on GitHub, but these changes are not being reflected on ReadTheDocs. The build process seems to work locally, but the updates do not appear on the ReadTheDocs site.

### Configuration

Here is the content of my `readthedocs.yml` configuration file:

```yaml
# Read the Docs configuration file for MkDocs projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

mkdocs:
  configuration: mkdocs.yml

# Optionally declare the Python requirements required to build your docs
python:
  install:
  - requirements: docs/requirements.txt
```

This is my local url and the screen shot:
<img width="869" alt="image" src="https://github.com/user-attachments/assets/596c88b7-45b7-49a7-9018-9e2e52b30b88">

<img width="1249" alt="image" src="https://github.com/user-attachments/assets/1ee61c3c-a2ad-4d6f-b57d-ead4b7f4fec8">

### Current Situation

1. I have pushed updates to the merge-my-changes branch on GitHub: [Github](https://github.com/BYU-Hydroinformatics/baseflow/tree/merge-my-changes)
2. I have manually triggered a build on [ReadTheDocs](https://baseflow.readthedocs.io/en/latest/)
3. The build logs show no obvious errors, but the documentation on ReadTheDocs has not been updated to reflect the latest changes.

### Attempted Solutions
Verified mkdocs.yml and docs/requirements.txt configurations.

### Request for Help
Could you please help me with the following:

1. Are there any additional configuration settings I might need to adjust?
2. Are there other potential reasons why the documentation is not updating on ReadTheDocs?
3. Is there any other configuration or step that needs to be checked?

Thank you for your assistance!
