### ISSUE TITLE
Consider adding FontAwesome icons for admonitions in base.css

### ISSUE THREAD

**Issue by daviewales** [mkdocs/mkdocs#3780]
Font Awesome is already included in MkDocs.
So it makes sense to use it to add icons to the default admonitions.

See the following CSS for example:

``` css
/* Fancy icons in admonitions... (Font Awesome 4.7.0) */

.admonition.note > .admonition-title::before {
  font-family: FontAwesome;
  /* fa-pencil */
  content: "\f040 ";
  margin-right: 0.5rem;
}

.admonition.info > .admonition-title::before {
  font-family: FontAwesome;
  /* fa-info-circle */
  content: "\f05a ";
  margin-right: 0.5rem;
}

.admonition.warning > .admonition-title::before {
  font-family: FontAwesome;
  /* fa-warning */
  content: "\f071 ";
  margin-right: 0.5rem;
}

.admonition.danger > .admonition-title::before {
  font-family: FontAwesome;
  /* fa-bomb */
  content: "\f1e2 ";
  margin-right: 0.5rem;
}
```

I'm on an older version of MkDocs, so the above is tested for Font Awesome 4.7 on MkDocs 1.5.2.
But the same concept with small tweaks should work for the latest version.

It may also make sense to include the Font Awesome icons in the HTML, rather than with the CSS hack above.

Example:

![image](https://github.com/user-attachments/assets/6439c23a-bd90-4cfd-b10e-0938c7d5584f)

Note: I extracted the `content: "\f1e2"` values directly from `font-awesome.css` (v.4.7.0).
