### ISSUE TITLE
Missing plugin glightbox creates error on docker image squidfunk/mkdocs-material

### ISSUE THREAD

**Issue by apizarro-wpt** [mkdocs/mkdocs#3868]
After adding the Lightbox plugin we can't build our project anymore. Currently our pipeline gives us this error:

```
$ mkdocs build --site-dir public
ERROR   -  Config value 'plugins': The "glightbox" plugin is not installed
Aborted with a configuration error!
Cleaning up project directory and file based variables 00:01
ERROR: Job failed: exit code 1
```

This has been reported [on this issue](https://github.com/blueswen/mkdocs-glightbox/issues/45) for mkdocs-glightbox by someone else. 

Locally, I used "pip install mkdocs-glightbox" and I can use `mkdocs serve` without issues. I can even do `mkdocs build` without issues.

I tried replicating this error using `docker run --rm -it --entrypoint sh squidfunk/mkdocs-material` to run the docker image locally and I get the same error.

Our current workaround is using `pip install mkdocs-glightbox` before `mkdocs build --site-dir public` on our pipeline.

Our mkdocs.yml is this (some parts have been censored):

```
site_name: CloudOps Documentation 
site_url: !ENV SITE_URL
site_author: Alberto Pizarro
site_description: >-
  how-to.

# Repository
repo_name: CloudOps
repo_url: https://gitlab.com/foo/documentation/

# Copyright
copyright: Copyright &copy; 2024 foo

# Configuration
theme:
  language: es
  name: material
  logo: assets/logo.png
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    # - scheme: default
    #   primary: indigo
    #   accent: indigo
    #   toggle:
    #     icon: material/brightness-7
    #     name: Switch to dark mode
    # - scheme: slate
    #   primary: black
    #   accent: indigo
    #   toggle:
    #     icon: material/brightness-4
    #     name: Switch to light mode
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - scheme: default
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo
    annotation: material/information

# Plugins
plugins:
  - blog
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - glightbox:
      zoomable: true


# Additional configuration
extra:
  annotate:
    json: [.s2]
  social:
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/foo


# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - sane_lists
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: docs
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Inicio: index.md
```
