### ISSUE TITLE
MD extension `attr_list` doesn't seem to work.

### ISSUE THREAD

**Issue by mbraakhekke** [mkdocs/mkdocs#3870]
I'd like to link to arbitrary markdown elements in my docs. From what I understand, that should be possible by including Python Markdown extension `attr_list` and adding an `id` using `#`. But I can't get it to work. See below for a minimal example. The first line get's rendered as `foo {: #foo }`. The link doesn't work either. Am I doing something wrong?

`mkdocs.yaml`:
```yaml
site_name: My Docs
markdown_extensions:
  - attr_list
```
`index.md`:
```markdown
foo {: #foo }

[ref](#foo)
```
