### ISSUE TITLE
Dropdown submenu marker invisible (regression in 1.6.1 since 1.5.2)

### ISSUE THREAD

**Issue by daviewales** [mkdocs/mkdocs#3909]
Navigation dropdown menus with submenus should have a submenu indicator.

In MkDocs 1.5.2 this looks like the following:

![Image](https://github.com/user-attachments/assets/4853a964-6d77-4aec-875c-58dea53f15e2)

However, this indicator is invisible in MkDocs 1.6.1:

![Image](https://github.com/user-attachments/assets/f6e81b29-feb6-469e-9b6d-199f431c3dce)

It does appear when you hover over it however, so it's just a styling issue:

![Image](https://github.com/user-attachments/assets/2cee578b-75d8-4b7c-8bab-de87e5444e9a)

## Workaround

Looking at a wiki produced with MkDocs 1.5.2, the following CSS was defined:

``` css
.dropdown-submenu > a::after {
	border-left-color: #ccc;
}
```

In 1.6.1, this changed to:

``` css
.dropdown-submenu > a::after {
	border-left-color: var(--bs-dropdown-link-active-color);
}
```

`var(--bs-dropdown-link-active-color)` appears to be defined as `#fff` rather than `#ccc`, which is why the marker is no longer visible. (White marker on white background.)

A quick workaround is to copy the old `.dropdown-submenu > a::after` definition above into your custom CSS.
