### ISSUE TITLE
If the anchor contains spaces or connectors, it cannot respond

### ISSUE THREAD

**Issue by jaywhj** [mkdocs/mkdocs#3920]
Hi, there are a lot of problems with the parsing of title anchors, such as titles containing spaces, containing characters other than English, capitalizing the first letter of English words, etc., which are not parsed and responded to properly. But the sidebar navigation automatically generated by mkdocs is normal.

And it compiles with an exception:

```
INFO    -  Doc file 'index.md' contains a link '#Test-1', but there is no such anchor on this page.
INFO    -  Doc file 'index.md' contains a link '#Test2 layout', but there is no such anchor on this page.
INFO    -  Doc file 'index.md' contains a link '#Test3', but there is no such anchor on this page.
```

this is a minimal reproduction：

[test-anchor.zip](https://github.com/user-attachments/files/18658979/test-anchor.zip)

**Comment by pawamoy** [comment]
Anchors are created by "slugifying" titles:

- `Test 1` becomes `#test-1`
- ` Test2 layout` becomes `#test2-layout`
- `Test3` becomes `#test3`

Try linking to these headings with the slugified anchors 🙂

**Comment by pawamoy** [comment]
I'm going to close as I believe this is working as intended!

**Comment by jaywhj** [comment]
@pawamoy i got it.

If the header is composed of Chinese or Chinese overlaid with English, how should I configure this kind of anchor link? I have already set permalink.

```
markdown_extensions:
  - toc:
      permalink: true
```

Like this:

```
## 中文标题-Python
## 预处理

<!-- how should I configure this kind of anchor link? -->
click [中文标题-Python](#中文标题-Python)
click [预处理](#预处理)
```

**Comment by pawamoy** [comment]
If the default `slugify` setting of the `toc` extension doesn't work well with Chinese characters, you could try this:

```yaml
markdown_extensions:
  - toc:
      permalink: true
      slugify: !!python/object/apply:markdown.extensions.toc.slugify_unicode
```

See https://python-markdown.github.io/extensions/toc/.

Alternatively, `pymdownx` also provides a slugify function:

```yaml
markdown_extensions:
  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}
```

See [https://python-markdown.github.io/extensions/toc/.](https://facelessuser.github.io/pymdown-extensions/about/releases/9.0/#one-slugify-to-rule-them-all).
