### ISSUE TITLE
"GET /%E5%B7%A5%E5%85%B7/mkdocs-pulisher/ HTTP/1.1" code 404,  non-English letters bug

### ISSUE THREAD

**Issue by Extious** [mkdocs/mkdocs#3953]
Here is my environment: 

![Image](https://github.com/user-attachments/assets/78d8dcf1-882f-47c1-acb2-c10a619f448e)
I have Chinese letters in my path:

![Image](https://github.com/user-attachments/assets/0284f3ca-1dca-44cd-b3a3-fff658490cb8)
Therefore , I can't found the page in this path:

![Image](https://github.com/user-attachments/assets/cb7a8457-a09b-428b-bb31-d574371e5a82)

![Image](https://github.com/user-attachments/assets/30438f3c-2155-43ff-842b-980096d5f208)
This is my config file:
```yaml
site_name: My Docs
theme:
  name: material
plugins:
  - pub-meta
  - search 
  - pub-obsidian:
      obsidian_dir: .obsidian
      templates_dir: _template
```
I use the plugin:  [mkdocs-publisher](https://github.com/mkdocs-publisher/mkdocs-publisher)
I have found a similar issue  https://github.com/mkdocs/mkdocs/issues/2463
But I still have this problem now.
Hope to get the answer.
