### ISSUE TITLE
Include some files from other repo? set the base url?

### ISSUE THREAD

**Issue by huglester** [mkdocs/mkdocs#575]
Hello,

I am playing with documenting some projects. But came to problem, where:

For example, I have documented modules like news, projects, navigation.

But now I need to write documentation for different websites for these modules. so actually only the 'base_url' which is mentioned in the pages will be used. is there a way to set it?

Other problem I see, is that, for example, I would like to make documentation of the news module in one place, navigation - other place.
And then, later, when I build the docs, I just link the external modules and compile them in...

That way, later, when news.md is updated on the main repo, I can rebuild every other page with it, just running the build command and it would fetch the updated repo, or something like that.

ANy ideas? Thanks

**Comment by d0ugal** [comment]
I'm not sure I fully understand. Is the main problem that you want to build markdown files across multiple repos?

**Comment by huglester** [comment]
There are two problems I am facing,

1 question:
in the readme, I often link to the main site, like:
`example.com/admin/pages`
`example.com/admin/navigation`

but using this, if I build readme for different pages, I need to find/replace `example.com` with `newdomain.com`

I think it would be good idea to add something like this in the config:
```yaml
theme: readthedocs
variables:
    base_url: 'http://test.com'
    some_var: 'test variable'
```
so in the markdown files, we could somehow use this variables. Maybe this is now possible? but I simply don't know how this is doable?

2 question is:
is there a way to build a markdown from external (i.e. git (gitlab), gist files)? 

So for example, I keep the main navigation.md file updated, and the `mkdocs build` would just git clone/pull this file/repo or something like this... Maybe config could look like:
```yaml
pages:
    About CMS: 'index.md'
    - 
      filename: 'news.md'
      title: 'News module'
      git: 'git@git.test.lt:docs/docs/module-news.git'
```

**Comment by waylan** [comment]
Regarding your first question, you can assign your own variables to [`extra`][1]:

```yaml
extra:
    base_url: 'http://test.com'
    some_var: 'test variable'
```

Anything in `extra` will get passed directly to the template. Of course, you will need to use a custom theme to make use of those variables.

Regarding your second question, that seems to me to be out of scope for MkDocs. You might want to look at git submodules or something similar. You would then need to run a git command to make sure everything it up-to-date before running `mkdocs build`.

[1]: http://www.mkdocs.org/user-guide/configuration/#extra
