### ISSUE TITLE
Allow not showing "Home"

### ISSUE THREAD

**Issue by vlcinsky** [mkdocs/mkdocs#765]
MkDocs navigation bar has items: [MkDocs][Home][User Guide][About]

Typically, the first two items lead to the same page.

When I try to optimize my site for mobile devices, sometime I need to keep navigation bar as short as possible.

I would like to have an option to have my "Home" not being shown as it is already navigated to by clicking the first item in the navigation bar. At the same time, I want to ensure, the `index.md` page is rendered.

Any idea, how to do that?

**Comment by d0ugal** [comment]
You can add [custom CSS](http://www.mkdocs.org/user-guide/configuration/#extra_css) to your documentation, that then gives you the flexibility to do what you want. This is one possible approach:

```css
.nav.navbar-nav li:first-child{
    display: none;
}
```

**Comment by vlcinsky** [comment]
Thanks @d0ugal for very clear and quick reaction.

This will work for us.

Adding file `docs/nohome.css` with the content:

```css
.nav.navbar-nav li:first-child{
    display: none;
}
```
and keeping value of `extra_css` in `mkdocs.yml` empty resulted in first button (`Home`) being hidden.

Nice.

**Comment by waylan** [comment]
Try this:

```css
.nav.navbar-nav>li:first-child{
    display: none;
}
```

Notice the inclusion of the `>` instead of a space, which ensures that the rule only applies to a direct child, not children nested at multiple levels.
