### ISSUE TITLE
Parent menu item links to current page in multi-level page navigation

### ISSUE THREAD

**Issue by chipsenkbeil** [mkdocs/mkdocs#779]
So, I have multiple levels of navigation (abbreviated below):

```yaml
pages:
    - About:
        - Roadmap: about/roadmap.md
        - Release Notes: about/release-notes.md
        - Scaladoc:
            - Scaladoc 2.10: external/scaladoc-2.10.md
            - Scaladoc 2.11: external/scaladoc-2.11.md
        - Contributing: about/contributing.md
        - License: about/license.md
```

![screen shot 2015-12-23 at 5 16 54 pm](https://cloud.githubusercontent.com/assets/2481802/11986771/0f63d3b2-a999-11e5-9624-b601582076ea.png)

What I've noticed is that the `Scaladoc` menu item (highlighted above) has a link that matches the current page url. E.g. When I am on the page `http://localhost:8000/advanced-topics/what-is-the-profile-system/`, the `Scaladoc` menu item has a link to that page.

I was expecting `#` or `#!` for the link such that clicking on the menu item with children did not send me to a new page (even if it is the same page).

Does that make sense? Was this link intended? I'm assuming so, but wanted to double-check.
