### ISSUE TITLE
Plantuml support

### ISSUE THREAD

**Issue by coding2012** [mkdocs/mkdocs#901]
This would be a cool addition:
https://github.com/mikitex70/plantuml-markdown

**Comment by d0ugal** [comment]
You can already use this with Markdown extensions. http://www.mkdocs.org/user-guide/configuration/#markdown_extensions

**Comment by coding2012** [comment]
That's my aha moment! I just need to read more how to use the extension system.

Thanks!

**Comment by mikaelhg** [comment]
```bash
pip install plantuml-markdown
```

```yaml
markdown_extensions:
  - plantuml_markdown:
      server: http://www.plantuml.com/plantuml
```
