### ISSUE TITLE
Color edit through custom css?

### ISSUE THREAD

**Issue by banj** [mkdocs/mkdocs#963]
We'll be deployment multiple sites built on MkDocs using the default theme and I'm hoping to provide easy visual differentiation by changing the blue navbar color to red, purple, green, etc- so that it's fast to tell the difference, similar to the configuration options available in the Material theme.

I was looking through the css to try to figure out what custom css I could pass to get the different color effect I want, but I had trouble extracting the piece I would need- the example in the docs addresses changing the text color easily, I'm hoping for a similarly straight-forward tweak for the header color.

Deeply appreciate anyone who is able to point me in the right direction, I'll be continuing to dig into this

**Comment by waylan** [comment]
This is something we need to address in #607. We have done some work on the HTML (available in the next release), but haven't improved the situation for overriding/customizing the CSS yet. Even worse, we have no clear direction in mind for this either.

@banj I realize this doesn't answer your question (I would have to go look at the CSS just the same as you), but I'm just connecting this to the bigger issue. Of course, any feedback about what we can do to make this easier from real users is always welcome.

**Comment by waylan** [comment]
Looks like you are looking for this CSS in [`bootstrap-custom.min.css`][1]:

```css
.navbar {
    background-image: -webkit-linear-gradient(#54b4eb,#2fa4e7 60%,#1d9ce5);
    background-image: linear-gradient(#54b4eb,#2fa4e7 60%,#1d9ce5);
    background-repeat: no-repeat;
    border-bottom: 1px solid #178acc;
    filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#ff54b4eb',endColorstr='#ff1d9ce5',GradientType=0);
    filter: none;
    -webkit-box-shadow: 0 1px 10px rgba(0,0,0,0.1);
    box-shadow: 0 1px 10px rgba(0,0,0,0.1);
}
.navbar-default {
    background-color: #2fa4e7;
    border-color: #1995dc;
}
```

[1]: https://github.com/mkdocs/mkdocs/blob/master/mkdocs/themes/mkdocs/css/bootstrap-custom.min.css
